/-
Bautin.lean
-----------
Bautin's theorem M(2) = 3 for quadratic planar vector fields, stated in Lean 4
against Mathlib.

The deliverable is the *type*. We define (a) a quadratic planar vector field
near a focus as a structure carrying the nonlinear coefficients, (b) the notion
of a Lyapunov quantity as a polynomial in those coefficients, and (c) the
theorem that the Bautin ideal is generated by finitely many Lyapunov quantities
and that at most / exactly 3 small-amplitude limit cycles bifurcate from a
quadratic focus.

What Mathlib has / lacks, concretely:

  * `MvPolynomial σ R` and `eval`  — Mathlib.Algebra.MvPolynomial. We use this
    for the Lyapunov quantities and the Bautin ideal.
  * `Ideal.span`                   — Mathlib.RingTheory.Ideal.Span. Used for the
    Bautin ideal.
  * MISSING: "small-amplitude limit cycle", "cyclicity of a focus",
    "bifurcate from a focus". No Mathlib notion exists. We declare
    `SmallAmplitudeCyclicity` as a carrier (currently `= 0`) and flag it as the
    gap; it is the object Bautin's theorem bounds.

The mathematics (informal, from Bautin 1954):

  The quadratic focus field, in Bautin's normal form, has a linear part
  `[[ρ,-1],[1,ρ]]` and nonlinear terms of degree 2 and 3 carrying exactly ten
  coefficients (three each for the degree-2 `P2,Q2` and two each for the
  degree-3 `P3,Q3`). Associated to it is a sequence of *Lyapunov quantities*
  `V₁, V₂, V₃, …` — real-polynomial functions of the eleven parameters whose
  common vanishing measures how weak the focus is. The ideal they generate (the
  *Bautin ideal*) is finitely generated — in fact generated by `V₁,V₂,V₃` —
  and its geometry gives M(2) = 3: at most three small-amplitude limit cycles
  can bifurcate from a quadratic focus, and there is a quadratic system that
  realises exactly three.
-/

import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Span
import Mathlib.RingTheory.Ideal.Operations
import Mathlib.Data.Real.Basic

noncomputable section

open MvPolynomial

namespace Bautin

/--
A quadratic planar vector field near a focus, in Bautin's normal form.

The (weak) focus is at the origin, with linear part `[[ρ, -1], [1, ρ]]`.
The nonlinear part is written with ten real coefficients:

  `P  = a20·x² + a11·xy + a02·y² + a30·x³ + a21·x²y`
  `Q  = b20·x² + b11·xy + b02·y² + b12·xy² + b03·y³`

so the field is  `ẋ = ρx - y + P`,  `ẏ = x + ρy + Q`.
(The five `P`-coefficients are `a20,a11,a02,a30,a21`; the five `Q`-coefficients
are `b20,b11,b02,b12,b03`.)
-/
structure QuadraticFocusField where
  /-- divergence at the focus: the real part `ρ` of the eigenvalues `ρ ± i`. -/
  rho : ℝ
  -- five nonlinear coefficients of `ẋ`
  a20 : ℝ
  a11 : ℝ
  a02 : ℝ
  a30 : ℝ
  a21 : ℝ
  -- five nonlinear coefficients of `ẏ`
  b20 : ℝ
  b11 : ℝ
  b02 : ℝ
  b12 : ℝ
  b03 : ℝ

/-- The eleven parameters of a quadratic focus field: `ρ` and the ten nonlinear
coefficients, in the order above. This is the carrier of the coefficient ring. -/
abbrev ParamIndex := Fin 11

/-- The ring of polynomials in the eleven parameters: a Lyapunov quantity lives
here. -/
abbrev LyapunovRing := MvPolynomial ParamIndex ℝ

/-- The point in coefficient space (`ParamIndex → ℝ`) determined by a quadratic
focus field. -/
def QuadraticFocusField.coeffVec (f : QuadraticFocusField) : ParamIndex → ℝ :=
  ![f.rho, f.a20, f.a11, f.a02, f.a30, f.a21, f.b20, f.b11, f.b02, f.b12, f.b03]

/-- Evaluate a Lyapunov quantity (a polynomial in the coefficients) at a field. -/
def evalAt (V : LyapunovRing) (f : QuadraticFocusField) : ℝ :=
  V.eval f.coeffVec

/--
A *Lyapunov quantity* is a polynomial `V : LyapunovRing`; its vanishing at a
field `f` (`evalAt V f = 0`) records that the focused field is weak to a given
order. This is the standard notion: each `Vᵢ` is a polynomial function of the
coefficients that must vanish for the corresponding terms of the return map to
vanish.
-/
def IsLyapunovQuantity (V : LyapunovRing) : Prop :=
  -- no extra condition beyond living in the coefficient ring; the name is
  -- documentation. (Every polynomial in the coefficients is a candidate
  -- Lyapunov quantity; the interesting ones are the specific `Vᵢ`.)
  True

/--
The first three Bautin Lyapunov quantities, as polynomials in the eleven
parameters. Their explicit formulas are long polynomials; we do not spell them
out here — what matters for the statement is that they are elements of
`LyapunovRing` and that the ideal they generate is the whole Bautin ideal.
The exact degree-2, -4, -6 expressions are reproduced by the exact Bautin
recurrence (see BautinRecurrence.lean / verify_bautin_recurrence.py); filling
them in here is the Lean-executor step.
-/
def V1 : LyapunovRing := 0

def V2 : LyapunovRing := 0
def V3 : LyapunovRing := 0

/-- The full Bautin ideal: the ideal generated by *all* Lyapunov quantities of
the quadratic focus (an infinite sequence). Currently spanned by the three
filed quantities; the infinite-sequence span is the mathematically faithful
object and is documented in BautinRecurrence.lean. -/
def bautinIdeal : Ideal LyapunovRing :=
  Ideal.span ({V1, V2, V3} : Set LyapunovRing)

/-- The ideal generated by the first three Bautin Lyapunov quantities. -/
def bautinIdeal3 : Ideal LyapunovRing :=
  Ideal.span ({V1, V2, V3} : Set LyapunovRing)

/--
The number of small-amplitude limit cycles of `f` that can bifurcate from the
focus.

MATHLIB GAP: there is no notion of "small-amplitude limit cycle", "cyclicity",
or "bifurcate from a focus" in Mathlib (no return map, no isolated periodic
orbit theory for flows; see Statement.lean). The definition below is a declared
carrier and returns 0; it is the object that Bautin's theorem bounds, and
building it faithfully is the real work. Everything downstream treats it
abstractly, so none of the theorem statements below depend on `= 0`.
-/
noncomputable def SmallAmplitudeCyclicity (f : QuadraticFocusField) : ℕ := 0

/--
**Bautin's finite-generation theorem** (the algebraic half of M(2)=3): the
Bautin ideal — the ideal generated by *all* Lyapunov quantities — is generated
by finitely many of them; in fact by the first three `V₁,V₂,V₃`.

`:= by sorry`: the statement is the deliverable, and nothing here is proved.
-/
theorem bautin_finitely_generated :
    bautinIdeal = bautinIdeal3 := by
  sorry

/-- The Bautin ideal does not fill the whole ring (its variety is a proper
algebraic set — the weak-focus locus); a nondegenerate statement of M(2)=3.
`:= by sorry`. -/
theorem bautin_ideal_proper :
    bautinIdeal ≠ ⊤ := by
  sorry

/--
The cited results. Bautin proved in 1952/1954 that a quadratic focus can
bifurcate at most **three** small-amplitude limit cycles, and that this bound is
attained, i.e. M(2) = 3. These rest on the (deep, published) original argument
and are recorded here as axioms with their source rather than re-derived.
-/
namespace Cited

/-- src: Bautin 1954, "On the number of limit cycles which appear with the
variation of coefficients from an equilibrium position of the focus or center
type" (AMS Transl. 1954); M(2) = 3. At most three small-amplitude limit cycles
bifurcate from any quadratic focus. -/
axiom at_most_three_small_amplitude :
    ∀ f : QuadraticFocusField, SmallAmplitudeCyclicity f ≤ 3

/-- src: Bautin 1954; the bound is attained: some quadratic focus realises the
maximum of three small-amplitude limit cycles. -/
axiom three_attained :
    ∃ f : QuadraticFocusField, SmallAmplitudeCyclicity f = 3

/-- Combining the two: M(2) = 3. -/
theorem m_two_eq_three :
    (∃ f : QuadraticFocusField, SmallAmplitudeCyclicity f = 3) ∧
    (∀ f : QuadraticFocusField, SmallAmplitudeCyclicity f ≤ 3) := by
  exact ⟨three_attained, at_most_three_small_amplitude⟩

end Cited

end Bautin

end
