/-
Certificate.lean
-----------------
The GENERAL certificate lemma for ideal non-membership, standalone and
self-contained. It is the "cofactor linear-functional quotient" shape of the
alternative route (see Lib/L8NotInIdeal_alt.lean):

   If a ring hom φ : R → S annihilates f1 and f2 and does NOT annihilate f3,
   then f3 ∉ ⟨f1, f2⟩ (the ideal of R generated by f1, f2).

Why it is true. Every element of the ideal is a sum a·f1 + b·f2; applying φ and
using φ f1 = 0, φ f2 = 0 sends every such element to 0 in S. If f3 were in the
ideal, φ f3 would be 0, contradicting φ f3 ≠ 0. This is the whole argument —
no Gröbner basis, no Buchberger — and it is the same idea the evaluation
witness in Bautin.lean uses, lifted to arbitrary rings and homomorphisms.

Why the homomorphism is the right general packaging. In the Bautin instance,
R = MvPolynomial (Fin 6) ℚ and φ = MvPolynomial.eval p for a point p. The
image ring S is ℚ; "φ annihilates L4, L6" is "L4 and L6 vanish at p" and
"φ does not annihilate L8" is "L8(p) ≠ 0". Each evaluation point p gives one
proof of the SAME non-membership statement — that is the independent-route
machinery, and it is exactly the theorem stated here, at full generality.

This file closes the general lemma with no `sorry` and no cited axiom; the
Bautin instance with its concrete focal values and certificate points lives in
Lib/Bautin.lean (point certPt) and the second, non-proportional point certPt2
is stated in Lib/L8NotInIdeal_alt.lean.
-/

import Mathlib.RingTheory.Ideal.Span
import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval

noncomputable section

open Ideal

namespace Certificate

/--
The general certificate lemma for ideal non-membership.

`R` is any commutative semiring carrying the elements whose ideal membership is
in question; `S` is any commutative semiring we can evaluate in. A ring
homomorphism `φ : R →+* S` trivialising `f1, f2` and nontrivial on `f3` proves
`f3 ∉ Ideal.span {f1, f2}`.

This is the "cofactor linear-functional quotient" certificate: `φ` is the
quotient-to-`S` linear functional separating `f3` from the span of `f1, f2`.
-/
theorem eval_cert_nonmem
    {R S : Type*} [CommSemiring R] [CommSemiring S]
    (φ : R →+* S) (f1 f2 f3 : R)
    (h1 : φ f1 = 0) (h2 : φ f2 = 0) (h3 : φ f3 ≠ 0) :
    f3 ∉ Ideal.span ({f1, f2} : Set R) := by
  intro hmem
  obtain ⟨a, b, hmem_eq⟩ := mem_span_pair.1 hmem
  have hφ : φ f3 = 0 := by
    rw [← hmem_eq]
    simp [map_add, map_mul, h1, h2]
  exact h3 hφ

#print axioms eval_cert_nonmem

/--
The same certificate when the homomorphism is the evaluation map of a
polynomial ring: a point `p` of `R` at which f1 and f2 vanish and f3 does not
refutes membership. This is the shape the Bautin witnesses use, and it is
`eval_cert_nonmem` with `φ = MvPolynomial.eval p`.
-/
theorem eval_point_cert_nonmem
    {R : Type*} [CommSemiring R]
    {σ : Type*} (p : σ → R) (f1 f2 f3 : MvPolynomial σ R)
    (h1 : MvPolynomial.eval p f1 = 0)
    (h2 : MvPolynomial.eval p f2 = 0)
    (h3 : MvPolynomial.eval p f3 ≠ 0) :
    f3 ∉ Ideal.span ({f1, f2} : Set (MvPolynomial σ R)) := by
  exact eval_cert_nonmem (MvPolynomial.eval p) f1 f2 f3 h1 h2 h3

#print axioms eval_point_cert_nonmem

end Certificate

end
