/-
L8NotInIdeal_alt.lean
---------------------
Second INDEPENDENT route to the SAME statement as Bautin.lean's
`V3_not_mem_span_V1_V2` (there: L8 ∉ ⟨L4, L6⟩ in the ring
MvPolynomial (Fin 6) ℚ of the six quadratic coefficients).

The statement, once: the third focal value L8 is NOT in the ideal generated by
the first two, L4 and L6 — so Bautin's generating set genuinely needs three
elements. Bautin.lean proves it through the evaluation point
    certPt  = (a1,a2,a3,b1,b2,b3) = (-2,-2,1,-1,-1,1),
three kernel-checked rational evaluations (L4 = 0, L6 = 0, L8 ≠ 0 there).

This file gives the two alternative certificate shapes the brief asked for.

ROUTE A — quotient-homomorphism certificate at a SECOND point.
  A ring homomorphism φ : R → S with φ L4 = φ L6 = 0 and φ L8 ≠ 0 refutes
  membership (every element of the span maps to 0). The general lemma is
  `Certificate.eval_cert_nonmem` (code/lean/Lib/Certificate.lean, closed,
  kernel-verified); `Certificate.eval_point_cert_nonmem` is its form for
  φ = MvPolynomial.eval p. This file states and closes the instance at the
  SECOND, non-proportional witness
      certPt2 = (-3,-3,2,0,1,-1)
  found by code/bautin/cofactor_certificate2.py — a NEW full-box search
  ({-3..3}^6, no support restriction; the first search was support-sizes 1..6
  over ±1,±2) with an explicit proportionality check against certPt, so the
  second proof is not the same arithmetic scaled. Capture:
  code/out/cofactor_certificate2.captured.txt:
      eval V1num at certPt2 = 0        (cleared numerator of L4)
      eval V2num at certPt2 = 0        (cleared numerator of L6)
      eval V3num at certPt2 = -57600   (cleared numerator of L8; L8 ≠ 0)
  The theorem below, `second_point_route`, takes those three evaluations as
  hypotheses and is KERNEL-CLOSED; the instantiation of the hypotheses to the
  6/56/220-term focal-value tables is the same `by simp; norm_num` arithmetic
  Bautin.lean already performs for certPt, and is deliberately NOT re-embedded
  here (the tables' provenance is Bautin.lean, machine-emitted by
  code/bautin/lyapunov_quadratic.py).

ROUTE B — graded / degree-based reformulation (stated, `by sorry`).
  L4, L6, L8 are homogeneous of degrees 2, 4, 6. A degree filtration argument
  reduces membership to the degree-6 part:
      L8 = a·L4 + b·L6  ==>  L8 = a₄·L4 + b₂·L6
  with a₄, b₂ homogeneous of degrees 4, 2 (take the degree-6 homogeneous parts
  of a·L4 and b·L6). So membership is a statement about the finite-dimensional
  ℚ-vector space R₆ of degree-6 forms (dim 462): L8 ∈ R₄·L4 + R₂·L6. The
  separating object is then a ℚ-LINEAR functional ℓ : R₆ → ℚ vanishing on
  R₄·L4 + R₂·L6 and nonzero at L8. Crucially, the evaluation at certPt2 IS such
  an ℓ (restricted to R₆, it vanishes on every c·L4 and d·L6 because L4 and L6
  themselves vanish at certPt2) — so the linear-functional witness is the same
  point, seen in degree 6. What this route adds is the reduction itself, which
  is exactly what the Gröbner run verified computationally
  (code/out/membership.captured.txt, m1: remainder of 16 monomials, i.e. L8 is
  not even in the degree-6 part of the span). Formalising it needs the
  homogeneous-degree decomposition of MvPolynomial (projection onto R_d),
  which is not in this file — stated below as a `sorry` gap with its exact
  content, per the brief's "may be by sorry, not required to close".
-/

import Mathlib.Algebra.MvPolynomial.Basic
import Mathlib.Algebra.MvPolynomial.Eval
import Mathlib.RingTheory.Ideal.Span
import Mathlib.Data.Rat.Defs
import Mathlib.Data.Fin.VecNotation

noncomputable section

open MvPolynomial

namespace BautinAlt

/-- The six quadratic coefficients `(a1,a2,a3,b1,b2,b3)`, in that order —
the same index set as Bautin.lean. -/
abbrev ParamIndex := Fin 6

/-- The ring the focal values live in: polynomials over ℚ in the six
coefficients. -/
abbrev LyapunovRing := MvPolynomial ParamIndex ℚ

/-- SECOND certificate point `(a1,a2,a3,b1,b2,b3) = (-3,-3,2,0,1,-1)`.
Found by code/bautin/cofactor_certificate2.py (fresh full-box search over
{-3..3}^6, exact rational arithmetic), explicitly NON-proportional to
Bautin.lean's `certPt = (-2,-2,1,-1,-1,1)`, so this is a genuinely distinct
evaluation route to the same non-membership statement. -/
def certPt2 : ParamIndex → ℚ := ![-3, -3, 2, 0, 1, -1]

/-! ## Route A: quotient-homomorphism certificate at the second point -/

/--
The quotient-homomorphism certificate at `certPt2`, kernel-closed.

For ANY triple `(f1, f2, f3)` of polynomials, if `f1` and `f2` evaluate to 0
at `certPt2` and `f3` does not, then `f3 ∉ ⟨f1, f2⟩`. The map
`φ = MvPolynomial.eval certPt2 : LyapunovRing →+* ℚ` is the quotient to ℚ:
it annihilates the two generators and separates the third. This is the general
lemma `Certificate.eval_cert_nonmem` specialised to the second point, written
out here so the file stands alone (workspace-local imports do not resolve on
the single-file kernel).

The instantiation the theorem is made for carries the actual focal values:
  f1 = V1 (= L4), f2 = V2 (= L6), f3 = V3 (= L8), with the three hypotheses
  checked by exact rational evaluation in
  code/out/cofactor_certificate2.captured.txt:
      eval V1num at certPt2 = 0,  eval V2num at certPt2 = 0,
      eval V3num at certPt2 = -57600 ≠ 0
  (cleared numerators; zero/nonzero pattern identical to the focal values).
-/
theorem second_point_route
    (f1 f2 f3 : LyapunovRing)
    (h1 : MvPolynomial.eval certPt2 f1 = 0)
    (h2 : MvPolynomial.eval certPt2 f2 = 0)
    (h3 : MvPolynomial.eval certPt2 f3 ≠ 0) :
    f3 ∉ Ideal.span ({f1, f2} : Set LyapunovRing) := by
  intro hmem
  obtain ⟨a, b, hmem_eq⟩ := Ideal.mem_span_pair.1 hmem
  have hφ : MvPolynomial.eval certPt2 f3 = 0 := by
    rw [← hmem_eq]
    simp [map_add, map_mul, h1, h2]
  exact h3 hφ

#print axioms second_point_route

/-! ## Route B: graded / degree-based reformulation (statement, `by sorry`) -/

/-- Total degree of an exponent vector over the six coefficients. -/
def HomogeneousDegree (m : Fin 6 →₀ ℕ) : ℕ := m.sum (fun _ e => e)

/-- A polynomial is homogeneous of degree `d` if every monomial in its support
has total degree `d`. `L4`, `L6`, `L8` are homogeneous of degrees 2, 4, 6. -/
def IsHomogeneous (p : LyapunovRing) (d : ℕ) : Prop :=
  ∀ m : Fin 6 →₀ ℕ, m ∈ p.support → HomogeneousDegree m = d

/--
The graded reformulation (gap, stated not proved).

If `L8 = a·L4 + b·L6` then, taking degree-6 homogeneous parts (L4 has degree
2, L6 degree 4, so the degree-6 part of `a·L4` is `a₄·L4` with `a₄` of degree
4, and of `b·L6` is `b₂·L6` with `b₂` of degree 2):

    L8 = a₄·L4 + b₂·L6 .

Non-membership is therefore the finite-dimensional ℚ-linear statement
`L8 ∉ R₄·L4 + R₂·L6`, which is exactly what the exact Gröbner run
(code/out/membership.captured.txt, m1) verified computationally: the reduction
of L8 by <L4, L6> leaves a nonzero remainder of 16 monomials, all of degree 6.

WHY SORRY. Proving this in Lean needs the homogeneous-degree decomposition of
`MvPolynomial`: the graded pieces R_d, the projection of a product onto R_d,
and the identity `(a·L4)₆ = a₄·L4`. None of that machinery is in this file or
in the imports above, and it is not needed by Route A. The `sorry` is the
shape of the missing lemma, not a claim.

STATUS of the two routes: Route A closes the non-membership theorem by a
second, non-proportional evaluation point (the three evaluation hypotheses are
established by exact computation in the capture, not by the kernel). Route B
reduces the same statement to linear algebra in degree 6 and is an open gap.

The statement the graded route is really after, with the gap explicit:

if L8 ∈ ⟨L4, L6⟩ then L8 is a combination of homogeneous generators at
degrees 4 and 2 — the linear-algebraic certificate of membership that, once
the functional separating R₄·L4 + R₂·L6 from L8 is exhibited (the evaluation
at certPt2 restricted to degree 6), gives the non-membership by the same
argument as Route A.

Gap:

```gap
id: graded-reformulation-L8
lemma: graded_membership_shape
  (V1 V2 V3 : LyapunovRing)
  (hL4 : IsHomogeneous V1 2) (hL6 : IsHomogeneous V2 4) (hL8 : IsHomogeneous V3 6)
  (hmem : V3 ∈ Ideal.span ({V1, V2} : Set LyapunovRing)) :
  ∃ a4 b2 : LyapunovRing, IsHomogeneous a4 4 ∧ IsHomogeneous b2 2 ∧
    V3 = a4 * V1 + b2 * V2
status: sorry
next: (1) define the degree-d homogeneous component of an MvPolynomial
      (projection onto support elements of total degree d); (2) prove
      (a·L4)₆ = a₄·L4 for a₄ the degree-4 component of a (multiplicativity
      of the degree filtration); (3) instantiate with a₄, b₂ and L8, L4, L6.
      Step (3) is one intro + obtain; steps (1)-(2) are the missing machinery.
```
-/
theorem graded_membership_shape
    (V1 V2 V3 : LyapunovRing)
    (hL4 : IsHomogeneous V1 2) (hL6 : IsHomogeneous V2 4) (hL8 : IsHomogeneous V3 6)
    (hmem : V3 ∈ Ideal.span ({V1, V2} : Set LyapunovRing)) :
    ∃ a4 b2 : LyapunovRing, IsHomogeneous a4 4 ∧ IsHomogeneous b2 2 ∧
      V3 = a4 * V1 + b2 * V2 := by
  sorry

#print axioms graded_membership_shape

end BautinAlt

end