import Mathlib

-- Check for transversality and jet bundle related concepts
#check ContMDiffOn
#check ContMDiff
#check PartialHomeomorph
#check ModelWithCorners
#check TangentBundle
#check ContMDiffMap
#check VectorBundle
#check FiberBundle
#check Diffeomorph
#check QuadraticForm
#check QuadraticMap
#check ContMDiffOn.transversality
#check ContMDiffOn.transverse
#check ContMDiffOn.jet
#check ContMDiffOn.jetBundle
#check ContMDiffOn.smoothMap
#check ContMDiffOn.pullback
#check ContMDiffOn.immersion
#check ContMDiffOn.submersion
#check ContMDiffOn.embedding
#check ContMDiffOn.localDiffeomorph
#check ContMDiffOn.smoothManifold
#check ContMDiffOn.chartedSpaceWithCorners
#check ContMDiffOn.hasGroupoid
#check ContMDiffOn.pseudogroup
#check ContMDiffOn.quadraticForm
#check ContMDiffOn.quadraticMap
#check ContMDiffOn.quadraticEquiv
#check ContMDiffOn.quadraticForm.associated
#check ContMDiffOn.quadraticForm.polarBilin
#check ContMDiffOn.quadraticForm.nonDegenerate
#check ContMDiffOn.quadraticForm.isDefinite
#check ContMDiffOn.quadraticForm.signature
#check ContMDiffOn.quadraticForm.anisotropic
#check ContMDiffOn.quadraticForm.isotropic
#check ContMDiffOn.quadraticForm.isRefl
#check ContMDiffOn.quadraticForm.isSymm
#check ContMDiffOn.quadraticForm.isAlt
#check ContMDiffOn.quadraticForm.zero
#check ContMDiffOn.quadraticForm.smul
#check ContMDiffOn.quadraticForm.add
#check ContMDiffOn.quadraticForm.neg
#check ContMDiffOn.quadraticForm.mul
#check ContMDiffOn.quadraticForm.pow
#check ContMDiffOn.quadraticForm.det
#check ContMDiffOn.quadraticForm.trace
#check ContMDiffOn.quadraticForm.charpoly
#check ContMDiffOn.quadraticForm.minpoly
#check ContMDiffOn.quadraticForm.eigenvalues
#check ContMDiffOn.quadraticForm.eigenvectors
#check ContMDiffOn.quadraticForm.spectral
#check ContMDiffOn.quadraticForm.diagonalization
#check ContMDiffOn.quadraticForm.classification
#check ContMDiffOn.quadraticForm.witt
#check ContMDiffOn.quadraticForm.wittIndex
#check ContMDiffOn.quadraticForm.anisotropy
#check ContMDiffOn.quadraticForm.isRegular
#check ContMDiffOn.quadraticForm.isSplit
#check ContMDiffOn.quadraticForm.isHypers
#check ContMDiffOn.quadraticForm.isElliptic
#check ContMDiffOn.quadraticForm.isParabolic
#check ContMDiffOn.quadraticForm.isDegenerate
#check ContMDiffOn.quadraticForm.isNondegenerate
#check ContMDiffOn.quadraticForm.isUniversal
#check ContMDiffOn.quadraticForm.isRound
#check ContMDiffOn.quadraticForm.isRegular
