import Mathlib.Data.Fintype.Card
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Card
import Mathlib.Data.Real.Basic
import Mathlib.Algebra.BigOperators.Group.Finset.Basic
import Mathlib.Topology.Defs.Filter
import Mathlib.Topology.MetricSpace.Basic

/-!
# R-center-ideal zero-division — conditional lemma

The abstract shape of the run's G-remainder step (blueprint
`h16-2-h14-3-finite-cyclicity/G-remainder`, live record
`research/backward/h16-2-h14-3-finite-cyclicity.md`): the displacement `V` on
a compact parameter neighbourhood `K` of the H¹⁴₃ hemicycle and a fixed collar
admits the Bautin-trick form

    V p z = Σᵢ aᵢ p · mᵢ z · (1 + hᵢ p z)

with `mᵢ` a finite family of generalized monomials, `aᵢ` lying in the center
ideal (finitely generated by L4, L6, L8 in the concrete H¹⁴₃ chart — see
`Lib/Bautin.lean`, `Lib/BautinRecurrence.lean`), and `hᵢ` a uniformly
controlled remainder.  From this form, the number of zeros of `V` on the
collar is bounded by a finite `N`, uniformly over the whole box `K × collar`,
via Hadamard divisibility / root uniqueness / the derivation–division (Rolle)
procedure on the two Dulac map types.

WHAT IS PROVED HERE: the implication.  Given the admissible form (finite
generalized-monomial family, center-ideal coefficient membership, uniform
remainder control, compactness) AND the analytic zero-division theorem stated
as the explicit hypothesis `zero_division`, the displacement has a finite
uniform zero bound.  The proof is the specialisation of `zero_division` to the
named displacement — kernel-checked, axioms exactly `[propext,
Classical.choice, Quot.sound]`, no `sorry`, no cited axiom.

WHAT IS NOT PROVED, AND MUST NOT BE READ AS PROVED:
* the analytic `zero_division` theorem itself is an OPEN hypothesis (the
  run's G-remainder gap).  It is deliberately NOT an `axiom` under
  `namespace Cited`: the held literature (RR 2015 Thm 5.8-style derivation–
  division on generalized monomials) does not cover the transseries class with
  iterated logarithms/exponentials that the non-hyperbolic H¹⁴₃ vertices
  require, and the run's refuted short-Dulac approach
  (`approach-fewnomial-short-dulac-refuted`) rules out the finite
  power-times-log restriction;
* nothing here states or implies H(2) < ∞, finite cyclicity of the graphic,
  or any bound on limit cycles.  This file is the conditional interface for
  one algebraic-analytic step of the H¹⁴₃ route.
-/
namespace RCenterIdealZeroDivision

abbrev Parameter := ℝ × ℝ
abbrev Section := ℝ

/-- A finite family of generalized monomials on the section.  Finiteness is
by the `Fin m` index; the Dulac/transseries semantics of the monomials are
supplied by the construction this statement abstracts over. -/
structure GeneralizedMonomialFamily (m : ℕ) where
  generalized_monomial : Fin m → Section → ℝ

/-- Pointwise membership of a coefficient function in the ideal generated by
`generator` on `K`: for every parameter `p ∈ K` the value `a p` is a finite
linear combination of the generator values at `p`.  This is the abstract
"coefficient ideal" (in the H¹⁴₃ chart: the center ideal generated by
L4, L6, L8). -/
def InCoefficientIdeal (K : Set Parameter) (g : Finset ι)
    (generator : ι → Parameter → ℝ) (a : Parameter → ℝ) : Prop :=
  ∃ coeff : ι → Parameter → ℝ,
    ∀ p ∈ K, a p = ∑ i ∈ g, coeff i p * generator i p

/-- The zero set of the displacement on the compact parameter box and collar. -/
def ZeroSet (K : Set Parameter) (collar : Set Section)
    (V : Parameter → Section → ℝ) : Set (Parameter × Section) :=
  {z | z.1 ∈ K ∧ z.2 ∈ collar ∧ V z.1 z.2 = 0}

/-- The admissible Bautin-trick form: the displacement is a finite sum of
center-ideal coefficients times generalized monomials times uniformly
controlled factors `(1 + hᵢ)`.  The four conjuncts are the named hypotheses
of the task: finite generalized-monomial family, coefficient ideal, uniform
remainder, and the remainder vanishing at the section origin (the `o(1)`
semantics). -/
def Admissible (K : Set Parameter) (collar : Set Section) (m : ℕ)
    (family : GeneralizedMonomialFamily m) (g : Finset ι)
    (generator : ι → Parameter → ℝ) (remainder_bound : Parameter → Section → ℝ)
    (V : Parameter → Section → ℝ) (a : Fin m → Parameter → ℝ)
    (h : Fin m → Parameter → Section → ℝ) : Prop :=
  (∀ p ∈ K, ∀ z ∈ collar,
    V p z = ∑ i : Fin m, a i p * family.generalized_monomial i z * (1 + h i p z)) ∧
  (∀ i : Fin m, InCoefficientIdeal K g generator (a i)) ∧
  (∀ p ∈ K, ∀ i : Fin m, h i p 0 = 0) ∧
  (∃ C : ℝ, 0 ≤ C ∧
    ∀ p ∈ K, ∀ z ∈ collar, ∀ i : Fin m, |h i p z| ≤ C * |remainder_bound p z|)

/-- **R-center-ideal zero-division, conditional.**

The precise conditional lemma: compact parameter neighbourhood `K` and collar
(finite generalized-monomial family, coefficient ideal, uniform remainder,
and the analytic `zero_division` theorem as explicit hypotheses) imply a
finite zero bound for the displacement, uniform over the whole box.

`zero_division` is the load-bearing analytic implication — Hadamard
divisibility / root uniqueness / derivation–division on the generalized
monomial class — and is the run's open G-remainder gap, supplied here as a
binder hypothesis rather than a `Cited` axiom or a `sorry`.  The proof is
exactly the specialisation of that hypothesis to `(V, a, h)`; the kernel
checks the implication and checks nothing about the hypothesis, which is the
honest status of the conditional result. -/
theorem r_center_ideal_zero_division
    {ι : Type} [Fintype ι]
    (K : Set Parameter) (collar : Set Section) (V : Parameter → Section → ℝ)
    (m : ℕ) (family : GeneralizedMonomialFamily m)
    (g : Finset ι) (generator : ι → Parameter → ℝ)
    (a : Fin m → Parameter → ℝ) (h : Fin m → Parameter → Section → ℝ)
    (remainder_bound : Parameter → Section → ℝ)
    (_hK : IsCompact K)
    (_hcollar : IsCompact collar)
    (hV : Admissible K collar m family g generator remainder_bound V a h)
    (zero_division : ∀ (V' : Parameter → Section → ℝ)
        (a' : Fin m → Parameter → ℝ) (h' : Fin m → Parameter → Section → ℝ),
      Admissible K collar m family g generator remainder_bound V' a' h' →
      ∃ N : ℕ, (ZeroSet K collar V').Finite ∧ (ZeroSet K collar V').ncard ≤ N) :
    ∃ N : ℕ, (ZeroSet K collar V).Finite ∧ (ZeroSet K collar V).ncard ≤ N := by
  exact zero_division V a h hV

#print axioms r_center_ideal_zero_division

/- gap
id: r-center-ideal-zero-division-analytic-theorem
lemma: ∀ (K collar m family g generator remainder_bound) (V a h),
  IsCompact K → IsCompact collar →
  Admissible K collar m family g generator remainder_bound V a h →
  ∃ N : ℕ, (ZeroSet K collar V).Finite ∧ (ZeroSet K collar V).ncard ≤ N
status: sorry (stated as the binder hypothesis `zero_division` of
  `r_center_ideal_zero_division`; the main theorem is closed by specialising
  it, so the file has no `sorry` — the unproved content lives in the
  hypothesis)
next: prove `zero_division` on the concrete H¹⁴₃ generalized-monomial class
  by (1) writing the two second-type Dulac endpoint expansions and the regular
  transition maps symbolically (sympy, exact, over the five-parameter family)
  so the monomials `mᵢ` and remainders `hᵢ` are explicit; (2) invoking the
  derivation–division (Rolle) zero bound on that class — the literature
  reference is RR 2015 Thm 5.8-style, which does NOT cover the iterated-log
  transseries needed here, so this is a genuine open step; (3) discharging
  `huniform_remainder` by the uniform remainder estimates.  Until (2) is a
  Cited axiom or a proof, nothing resting on this node may be marked
  `formalised`; the conditional statement is the deliverable.
-/

end RCenterIdealZeroDivision
