<!-- source: https://arxiv.org/pdf/2203.01901 | converted from PDF -->

arXiv:2203.01901v1  [math.MG]  3 Mar 2022
Cubic sublattices

M´arton Horv´ath

Department of Geometry, Institute of Mathematics,
Budapest University of Technology and Economics, Hungary
horvathm@math.bme.hu

Abstract

A sublattice of the three-dimensional integer lattice Z3 is called cubic sublattice if there exists a basis
of the sublattice whose elements are pairwise orthogonal and of equal lengths. We show that for an integer
vector v ∈ Z3 whose squared length is divisible by d2, there exists a cubic sublattice containing v with
edge length d. This improves one of the main result of a paper [3] of Goswick et al., where similar theorem
was proved by using the decomposition theory of Hurwitz integral quaternions. We give an elementary
proof heavily using cross product. This method allows us to characterize the cubic sublattices.

1 Introduction

Constructing lattice squares in the integer lattice Z
2 is easy as we can take a vector and its image under
a 90 degree rotation. The analogous problem in dimension three is to ﬁnd lattice cubes in Z
3. Although
there are axis-parallel lattice cubes, still many other constructions exist, which are much more complicated
to construct as there is no canonical rotation in dimension three.
One early result on lattice cubes is due to A. S´ark¨ozy [7], who described some constructions of lattice
cubes and determined the number of certain lattice cubes in 1961. This topic is still researched, E. J. Ionascu
studied lattice cubes in dimensions 2, 3, 4 and determined their Ehrhart polynomial in his recently published
paper [4].
If the edge length of a lattice cube is d, then its volume d
3 is the determinant of the edge vectors, so it
is an integer, while the squared edge length d
2 is also an integer. This means that the edge length d is an
integer. The following statement is an easy consequence of the description of the Pythagorean quadruples
(see [1] or [8]). If the length of a vector v ∈ Z
3 is an integer, then v can be extended to a lattice cube. An
algorithmic proof is found in [6]. Similar questions are discussed in dimension four using Hurwitz integral
quaternions by E. W. Kiss and P. Kutas [5].
A lattice cube can be easily extended to a cubic sublattice, which is a sublattice having such basis whose
elements are pairwise orthogonal and of equal lengths. In this situation, it is naturally to ask which cubic
sublattices contain a given vector v ∈ Z
3 not necessarily as a basis vector. If the edge length of the cubic
sublattice is d, then d
2 must divide the squared length of v. Our goal is to show that this condition is
suﬃcient in the following sense.

Theorem 1. For a vector v ∈ Z
3 whose squared length is divisible by d
2 for an integer d, there exists a cubic
sublattice containing v with edge length d. If v is primitive, then this cubic sublattice is unique.

For example, the squared length of the vector v = (5, 5, 2) is 54, which is divisible by 9, so there exists a
cubic sublattice containing v with edge length 3, see Figure 1.

2020 Mathematics Subject Classiﬁcation: Primary 52C07, Secondary 11H06.
Keywords and phrases: cubic lattice, integer vector, three-dimensional lattice.

1
 y

z
 x
 v

Figure 1: The vector v = (5, 5, 2) is contained in the cubic sublattice with edge length 3 generated by vectors
(−1, 2, 2), (2, −1, 2), (2, 2, −1). The ﬁgure shows the domain [−1, 6] × [−1, 6] × [−2, 4].

There might be several suitable cubic sublattices if v is not primitive. For instance, the vector v = (5, 0, 0)
is contained in the cubic sublattices with edge length d = 5 generated by bases {(5, 0, 0), (0, 5, 0), (0, 0, 5)}
and {(5, 0, 0), (0, 3, 4), (0, 4, −3)}.
For the uniqueness, it is enough to assume that the greatest positive divisor k of v and d are coprime.
Indeed, we show that the primitive vector u = v/k is also contained in the cubic sublattice Γ given by the
theorem for v when d and k are coprime. In the group Z
3/Γ, the order of uΓ divides k and the order d
3 of
the group by Lagrange’s theorem, hence the order of uΓ is 1.
For the greatest possible value of d, i.e., in the case when ∥v∥2/d
2 is square-free, Theorem 1 was proved in
[3] by L. M. Goswick, E. W. Kiss, G. Moussong and N. Sim´anyi using the decomposition theory of Hurwitz
integral quaternions. Our proof builds solely on the structure of the three-dimensional Euclidean space and
some basic facts about lattice geometry.
Finally, we give a number-theoretic corollary by considering the squared length of the vector v. When a
number d
2m (where d and m are integers) is a sum of three squares, then m is also a sum of three squares.
This is not surprising because Legendre’s three-square theorem states that a natural number is a sum of three
squares if and only if it is not of the form 4n(8k + 7). As a primitive vector remains primitive vector in the
cubic sublattice, we can formulate a similar corollary: If an integer d
2m is a sum of three coprime squares,
then m is also a sum of three coprime squares. We will discuss the converse of this claim after Theorem 3 at
the end of Section 4.
In Section 2, we introduce some deﬁnitions and propositions from lattice geometry. Section 3 is devoted
to the proof of Theorem 1. Then we characterize the cubic sublattices of Z
3 and we prove a kind of reverse
theorem in Section 4. Finally, we investigate cubic sublattices as a partial ordered set in Section 5.

2

2 Preliminaries

In this section, we summarize some basic deﬁnitions and statements without proof. We refer to [2] for more
details on lattice geometry. After that we prove some easy propositions which will be used later.
Let Λ be an n-dimensional lattice in a real vector space. We say that a subgroup K < Λ is a sublattice
if K is also an n-dimensional lattice. This is equivalent to the ﬁniteness of the index of K in Λ. If some
linearly independent vectors in Λ form a basis in the intersection of Λ and the linear subspace generated by
them, then these vectors can be extended to a basis of Λ. The parallelepiped generated by the basis of the
lattice is called fundamental parallelepiped. When a scalar product or just a volume form is given on the
vector space, the volume of the fundamental parallelepiped does not depend on the choice of the basis of the
lattice. For a sublattice K ⊆ Λ, the ratio of the volumes of the fundamental parallelepipeds is equal to the
index of K in Λ as a subgroup.
We say that a vector v ∈ Λ is divisible by a positive integer k if there exists a vector u ∈ Λ such that
v = ku. A vector v ∈ Λ is called primitive if there is not any positive integer k ̸= 1 which divides v. For
a non-zero vector v ∈ Λ, there exists a unique primitive vector u and a unique positive integer k such that
v = ku. In this case, we say that k is the greatest divisor of v. The vectors that are divisible by a positive
integer k form a sublattice in Λ, it will be denoted by kΛ. The index of kΛ in Λ is kn.
Fixing a basis {e1, . . . , en} of Λ, we can identify Λ with Z
n by using the coordinates (v1, . . . , vn) of a
vector v ∈ Λ with respect to this basis. A vector is divisible by k if and only if its coordinates so are. A
vector is primitive if and only if its coordinates are coprime. The standard embedding Z
n ⊆ Rn and the
Euclidean vector space structure of Rn deﬁne the dot product on Λ. In particular, the perpendicularity of
two vectors of Λ and the length ∥v∥ of a vector v ∈ Λ are deﬁned. In this case, the volume of the fundamental
parallelepiped is the determinant of the basis vectors.
From now, we consider the case n = 3. The advantage of this dimension is the applicability of the cross
product. We say that a sublattice Γ of the standard lattice Z
3 is a cubic sublattice if there exists a basis of
Γ whose elements are pairwise orthogonal and of equal lengths. Such basis is called cubic basis, and their
common length d is the edge length. When we have a cubic sublattice Γ ⊂ Z
3, we can identify Γ with Z
3, so
we can measure the vectors of Γ with respect to this identifying.
For a non-zero vector v ∈ Z
3, the set of the orthogonal vectors to v will be denoted by v⊥.

Proposition 1. For a non-zero vector v = (v1, v2, v3) ∈ Z
3, the set v⊥ is a two-dimensional lattice.

Proof. Obviously, v⊥ is a discrete subgroup. Its dimension is at most 2, we show that it is exactly 2. We can
assume that v3 ̸= 0, so none of the linear combinations of e1, e2 is parallel to v. In this case, the linearity of
the cross product yields that the vectors e1 × v, e2 × v ∈ v⊥ are linearly independent.

Proposition 2. For a primitive vector v ∈ Z
3, the area of the fundamental parallelogram in v⊥ is equal to
the length of v.

Proof. The area of the fundamental parallelogram equals the length of the cross product ˜v of the generating
vectors. As v is primitive, ˜v is a multiple of v. Every pair of the vectors ei × v (i = 1, 2, 3) generates a
sublattice of v⊥. The cross product of the generators is

(ei × v) × (ej × v) = (
v · (ei × ej)
) v = ±vkv,

where i, j, k ∈ {1, 2, 3} are distinct indices. These vectors are multiples of ˜v. As v is primitive, the coeﬃcients
v1, v2, v3 are coprime, hence ˜v = ±v.

Fixing a primitive vector v, let the vectors a, b ∈ Z
3 be equivalent if their diﬀerence is a multiple of v.
Then the cross product with v is a well-deﬁned map Φv from the equivalence classes to v⊥.

Proposition 3. The map Φv is a bijection.

Proof. If the cross products with v are equal for two vectors of Z
3, then their diﬀerence is parallel to v. This
means that Φv is injective.
For the surjectivity, consider a vector ku ∈ v⊥, where u is primitive and k is an integer. The vector v is
primitive in u⊥, so there exists a vector w such that {v, w} is a basis of u⊥. Then the cross product w × v
is ±u, so ±kw × v = ku, hence Φv is surjective.
 3

3 The proof of Theorem 1

It is enough to prove the theorem for primitive vector v. Indeed, if v = ku for a primitive vector u ∈ Z
3,
and d
2 divides the squared length ∥v∥2 = k2∥u∥2, then there exists a decomposition d = d1d2 such that d1
divides k and d
2
2 divides ∥u∥2. Applying the theorem for d2 and u, we get a cubic sublattice Γ. Then the
cubic sublattice d1Γ has edge length d1d2 = d and contains d1u, therefore also v.
First we prove the uniqueness part of the theorem in case v is primitive. Suppose that we have a cubic
sublattice Γ containing v with edge length d. The ﬁrst lemma is the key observation.

Lemma 1. If a, b ∈ Γ, then a × b is divisible by d, and a × b/d ∈ Γ.

Proof. Computing the cross product of a and b with respect to the Euclidean structure of Γ ∼= Z
3 ⊂ R3, we
get a × b/d, which implies the statement.

Lemma 1 yields that a × v is divisible by d for a ∈ Γ, so consider the following subset of v⊥

M (v, d) = {a ∈ v⊥ | a × v is divisible by d}.

We have that M (v, d) contains the intersection v⊥ ∩ Γ. Later we will see that these sets are coincide. By
the linearity of the cross product, M (v, d) is a subgroup. The next lemma shows that it is a sublattice.

Lemma 2. The index of M (v, d) in v⊥ is d.

Proof. Let i denote the index of M (v, d) in v⊥. Firstly we prove that i is divisible by d. As the vector
v = (v1, v2, v3) is primitive, there exist integers t1, t2, t3 such that t1v1 + t2v2 + t3v3 = 1. Consider the vector
t = (t1, t2, t3), and put u = t × v ∈ v⊥. Then

u × v = (t × v) × v = (t · v)v − (v · v)t = v − ℓ2t = (
v1 − ℓ2t1, v2 − ℓ2t2, v3 − ℓ2t3) .

This vector is not divisible by any non-unit divisor of d, otherwise such a divisor would divide ℓ2 and v1, v2, v3,
which would contradict the primitiveness of v. Thus, the vectors u × v, 2u × v, . . . , (d − 1)u × v are not
divisible by d, so the vectors u, 2u, . . . , (d − 1)u are not contained in M (v, d). The vector du belongs to
M (v, d) by deﬁnition. In the group ⟨u⟩ generated by u ∈ v⊥, the subgroup ⟨u⟩ ∩ M (v, d) has index d, hence
i is a multiple of d by Noether’s isomorphism theorem.
Now we prove that i divides d. Consider the vectors

r
1 = de1 × v = (0, −dv3, dv2),

s1 = (r
1 × v)/d = (e1 × v) × v = (
−v2
2 − v2
3, v1v2, v1v3) .

We have that r
1 ∈ M (v, d) and r
1 ⊥ s1. As r
1 is perpendicular to v, we have

s1 × v = 1
d (r
1 × v) × v = − ℓ2

d r
1,

which means that s1 ∈ M (v, d). The area of the rectangle spanned by r
1 and s1 is ∥r
1∥2ℓ/d = dℓ(v2
2 +v2
3). By
Proposition 2, the area of the fundamental parallelogram in v⊥ is ℓ. The index of the sublattice generated by
r
1 and s1 in v⊥ is the quotient of the areas of the fundamental parallelograms, which is equal to d(v2
2 + v2
3).
This shows that i divides d(v2
2 + v2
3). We get similarly that i also divides d(v2
1 + v2
3) and d(v2
1 + v2
2), which
yields that i divides the greatest common divisor

gcd (
d(v2
2 + v2
3), d(v2
1 + v2
3), d(v2
1 + v2
2)
) = d gcd (
v2
2 + v2
3, v2
1 + v2
3, v2
1 + v2
2)

= d gcd (
v2
2 + v2
3, v2
1 + v2
3, v2
1 + v2
2, v2
2 − v2
3, v2
1 − v2
3, v2
1 − v2
2)

= d gcd (
2v2
1, 2v2
2, 2v2
3, v2
2 + v2
3, v2
1 + v2
3, v2
1 + v2
2) .

Using gcd(v1, v2, v3) = 1, we obtain gcd(d(v2
2 + v2
3), d(v2
1 + v2
3), d(v2
1 + v2
2)) = d if v1, v2, v3 are not all odd. This
implies the statement in this case. If v1, v2, v3 are all odd, then gcd(d(v2
2 + v2
3), d(v2
1 + v2
3), d(v2
1 + v2
2)) = 2d,
so we have that i divides 2d. In this case, ℓ2 = v2
1 + v2
2 + v2
3 is odd, so is d. The sublattice dv⊥ is contained
in M (v, d), and its index is d
2. Therefore i divides gcd(2d, d
2) = d.

4

Lemma 1 implies for a vector a ∈ Γ that a × v is divisible by d and a × v/d ∈ Γ. Since a × v/d ∈ v⊥ as
well, we obtain a × v/d ∈ M (v, d). This motivates the deﬁnition of the set

Γ(v, d) = {a ∈ Z
3 | a × v/d ∈ M (v, d)}

= {a ∈ Z
3 | a × v is divisible by d, and (a × v) × v is divisible by d
2}.

We have Γ ⊆ Γ(v, d) and v ∈ Γ(v, d). As the cross product is linear, Γ(v, d) is a subgroup. The following
lemma shows that Γ(v, d) is a sublattice.

Lemma 3. The index of Γ(v, d) in Z
3 is d
3.

Proof. The sublattice Γ(v, d) contains such vectors a ∈ Z
3 that a × v ∈ dM (v, d). By Proposition 3, the
index of Γ(v, d) in Z
3 is equal to the index of dM (v, d) in v⊥. As M (v, d) has index d in v⊥, the index of
the sublattice dM (v, d) in v⊥ is d
3.

Since the index of Γ is d
3 as well, if there exists an appropriate cubic sublattice, then it is Γ(v, d), which
proves the uniqueness part of Theorem 1.

Now we prove that Γ(v, d) is indeed a cubic sublattice. The ﬁrst step is to show that the dot products of
the elements of Γ(v, d) are divisible by d
2, but we have to start with weaker lemmas.

Lemma 4. For a vector a ∈ Γ(v, d), the dot product a · v is an integer and it is divisible by d
2.

Proof. For a ∈ Γ(v, d), we have that d
2 divides

(a × v) × v = (a · v)v − (v · v)a,

which means that a · v
d2 v − v · v
d2 a ∈ Z
3.

Since v · v is divisible by d
2, we earn a · v
d2 v ∈ Z
3. This gives the statement as v is primitive.

Lemma 5. For vectors a, b ∈ Γ(v, d), the vector a × b
d is contained in Γ(v, d).

Proof. Our goal is to prove that M (v, d) contains the vector

a×b
d × v
d = a · v
d2 b − b · v
d2 a,

where the coeﬃcients a · v
d2 and b · v
d2 are integers by Lemma 4. The above vector is in M (v, d) if

a · v
d2 b × v
d − b · v
d2 a × v
d ∈ Z
3,

which is satisﬁed, because b × v
d , a × v
d ∈ Z
3 as a, b ∈ Γ(v, d).

Lemma 6. For vectors a, b ∈ Γ(v, d), the dot product a · b is divisible by d
2.

Proof. We have a × v
d ∈ Γ(v, d) by Lemma 5. Applying Lemma 5 again, we get that the vector

(a × v) × b = (a · b)v − (v · b)a

is divisible by d
2. Lemma 4 implies that d
2 divides the coeﬃcient v · b. Therefore the vector (a · b)v is also
divisible by d
2, which gives the statement.
 5

The second step is to ﬁnd the cubic basis in Γ(v, d).

Lemma 7. There exists a vector a ∈ Γ(v, d) of length d.

Proof. Suppose the contrary. Lemma 6 implies that the squared length of every vector of Γ(v, d) is divisible
by d
2. This and the indirect assumption yield that the length of every non-zero vector of Γ(v, d) is at least√
2d. Thus, the balls centered at the elements of Γ(v, d) with radius √
2d/2 are disjoint. The parts of the
intersection of a fundamental parallelepiped and these balls form an entire ball. Its volume is

4π
3
 ( √
2d
2
 )3
 > √
2d
3,

while the volume of the fundamental parallelepiped is d
3. This is a contradiction.

Fix a vector a ∈ Γ(v, d) of length d. By Lemma 6, for a vector b ∈ Γ(v, d), the dot product a · b is
divisible by d
2, so the length of the projection of b to a is a multiple of d. Therefore the elements of Γ(v, d)
lie in a
⊥ and its translates by the multiples of a. Consider the sublattice Λ = a
⊥ ∩ Γ(v, d). The area of the
fundamental parallelogram in Λ is d
2 as we can get the basis of the fundamental parallelepiped of Γ(v, d) by
adding a to the basis of the fundamental parallelogram of Λ.

Lemma 8. There exists a vector b ∈ Λ of length d.

Proof. We prove by contradiction in a way similar to the proof of Lemma 7. We suppose that the length of
every non-zero vector in Λ is at least √
2d. In this case, the disks around the elements of Λ with radius √
2d/2
in the plane perpendicular to a are disjoint. The area of the intersection of a fundamental parallelogram and
these disks is ( √
2d
2
 )2
 π = π
2 d
2 > d
2,

which is the area of the fundamental parallelogram, this is a contradiction.

Fix a vector b ∈ Λ of length d. The vector c = a×b
d is in Γ(v, d) by Lemma 5. Since the lengths of a and
b are d and they are perpendicular, the length of c is also d. The vectors a, b, c are pairwise perpendicular,
so the volume of the parallelepiped generated by them is d
3. As the index of Γ(v, d) in Z
3 is also d
3, the
vectors a, b, c generate the sublattice Γ(v, d). This means that Γ(v, d) is indeed a cubic sublattice with edge
length d.

4 Characterization of cubic sublattices

Although the following two lemmas are well-known, we prove them for the sake of completeness.

Lemma 9. Let K be a sublattice of a two-dimensional lattice Λ and let k be the greatest common divisor of
the vectors of K. Then there exists a vector in K whose greatest divisor is k.

Proof. Let the generators of K be v1 = k1u1 and v2 = k2u2, where u1, u2 are primitive, and k1, k2 are
positive integers. We can assume that k = gcd(k1, k2) is equal to 1. Unfortunately, the vector v1 + v2 is
not necessarily primitive, see Figure 2, so we have to be more tricky. As u1 is primitive, there exists such a
vector w that u1 and w generate Λ. We can write u2 = au1 + bw, where a, b are coprime integers. Let c be
the product of those prime numbers which divide b, but do not divide k1k2 (set c = 1 if there is not any such
prime number). We show that the vector v = cv1 + v2 ∈ K is a primitive vector. Suppose the contrary, i.e.,
there exists a prime number p which divides

v = cv1 + v2 = ck1u1 + k2(au1 + bw) = (ck1 + ak2)u1 + bk2w.

Since u1, w are the generators of Λ, p divides ck1 + ak2 and bk2. As p is prime, p divides b or k2. If p divides
k2, then p also divides ck1, which contradicts the deﬁnition of c or gcd(k1, k2) = 1. If p does not divide k2,
then p divides b. By the deﬁnition of c, p divides ck1, hence p divides ak2 and consequently also a. Thus, p
divides u2 = au1 + bw, which is a contradiction.
 6

v2

u2
 cv1v1u1

w
 v1 +v2 v

Figure 2: The vector v1 + v2 is divisible by 2.

The next lemma is the three-dimensional version of Lemma 9.

Lemma 10. If the greatest common divisor of the vectors of a sublattice K of a three-dimensional lattice Λ
is k, then K contains a vector whose greatest divisor is k.

Proof. Denote the generators of K by v1, v2, v3 and its greatest divisors by k1, k2, k3, respectively. We have
that k = gcd(k1, k2, k3). Let M be the sublattice generated by v1 and v2. By Lemma 9, there is a vector v
in M whose greatest divisor is gcd(k1, k2). If we apply Lemma 9 again to the sublattice generated by v and
v3, we get a vector in K, whose greatest divisor is gcd(gcd(k1, k2), k3) = k.

We remark that similar statement holds for arbitrary dimensional lattices, and one can prove it by
induction on the dimension.
Now we can characterize the cubic sublattices of Z
3. We show that every cubic sublattice can be obtained
from our construction.

Theorem 2. For an arbitrary cubic sublattice Γ ⊆ Z
3, there exist unique positive integers k and d such that
Γ = kΓ(v, d) for a primitive vector v ∈ Z
3.

Proof. We have that k is the greatest common divisor of the vectors of Γ and d is the quotient of the edge
length of Γ and k. Consider the cubic sublattice Γ′ such that kΓ′ = Γ. By Lemma 10, there exists a primitive
vector v ∈ Γ′. Theorem 1 implies Γ′ = Γ(v, d), which gives the statement.

When a cubic sublattice is constructed from a primitive vector, this vector is also a primitive vector in
the cubic sublattice. Our next goal is to show that every primitive vector can be such a vector. It requires
two lemmas.

Lemma 11. If a cubic sublattice Γ ⊆ Z
3 has edge length d, then it contains the vectors divisible by d
2, i.e.,
the inclusion d
2Z
3 ⊆ Γ is fulﬁlled.

Proof. When Γ = Γ(v, d) for some primitive vector v, we have d
2a ∈ Γ(v, d) for any a ∈ Z
3 by the
construction. In the general case, Γ = kΓ(v, d/k) for some integer k by Theorem 2. For an arbitrary a ∈ Z
3,
we obtain d
2/k2a ∈ Γ(v, d/k), hence d
2a ∈ Γ.

The second lemma is a claim from number theory.

Lemma 12. For an odd prime number p, there exists a primitive vector in Z
3 whose squared length is
divisible by p2.

Proof. It is enough to construct a vector whose squared length is divisible by p2 and which is not divisible
by p, as we can divide it by its greatest divisor.
If −1 is a quadratic residue (when p = 4k + 1 for a positive integer k), then there exists a positive integer
x such that x
2 = ap − 1 for some integer a. As p is odd, there exists integer b such that −2b ≡ a modulo p.
Then (0, x, bp + 1) is a suitable vector.
 7

When −1 is not a quadratic residue (if p = 4k + 3), we search for x, y ∈ Zp such that x
2 + y2 = −1. If
there were no such elements, then each of the pairs

(1, p − 2), (2, p − 3), . . . , ((p − 1)/2, (p − 1)/2)

would contain only one quadratic residue (in particular the last one would not contain any), which would
contradict the well-known fact that there exist (p − 1)/2 quadratic residues modulo p. Denoting the corre-
sponding integers by x, y as well, we obtain that x
2 + y2 = ap − 1 for some integer a. As in the previous case,
we have an integer b such that −2b ≡ a modulo p, thus, the vector (x, y, bp + 1) is a suitable vector.

Lemma 12 does not hold for p = 2. Indeed, the square numbers are congruent 0 or 1 modulo 4, so if 4
divides the sum of the square of the coordinates, then all of them are even, hence the vector is divisible by 2.
If we construct a cubic sublattice in a cubic sublattice Λ instead of Z
3, we will use the notion ΓΛ(v, d)
for the cubic sublattice of Λ with edge length d which contains the primitive vector v ∈ Λ.

Theorem 3. For an arbitrary primitive vector v = (v1, v2, v3) ∈ Z
3 and an odd d, there exists a primitive
vector u ∈ Z
3 for which we can choose a cubic basis of the cubic sublattice Γ(u, d) so that the coordinates of
u are (v1, v2, v3).

Proof. First we show that it is enough to prove the theorem for odd prime number d. Applying the theorem
for a vector v = (v1, v2, v3) ∈ Z
3 and d1 yields a primitive vector u ∈ Z
3. If we apply again the theorem for
u and for d2, we get a primitive vector t ∈ Z
3. The sublattice ΓΓ(t,d2)(u, d1) is a cubic sublattice with edge
length d1d2, where the coordinates of the vector t are (v1, v2, v3). The uniqueness part of Theorem 1 implies
that this sublattice is Γ(t, d1d2). In the following, we suppose that d is an odd prime number.
As v is primitive, d does not divide at least one of its coordinates, let it be the ﬁrst coordinate v1.
Lemma 12 provides a primitive vector w = (w1, w2, w3) whose squared length is divisible by d
2. Reordering
the coordinates, we can achieve that d does not divide the ﬁrst coordinate w1. Set ˜w = (−w1, w2, w3). Now
one of the dot products v · w or v · ˜w is not divisible by d, otherwise d would divide their diﬀerence 2v1w1,
which would contradict our assumptions on v1 and w1 as d is odd. Assume that v · w is not divisible by d.
Finally, construct the cubic sublattice Γ(w, d). By Lemma 11, it contains the vector d
2v. Consider this
vector as a vector of the cubic sublattice Γ(w, d), and denote it by u. This vector is primitive since dv is not
contained in Γ(w, d) by Lemma 4. The sublattice d
2Z
3 is a cubic sublattice in Γ(w, d) with edge length d
and it contains u. Thus, the cubic sublattice ΓΓ(w,d)(u, d) is d
2Z
3. Choosing the basis (d
2e1, d
2e2, d
2e3) of
d
2Z
3, we have that the coordinates of u are (v1, v2, v3).

Theorem 3 allows us to formulate the converse of the number-theoretic corollary mentioned in the Intro-
duction. If an integer m is a sum of three coprime squares, then for an odd d, the number d
2m is also a
sum of three coprime squares. The assumption on the oddness of d is necessary, as a number divisible by 4
cannot be a sum of three coprime squares by the investigation of the remainders modulo 4.

5 Cubic sublattices as partially ordered set

The inclusion gives a partial order over the cubic sublattices of Z
3. This makes the set of the cubic sublattices
to a partially ordered set. We decide whether this set is a lattice in the algebraic sense.
Similarly to the cubic sublattices, we can investigate the square sublattices of Z
2. A square sublattice
can be characterized by the invariance of the rotation of 90◦. Therefore the intersection and the union of
square sublattices are also square sublattices. These are the supremum and the inﬁmum of the given square
sublattices, so the partially ordered set of the square sublattices of Z
2 forms a lattice in algebraic sense.
We show that the partially ordered set of the cubic sublattices of Z
3 is not a lattice in algebraic sense.
The squared length of v = (1, 2, 2) is 9 = 32, so there exists the cubic sublattice Γ(v, 3) ≤ Z
3. We have the
inclusions 9Z
3 ≤ 3Z
3 ≤ Z
3 and 3Γ(v, 3) ≤ Γ(v, 3) ≤ Z
3, and from the last one, 3Γ(v, 3) ≤ 3Z
3, see Figure 3.
Lemma 11 gives 9Z
3 ≤ Γ(v, 3). In all of the mentioned inclusions, the (relatively) edge lengths of the cubic
sublattices are 3, so there is not any cubic sublattice between the inclusions. This means that there is no
supremum of 3Γ(v, 3) and 9Z
3. And there is no inﬁmum of Γ(v, 3) and 3Z
3.

8

3Γ(v, 3) 9Z3

Γ(v, 3) 3Z3

Z3

Figure 3: This example shows that the partially ordered set of the cubic sublattices of Z
3 does not form a
lattice in algebraic sense.

However, the partially ordered set of such cubic sublattices that contain a given primitive vector v ∈ Z
3

is a lattice in algebraic sense. If the squared length of v is kd
2, where k is square-free, then this lattice is
isomorphic to the lattice of the divisors of d.

Acknowledgment

The author is immensely grateful for G´abor Moussong, who recommended this topic and proposed to search
an elementary proof for Theorem 1.

References

[1] R. D. Carmichael. Diophantine Analysis. Mathematical Monographs. John Wiley & Sons, 1915.

[2] J. W. S. Cassels. An Introduction to the Geometry of Numbers. Classics in Mathematics. Springer-Verlag,
Berlin, 1997. Corrected reprint of the 1971 edition.

[3] L. M. Goswick, E. W. Kiss, G. Moussong, and N. Sim´anyi. Sums of squares and orthogonal integral
vectors. J. Number Theory, 132(1):37–53, 2012.

[4] E. J. Ionascu. Ehrhart polynomial for lattice squares, cubes and hypercubes. Rev. Roumaine Math. Pures
Appl., 64(1):57–80, 2019.

[5] E. W. Kiss and P. Kutas. Cubes of integral vectors in dimension four. Studia Sci. Math. Hungar.,
49(4):525–537, 2012.

[6] R. Parris. Lattice cubes. College Math. J., 42(2):118–125, 2011.

[7] A. S´ark¨ozy. On lattice cubes in the three-space. Mat. Lapok, 12:232–245, 1961. In Hungarian.

[8] R. Spira. The Diophantine equation x
2 + y2 + z2 = m2. Amer. Math. Monthly, 69(5):360–365, 1962.

9
