<!-- source: https://ar5iv.labs.arxiv.org/html/0806.3943 | converted from HTML -->

[0806.3943] Sums of squares and orthogonal integral vectors

# Sums of squares and orthogonal integral vectors Thanks: Second author supported by Hungarian Nat. Sci. Found. (OTKA) Grant No. NK72523, third author supported by Hungarian Nat. Sci. Found. (OTKA) Grant No. T047102, fourth author supported by the National Science Foundation, grants DMS-0457168 and DMS-0800538.

Lee M. Goswick, Emil W. Kiss, Gábor Moussong, Nándor Simányi Lee M. Goswick The University of Alabama at Birmingham
Department of Mathematics
1300 University Blvd., Suite 452
Birmingham, AL 35294 U.S.A. Emil W. Kiss Eötvös University
Department of Algebra and Number Theory
1117 Budapest, Pázmány Péter sétány 1/c
Hungary Gábor Moussong Eötvös University
Department of Geometry
1117 Budapest, Pázmány Péter sétány 1/c
Hungary Nándor Simányi The University of Alabama at Birmingham
Department of Mathematics
1300 University Blvd., Suite 452
Birmingham, AL 35294 U.S.A. Email address, Lee M. Goswick : [goswick@amadeus.math.uab.edu][1] Email address, Emil W. Kiss : [ewkiss@math.elte.hu][2] Email address, Gábor Moussong : [mg@math.elte.hu][3] Email address, Nándor Simányi : [simanyi@math.uab.edu][4]

###### Abstract.

Two vectors in ℤ 3 \BZ^{3} are called *twins*if they are orthogonal and have the same length. The paper describes twin pairs using cubic lattices, and counts the number of twin pairs with a given length. Integers M M with the property that each integral vector with length M \sqrt{M} has a twin are called twin-complete. They are completely characterized modulo a famous conjecture in number theory. The main tool is the decomposition theory of Hurwitz integral quaternions. Throughout the paper we made a concerted effort to keep the exposition as elementary as possible.

###### Key words and phrases:

Cubic lattice, Euler rotation matrix, Hurwitz integral quaternion

###### 1991 Mathematics Subject Classification

11R52, 52C07

## 1. Introduction and main results

An *icube*in ℤ n \BZ^{n} of dimension k k is a sequence ( v 1, …, v k) (v_{1},\ldots,v_{k}) of k k nonzero vectors in ℤ n \BZ^{n} that are pairwise orthogonal and have the same length. The subgroup generated by v 1, …, v k v_{1},\ldots,v_{k} is called the corresponding *cubic lattice*. The common *length*of the vectors v i v_{i} is denoted by ‖ v i ‖ \|{v_{i}}\|, and is called the *edge length*of the icube. By the *norm*of v i v_{i} we shall mean N ⁡ ( v i) = ‖ v i ‖ 2 \Norm(v_{i})=\|{v_{i}}\|^{2} (a similar convention is used also for Gaussian integers and quaternions). A twin pair is a 2 2 -dimensional icube in ℤ 3 \BZ^{3}.

In this paper we investigate how icubes can be *constructed, counted,*and *extended.*We shall consider the case n = 3 n=3. The main results are the following.

- •

Theorem 5.10 counts all twin pairs with a given edge length.

- •

Proposition 1.3 and Corollary 5.11 show that a twin pair can be extended to a 3 3 -dimensional icube if and only if its edge length is an integer.

- •

Theorem 1.5 and Corollary 1.6 investigate the existence and uniqueness of 3 3 -dimensional cubic lattices containing a single integral vector and the extension of single vectors to twins.

- •

Theorem 1.8 and Corollary 1.10 characterize twin-complete numbers.

- •

The above results are based on the following representation theorems:

  -

k = 1 k=1: Theorem 4.2 and Theorem 4.6;

  -

k = 2 k=2: Theorem 5.4;

  -

k = 3 k=3: Theorem 3.3 and Corollary 3.9.

In the rest of the Introduction, we put these results into context.

The problem of *construction*and *counting*for 3 3 -dimensional icubes in ℤ 3 \BZ^{3} has been solved by A. Sárközy [Sar61]. To formulate his main result, we use a construction discovered by Euler. The following well-known facts show how to obtain rotations in ℝ 3 \BR^{3}. Throughout the paper we identify v = ( v 1, v 2, v 3) ∈ ℝ 3 v=(v_{1},v_{2},v_{3})\in\BR^{3} with the pure quaternion V ⁡ ( v) = v 1 ​ i + v 2 ​ j + v 3 ​ k V(v)=v_{1}i+v_{2}j+v_{3}k.

###### Theorem 1.1 (see [CS03], Section 3).

Let ℍ ∗ = ℍ ∖ { 0 } \BH^{*}=\BH\setminus\{0\} denote the set of nonzero quaternions, and V V the space of all quaternions with zero real part. For α ∈ ℍ ∗ \alpha\in\BH^{*}, let M ⁡ ( α) M(\alpha) denote the matrix of the transformation α ⁡ ( ⋅) ​ α − 1: V → V \alpha(\,\cdot\,)\alpha^{-1}:\;V\rightarrow V expressed in the standard basis ( i, j, k i,\,j,\,k). Then there exists a surjective linear representation ρ: ℍ ∗ → SO ​ ( 3, ℝ) {\rho:\BH^{*}\rightarrow\text{\sl SO}(3,\BR)} such that

1. ( 1) (1)

ker ⁡ ( ρ) = ℝ ∗ \ker(\rho)=\BR^{*}.

2. ( 2) (2)

The matrix of ρ ⁡ ( α) \rho(\alpha) in the standard basis ( i, j, k i,\,j,\,k) is

 | M ⁡ ( α) = 1 d ​ ( m 2 + n 2 − p 2 − q 2 − 2 ​ m ​ q + 2 ​ n ​ p 2 ​ m ​ p + 2 ​ n ​ q 2 ​ m ​ q + 2 ​ n ​ p m 2 − n 2 + p 2 − q 2 − 2 ​ m ​ n + 2 ​ p ​ q − 2 ​ m ​ p + 2 ​ n ​ q 2 ​ m ​ n + 2 ​ p ​ q m 2 − n 2 − p 2 + q 2), M(\alpha)=\frac{1}{d}\begin{pmatrix}m^{2}+n^{2}-p^{2}-q^{2}&-2mq+2np&2mp+2nq\\ 2mq+2np&m^{2}-n^{2}+p^{2}-q^{2}&-2mn+2pq\\ -2mp+2nq&2mn+2pq&m^{2}-n^{2}-p^{2}+q^{2}\end{pmatrix}\,, |  |

where α = m + n ​ i + p ​ j + q ​ k \alpha=m+ni+pj+qk and d = m 2 + n 2 + p 2 + q 2 d=m^{2}+n^{2}+p^{2}+q^{2}. We note that the restriction of the representation ρ \rho to the unit sphere S 3 S^{3} of ℍ \BH is the adjoint representation of S 3 S^{3} with the kernel { 1, − 1 } \{1,\,-1\}, being also the universal covering of the real projective space SO ​ ( 3, ℝ) \text{\sl SO}(3,\BR).

In what follows, we shall concern ourselves with the *Euler matrix*E ⁡ ( α) = d ​ M ​ ( α) E(\alpha)=dM(\alpha). We are interested in E ⁡ ( α) E(\alpha) when its entries are integers. Call such a matrix *primitive*if the greatest common divisor of its nine entries is 1 1. Similarly, an icube (or a single integral vector) is primitive if the n ​ k nk entries are relatively prime.

###### Theorem 1.2 (Sárközy, [Sar61]).

If m, n, p, q ∈ ℤ m,n,p,q\in\BZ, then E ⁡ ( m + n ​ i + p ​ j + q ​ k) E(m+ni+pj+qk) is primitive if and only if gcd ⁡ ( m, n, p, q) = 1 \gcd(m,n,p,q)=1 and d d is odd. Every primitive 3 3 -dimensional icube in ℤ 3 \BZ^{3} can be obtained from such an Euler matrix by permuting columns and changing the sign of the third column if necessary.

This theorem is analyzed in Section 3 and in Corollary 5.12. Sárközy went on to count all 3 3 -dimensional icubes in ℤ 3 \BZ^{3} with a given edge length d d.

We next look at the question of extension. Our first observation puts an obvious limitation on those vectors that can be extended to a 3 3 -dimensional icube in ℤ 3 \BZ^{3}.

###### Proposition 1.3.

Let ( v 1, …, v n) (v_{1},\ldots,v_{n}) be an n n -dimensional icube in ℤ n \BZ^{n}. If n n is odd, then its edge length is an integer.

###### Proof.

Let d d denote this length. The volume of the cube is d n d^{n}, which is an integer, since it is the determinant of the integer matrix ( v 1, …, v n) (v_{1},\ldots,v_{n}). We have that d 2 d^{2} is also an integer, since the vectors have integer components, which implies d n − 1 d^{n-1} is an integer. Therefore, d = d n / d n − 1 d=d^{n}/d^{n-1} is rational, and, moreover, an integer. ∎

This observation makes it easy to answer the following: which 1 1 -dimensional icubes (that is, which vectors in ℤ 3 \BZ^{3}) can be extended to a 3 3 -dimensional icube? It turns out that the trivial necessary condition given by Proposition 1.3 is sufficient.

###### Theorem 1.4.

A vector in ℤ 3 \BZ^{3} is contained in a 3 3 -dimensional icube if and only if its length is an integer.

###### Proof.

Let u = ( a, b, c) u=(a,b,c) be a primitive integral vector, whose length d d is an integer, so a 2 + b 2 + c 2 = d 2 a^{2}+b^{2}+c^{2}=d^{2}. We may assume that a a is odd. It has been known since at least [Car15] that in this case there exist m, n, p, q ∈ ℤ m,n,p,q\in\BZ such that u u is exactly the first column of the corresponding Euler matrix. Thus, the columns of this matrix extend u u to the desired icube.

If x x is a non-primitive vector of integer length, then it can be written uniquely as g ​ u gu, where g ∈ ℤ g\in\BZ and u ∈ ℤ 3 u\in\BZ^{3} is primitive. Then the length of u u is also an integer, so it extends to an icube ( u, v, w) (u,v,w). Therefore, ( g ​ u, g ​ v, g ​ w) (gu,gv,gw) extends x = g ​ u x=gu. ∎

Theorem 4.2 also yields Theorem 1.4, but by using quaternions (see Remark 4.3). When u u is primitive, the cubic lattice generated by any 3 3 -dimensional icube containing u u is always the same (see Theorem 1.5).

The next question is this: which 2 2 -dimensional icubes in ℤ 3 \BZ^{3} can be extended to a 3 3 -dimensional icube? Again, the necessary condition that the length be an integer is sufficient (see Corollary 5.11).

Having surveyed a few results concerning 3 3 -dimensional icubes, we now turn our attention to the 2 2 -dimensional case. From now on by an icube we shall always mean a 3 3 -dimensional icube in ℤ 3 \BZ^{3}. The theorems described below are our results. The essence of them is that we understand vectors and twin pairs by putting them into large 3 3 -dimensional cubic lattices.

###### Theorem 1.5.

Let x ∈ ℤ 3 x\in\BZ^{3} have norm n ​ m 2 nm^{2}, where n n is square-free. Then there exists an icube ( u, v, w) (u,v,w) with edge length m m such that the corresponding cubic sublattice contains x x. If x x is primitive, then this cubic lattice is unique, and is given by an Euler matrix E ⁡ ( α) E(\alpha), for a quaternion α \alpha with integer coefficients.

The existence part of this result follows from Theorem 4.2 (see Remark 4.3). The uniqueness part is proved at the end of Section 5, but it is also a consequence of Corollary 3.9 and Theorem 4.2.

If ( u, v, w) (u,v,w) is an icube and a, b ∈ ℤ a,b\in\BZ, then ( a ​ v + b ​ w, − b ​ v + a ​ w) (av+bw,-bv+aw) is a twin pair. Theorem 5.4 shows that *we get all twin pairs this way.*To count all twin pairs, the corresponding cubic lattice should be made unique. This is achieved in the same theorem by making the cubic lattice as large as possible, but not necessarily as large as in Theorem 1.5 above. The difficulty is with non-primitive vectors, because there is no trivial reduction to the primitive case. For example, 3 ​ ( 8, − 10, 9) 3(8,-10,9) and 7 ​ ( 4, 5, 2) 7(4,5,2) are twins, and this is explained by the cubic lattice ( u, v, w) = E ⁡ ( 2 ​ i + j + 4 ​ k) (u,v,w)=E(2i+j+4k), with a = 2 a=2 and b = 1 b=1. Theorem 4.6 shows how a vector in a cubic lattice can be divisible by a prime “unexpectedly”. Theorem 5.4 describes, using the language of quaternions, how large this common cubic lattice really is for a given pair of twins. As an application, we count all twin pairs with given norm in Theorem 5.10.

The problem of extending single vectors to twins is more difficult. A consequence of our counting result is that the common norm of twins is always the sum of two squares. The converse, however, is not true, as the example of ( 2, 2, 3) (2,2,3) shows: its norm is 17 = 1 2 + 4 2 17=1^{2}+4^{2}, but it does not have a twin. The case of primitive vectors is characterized by the following (the proof is at the end of Section 5)

###### Corollary 1.6.

Using the notation of Theorem 1.5 suppose that x x is primitive and x = a ​ u + b ​ v + c ​ w x=au+bv+cw.

1. ( 1) (1)

If none of a a, b b, c c is zero, then x x does not have a twin.

2. ( 2) (2)

If exactly one of a a, b b, c c is zero, then x x has exactly two twins. If, say, a = 0 a=0, then these are c ​ v − b ​ w cv-bw and its negative.

3. ( 3) (3)

If two of a a, b b, c c are zero, then x x has exactly four twins, and so is contained in a unique icube. If, say, a = b = 0 a=b=0, then c = ± 1 c=\pm 1, n = 1 n=1, and the twins of x x are ± u \pm u and ± v \pm v. This case happens exactly when the norm of x x is a square.

###### Definition 1.7.

An integer M > 0 M>0 is *twin-complete*if every vector in ℤ 3 \BZ^{3} with norm M M has a twin, and there is such a vector (that is, M M is not of the form 4 n ​ ( 8 ​ k + 7) 4^{n}(8k+7)).

###### Theorem 1.8.

A positive integer is twin-complete if and only if its square-free part is twin-complete. A positive square-free integer is twin-complete if and only if it can be written as a sum of two squares, but not as a sum of three positive squares.

We give a complete list of twin-complete numbers modulo the following conjecture.

###### Conjecture 1.9.

The complete list of those square-free numbers that can be written as a sum of two squares, but not as a sum of three positive squares is the following: { 1, 2, 5, 10, 13, 37, 58, 85, 130 } \{1,2,5,10,13,37,58,85,130\}.

###### Corollary 1.10.

The numbers m 2 m^{2}, 2 ​ m 2 2m^{2}, 5 ​ m 2 5m^{2}, 10 ​ m 2 10m^{2}, 13 ​ m 2 13m^{2}, 37 ​ m 2 37m^{2}, 58 ​ m 2 58m^{2}, 85 ​ m 2 85m^{2}, 130 ​ m 2 130m^{2} are twin-complete for every integer m > 0 m>0. If Conjecture 1.9 holds, then there are no other twin-complete numbers.∎

The proof of Theorem 1.8 is in Section 6, where many known results concerning this conjecture are reviewed. The square-free numbers in question form a subset of Euler’s numeri idonei, and therefore, at most one number can be absent from the list above. If such an integer does exist, it must exceed 2 ⋅ 10 11 2\cdot 10^{11} [Wei73], and if it is even, the Generalized Riemann Hypothesis is false [BC00].

###### Problem 1.11.

An avenue for future work is to investigate the *construction, counting, extension*of higher-dimensional icubes.

## 2. Integral quaternions

In this section we list some basic results and technical facts that we shall use in what follows. The general references about quaternions are [H19], [HW79], and [CS03]. The division ring of all quaternions (with real coefficients) is denoted by ℍ \BH. A quaternion is *pure*if its real part is zero. Quaternions with integer coefficients are called *Lipschitz integral quaternions*. Such a quaternion is *primitive*if its coefficients are relatively prime. Define the special quaternion σ = ( 1 + i + j + k) / 2 \sigma=(1+i+j+k)/2.

###### Proposition 2.1 ( [HW79]).

We have N ⁡ ( σ) = 1 \Norm(\sigma)=1 and σ 2 = σ − 1 \sigma^{2}=\sigma-1. Conjugating by σ \sigma induces a cyclic permutation on { i, j, k } \{i,j,k\} (see Section 3 for more details).

Quaternions of the form a ​ σ + b ​ i + c ​ j + d ​ k a\sigma+bi+cj+dk ( a, b, c, d ∈ ℤ a,b,c,d\in\BZ) are called *integral quaternions*, or *Hurwitz integral quaternions*and they form a ring 𝔼 \BE.

###### Proposition 2.2.

A quaternion α = a + b ​ i + c ​ j + d ​ k \alpha=a+bi+cj+dk belongs to 𝔼 \BE if and only if the numbers 2 ​ a, 2 ​ b, 2 ​ c, 2 ​ d 2a,2b,2c,2d are rational integers with the same parity. If α \alpha is such, then N ⁡ ( α) ∈ ℤ \Norm(\alpha)\in\BZ. A pure integral quaternion has integer coefficients, hence the Euler matrix E ⁡ ( α) E(\alpha), whose columns are α ​ i ​ α ¯ \alpha i\,\overline{\alpha}, α ​ j ​ α ¯ \alpha j\,\overline{\alpha}, α ​ k ​ α ¯ \alpha k\,\overline{\alpha}, has integer entries.

The Hurwitz integral quaternions form a maximal order in the rational quaternion algebra ( − 1, − 1 ℚ) \left(\frac{-1,-1}{\BQ}\right). We shall use the symbol ∣ \mid to denote divisibility *on the left*in 𝔼 \BE.

###### Proposition 2.3.

An integral quaternion is a unit if and only if its norm is 1 1. These are exactly the 24 24 elements ± 1 \pm 1, ± i \pm i, ± j \pm j, ± k \pm k, ( ± 1 ± i ± j ± k) / 2 (\pm 1\pm i\pm j\pm k)/2, which form a group under multiplication. Every integral quaternion has a left associate that has integer coefficients ( [HW79], p. 305, [CS03], Section 5.2).

###### Theorem 2.4.

The ring 𝔼 \BE is right Euclidean: for every α, β ∈ 𝔼 \alpha,\beta\in\BE with β ≠ 0 \beta\neq 0, there exist ω, ρ ∈ 𝔼 \omega,\rho\in\BE such that α = β ​ ω + ρ \alpha=\beta\omega+\rho and N ⁡ ( ρ) < N ⁡ ( β) \Norm(\rho)<\Norm(\beta) (see Theorem 373 of [HW79]).

Since α ↦ α ¯ \alpha\mapsto\overline{\alpha} is an isomorphism between 𝔼 \BE and its dual, every assertion that we prove for 𝔼 \BE remains true if we replace “left” with “right” and vice versa. As 𝔼 \BE is left Euclidean, every element can be written as a product of irreducible quaternions. This decomposition is unique in a certain sense (see [CS03], Section 5.2).

We shall need the following two technical lemmas.

###### Lemma 2.5.

Suppose that α ∈ 𝔼 \alpha\in\BE and p ∈ ℤ p\in\BZ is a prime such that p | N ⁡ ( α) p\mid\Norm(\alpha) but p p does not divide α \alpha. Then α \alpha can be written as π ​ α ′ \pi\alpha^{\prime}, where N ⁡ ( π) = p \Norm(\pi)=p. This π \pi is uniquely determined up to right association.

An element π \pi is a left divisor of α \alpha with norm p p if and only if π \pi is the generator of the right ideal ( α, p) r (\alpha,p)_{r}.

###### Proof.

The fact that α \alpha is left divisible by a prime π \pi of norm p p, with the additional property ( π) r = ( α, p) r (\pi)_{r}=(\alpha,p)_{r}, follows easily from Theorem 2 in Section 5.2 of [CS03]. (Note that that argument only uses the hypothesis that p p does not divide α \alpha, not the primitivity of α \alpha.) Suppose that π 1 \pi_{1} is also left divisor of α \alpha with norm p p. Then α \alpha and p = π 1 ​ π 1 ¯ p=\pi_{1}\overline{\pi_{1}} are in ( π 1) r (\pi_{1})_{r}, so ( π) r = ( α, p) r ⊆ ( π 1) r (\pi)_{r}=(\alpha,p)_{r}\subseteq(\pi_{1})_{r}. Thus, π 1 \pi_{1} divides π \pi on the right, and as they have the same norm, they are right associates, implying also that ( π 1) r = ( π) r = ( α, p) r (\pi_{1})_{r}=(\pi)_{r}=(\alpha,p)_{r}. ∎

###### Lemma 2.6.

Suppose that θ, η, π ∈ 𝔼 \theta,\eta,\pi\in\BE, such that N ⁡ ( π) = p \Norm(\pi)=p is a prime in ℤ \BZ. If π | θ \pi\mid\theta, p | θ ¯ ​ η p\mid\overline{\theta}\eta but p p does not divide θ \theta, then π | η \pi\mid\eta.

###### Proof.

By Lemma 2.5, ( p, θ) r = ( π) r (p,\theta)_{r}=(\pi)_{r}, that is, π = θ ​ τ 1 + p ​ τ 2 \pi=\theta\tau_{1}+p\tau_{2}, for some τ 1, τ 2 ∈ 𝔼 \tau_{1},\tau_{2}\in\BE. Hence, π ¯ ​ η = τ 1 ¯ ​ θ ¯ ​ η + p ​ τ 2 ¯ ​ η \overline{\pi}\eta=\overline{\tau_{1}}\overline{\theta}\eta+p\overline{\tau_{2}}\eta, and as p p divides θ ¯ ​ η \overline{\theta}\eta, we get that p | π ¯ ​ η p\mid\overline{\pi}\eta. Using p = π ¯ ​ π p=\overline{\pi}\pi, this shows that π | η \pi\mid\eta. ∎

###### Theorem 2.7.

An integral quaternion is irreducible in the ring 𝔼 \BE if and only if its norm is a prime in ℤ \BZ (see Theorem 377 of [HW79]). The only elements of 𝔼 \BE whose norm is 2 2 are λ = 1 + i \lambda=1+i and its left associates. If p > 2 p>2 is a prime in ℤ \BZ, then there exist exactly 24 ​ ( p + 1) 24(p+1) integral quaternions whose norm is p p (see the note right after the proof of Theorem 3 in Section 5.3 of [CS03]).

###### Corollary 2.8.

The number of integral quaternions with norm n n is 24 24 times the sum of positive odd divisors of n n.

###### Lemma 2.9.

Let p ∈ ℤ p\in\BZ be a prime and ℓ ≥ 0 \ell\geq 0. Suppose that π 1 ∈ 𝔼 \pi_{1}\in\BE is fixed and has norm p p. Consider all integer quaternions α \alpha such that N ⁡ ( α) = p ℓ \Norm(\alpha)=p^{\ell} and α ​ π 1 \alpha\pi_{1} is not divisible by p p. Then the number of such α \alpha is 24 ​ p ℓ 24p^{\ell}.

###### Proof.

We do induction on ℓ \ell. If ℓ = 0 \ell=0, then the statement is trivial, since the number of units is 24 24. Suppose that p p does not divide α \alpha. The dual of Lemma 2.5 shows that α \alpha can be written as α 2 ​ π 2 \alpha_{2}\pi_{2}, with N ⁡ ( π 2) = p \Norm(\pi_{2})=p, where α 2 \alpha_{2} is unique up to right association, and π 2 \pi_{2} is unique up to left association. Apply Lemma 2.6 for θ ↦ α ¯ \theta\mapsto\overline{\alpha}, η ↦ π 1 \eta\mapsto\pi_{1}, and π ↦ π 2 ¯ \pi\mapsto\overline{\pi_{2}}. We get that if α ​ π 1 \alpha\pi_{1} is divisible by p p, then π 2 \pi_{2} and π 1 ¯ \overline{\pi_{1}} are left associates. Conversely, if π 2 \pi_{2} and π 1 ¯ \overline{\pi_{1}} are left associates, then clearly p | α ​ π 1 p\mid\alpha\pi_{1}.

By Theorem 2.7, the number of elements of norm p p up to left association is p + 1 p+1. So π 2 \pi_{2} can be chosen p p ways, and by the induction assumption, α 2 \alpha_{2} can be chosen 24 ​ p ℓ − 1 24p^{\ell-1} ways for every given π 2 \pi_{2}. Thus, α \alpha can be chosen 24 ​ p ℓ − 1 ​ p 24p^{\ell-1}p ways. ∎

## 3. Integral Euler matrices

Our goal in this section is to characterize (in Theorem 3.3) all Euler matrices E ⁡ ( α) E(\alpha) with integer entries (called *integral Euler matrices*) in terms of the corresponding quaternion α \alpha. Sárközy’s Theorem 1.2 is obtained as Corollary 3.9

First, we demonstrate how to permute the columns of an Euler matrix by changing its generating quaternion. By Theorem 1.1, E ⁡ ( α) E(\alpha) is the matrix of R ⁡ ( α): β ↦ α ​ β ​ α ¯ R(\alpha):\beta\mapsto\alpha\beta\,\overline{\alpha}, hence E ⁡ ( α ​ ε) = E ⁡ ( α) ​ E ​ ( ε) E(\alpha\varepsilon)=E(\alpha)E(\varepsilon). The map R ⁡ ( α) R(\alpha) is always orientation-preserving, but the map corresponding to an icube (as a matrix) may not be. This problem is averted by taking the negative of an odd number of columns.

###### Proposition 3.1 (cf. [CS03], Section 3.5).

Let ε \varepsilon be

1. ( A) (A)

σ \sigma or σ − 1 \sigma^{-1}, where σ = ( 1 + i + j + k) / 2 \sigma=(1+i+j+k)/2. Then R ⁡ ( ε) R(\varepsilon) is the rotation of ℝ 3 \BR^{3} about the vector i + j + k i+j+k by an angle of ± 120 ∘ \pm 120^{\circ} (thus cyclically permuting the three coordinate axes). Therefore, E ⁡ ( α ​ ε) E(\alpha\varepsilon) is obtained from E ⁡ ( α) E(\alpha) by applying a cyclic permutation to the columns.

2. ( B) (B)

( 1 ± i) / 2 (1\pm i)/\sqrt{2}. Then R ⁡ ( ε) R(\varepsilon) is the rotation about the unit vector i ∈ ℤ 3 i\in\BZ^{3} by an angle of ± 90 ∘ \pm 90^{\circ} (interchanging the other two coordinate axes). Therefore, E ⁡ ( α ​ ε) E(\alpha\varepsilon) is obtained from E ⁡ ( α) E(\alpha) by switching the last two columns and taking the negative of one. A similar statement holds for ( 1 ± j) / 2 (1\pm j)/\sqrt{2} and ( 1 ± k) / 2 (1\pm k)/\sqrt{2}.

3. ( C) (C)

± i \pm i. Then R ⁡ ( ε) R(\varepsilon) is the half turn (that is, 180 ∘ 180^{\circ} rotation) about the unit vector i ∈ ℤ 3 i\in\BZ^{3} (fixing all coordinate axes). Therefore, E ⁡ ( α ​ ε) E(\alpha\varepsilon) is obtained from E ⁡ ( α) E(\alpha) by taking the negative of the last two columns. A similar statement holds for ± j \pm j and ± k \pm k. This transformation is the square of the one described in ( B) (B).

Every non-identical permutation of the columns of E ⁡ ( α) E(\alpha) can be obtained by one of the above modifications of α \alpha, but in case of an odd permutation one of the columns changes its sign. One can also change the sign of any two columns.∎

Before proceeding, let us review the action of these isometries on ℝ 3 \BR^{3}.

###### Proposition 3.2 (cf. [CS03], Section 3.5).

Denote by H H the group of units of 𝔼 \BE (see Proposition 2.3), set Q = { ± 1, ± i, ± j, ± k } Q=\{\pm 1,\pm i,\pm j,\pm k\} and let G G be the subgroup of the multiplicative group of ℍ \BH generated by H H and ( 1 + i) / 2 (1+i)/\sqrt{2}. Then G G contains all the isometries investigated in Proposition 3.1. The group G G has 48 48 elements.

The element σ \sigma has order 6 6. The rotation R ⁡ ( σ) R(\sigma) maps η = a ​ i + b ​ j + c ​ k \eta=ai+bj+ck to c ​ i + a ​ j + b ​ k ci+aj+bk, so it permutes the components cyclically.

The element ( 1 + i) / 2 (1+i)/\sqrt{2} has order 8 8. The corresponding rotation R ⁡ ( ( 1 + i) / 2) R\big((1+i)/\sqrt{2}\big) maps η \eta to a ​ i − c ​ j + b ​ k ai-cj+bk. The square of this rotation is R ⁡ ( i) R(i), mapping η \eta to a ​ i − b ​ j − c ​ k ai-bj-ck.

In general, G G acts on the set of pure quaternions via the rotations R ⁡ ( ρ) R(\rho) with ρ ∈ G \rho\in G. The orbit of η \eta under Q Q consists of η \eta, − a ​ i − b ​ j + c ​ k -ai-bj+ck, − a ​ i + b ​ j − c ​ k -ai+bj-ck, and + a ​ i − b ​ j − c ​ k +ai-bj-ck. If we disregard the signs, then every other element of H H induces a fixed point free permutation on the components of η \eta.∎

###### Theorem 3.3.

E ⁡ ( α) E(\alpha) is a primitive integral Euler matrix if and only if the non-zero quaternion α \alpha belongs to one of the following three types.

1. ( 1) (1)

α \alpha is a primitive Lipschitz integral quaternion with an odd norm.

2. ( 2) (2)

α = β / 2 \alpha=\beta/\sqrt{2}, where β \beta is a primitive Lipschitz integral quaternion such that N ⁡ ( β) ≡ 2 ​ ( 4) \Norm(\beta)\equiv 2~(4), or equivalently: exactly two components of β \beta are odd.

3. ( 3) (3)

α = β / 2 \alpha=\beta/2, where β \beta is a primitive Lipschitz integral quaternion such that N ⁡ ( β) ≡ 4 ​ ( 8) \Norm(\beta)\equiv 4~(8), or equivalently: all four components of β \beta are odd (so α \alpha is a Hurwitz integral quaternion).

In all cases N ⁡ ( α) \Norm(\alpha) is an odd integer. Each column and each row of E ⁡ ( α) E(\alpha) contains exactly one odd entry. The number of odd entries in the main diagonal in types ( 1) (1), ( 2) (2), ( 3) (3) are 3 3, 1 1, 0 0, respectively.

The proof requires four lemmas, whose proofs are elementary calculations.

###### Lemma 3.4.

If β \beta is a primitive Lipschitz integral quaternion, then N ⁡ ( β) \Norm(\beta) cannot be divisible by 8 8. It is congruent to 2 2 modulo 4 4 if and only if β \beta has exactly two odd components, and is congruent to 4 4 modulo 8 8 if and only if all components of β \beta are odd.∎

###### Lemma 3.5.

If E ⁡ ( α) E(\alpha) is a primitive integral Euler matrix, then N ⁡ ( α) \Norm(\alpha) is an odd integer. Each column and each row contains exactly one odd entry.∎

###### Lemma 3.6.

If the quaternion α = ( m + n ​ i + p ​ j + q ​ k) / 2 \alpha=(m+ni+pj+qk)/2 belongs to class ( 3) (3) of Theorem 3.3, then either α ​ σ \alpha\sigma or α ​ σ − 1 \alpha\sigma^{-1} is a quaternion of class ( 1) (1).∎

###### Lemma 3.7.

Every quaternion α = ( m + n ​ i + p ​ j + q ​ k) / 2 \alpha=(m+ni+pj+qk)/\sqrt{2} of class ( 2) (2) can be multiplied on the right by a suitable unit ( 1 + u) / 2 (1+u)/\sqrt{2} to transform it to a quaternion of class ( 1) (1), where u ∈ { i, j, k } u\in\{i,j,k\}.∎

###### Proof of Theorem 3.3.

Put α = m + n ​ i + p ​ j + k ​ q \alpha=m+ni+pj+kq with real numbers m, n, p, q m,n,p,q, and assume that the Euler matrix E ⁡ ( α) E(\alpha) given in Theorem 1.1 has integral entries and is primitive. By Lemma 3.5, N ⁡ ( α) = m 2 + n 2 + p 2 + q 2 \Norm(\alpha)=m^{2}+n^{2}+p^{2}+q^{2} is an integer, and the diagonal elements of E ⁡ ( α) E(\alpha) are also integers. Taking linear combinations of these quadratic forms, we get that 4 ​ m 2 4m^{2}, 4 ​ n 2 4n^{2}, 4 ​ p 2 4p^{2}, and 4 ​ q 2 4q^{2} are all integers. By adding and subtracting symmetric off-diagonal elements, we obtain that 4 ​ m ​ n 4mn, 4 ​ m ​ p 4mp, 4 ​ m ​ q 4mq, 4 ​ n ​ p 4np, 4 ​ n ​ q 4nq, and 4 ​ p ​ q 4pq are integers as well. Therefore, the square-free parts of the non-zero numbers among 4 ​ m 2, 4 ​ n 2, 4 ​ p 2 4m^{2},4n^{2},4p^{2}, and 4 ​ q 2 4q^{2} are the same. Denote this common square-free part by r r. The quaternion α = m + n ​ i + p ​ j + q ​ k \alpha=m+ni+pj+qk can be written uniquely in the form

(3.8) |  | α = k ​ r 2 ​ ( a + b ​ i + c ​ j + d ​ k), \alpha=\frac{k\sqrt{r}}{2}(a+bi+cj+dk), |  |

where k ∈ ℕ k\in\BN, a, b, c, d ∈ ℤ a,b,c,d\in\BZ, ( a, b, c, d) = 1 (a,b,c,d)=1. Since the matrix E ⁡ ( α) E(\alpha) is primitive, neither k k nor the square-free r r can have any odd prime divisor, and k k (as a power of 2 2) cannot be greater than 2 2. Hence, both k k and r r are elements of the set { 1, 2 } \{1,2\}, but k = r = 2 k=r=2 violates primitivity of E ⁡ ( α) E(\alpha). Thus, we are left with the cases

1. ( a) (a)

k = 2 k=2, r = 1 r=1;

2. ( b) (b)

k = 1 k=1, r = 2 r=2;

3. ( c) (c)

k = r = 1 k=r=1.

These correspond exactly to the cases listed as ( 1) (1), ( 2) (2), and ( 3) (3) in Theorem 3.3. Lemma 3.5 shows that N ⁡ ( α) \Norm(\alpha) is an odd integer. Therefore, Lemma 3.4 finishes the proof of one implication of the theorem.

Assume now that the quaternion α \alpha is one of the types ( 1) (1) – ( 3) (3) in Theorem 3.3. We want to show that E ⁡ ( α) E(\alpha) is a primitive integer matrix. By Lemmas 3.6 and 3.7, there exists a suitable quaternion ε ∈ ℍ \varepsilon\in\BH with N ⁡ ( ε) = 1 \Norm(\varepsilon)=1 such that α ​ ε \alpha\varepsilon is of class ( 1) (1), and by Proposition 3.1, we see that E ⁡ ( α ​ ε) = E ⁡ ( α) ​ E ​ ( ε) E(\alpha\varepsilon)=E(\alpha)E(\varepsilon) is a primitive integral matrix if and only if E ⁡ ( α) E(\alpha) is.

We show that E ⁡ ( α ​ ε) E(\alpha\varepsilon) is primitive. Since N ⁡ ( α ​ ε) \Norm(\alpha\varepsilon) is odd by assumption, the entries in the main diagonal of E ⁡ ( α ​ ε) E(\alpha\varepsilon) are odd. Suppose that an odd rational prime t t divides all entries of E ⁡ ( α ​ ε) E(\alpha\varepsilon). Let α ​ ε = m + n ​ i + p ​ j + q ​ k \alpha\varepsilon=m+ni+pj+qk. The simple calculation preceding ( 3.8) shows that t t divides the numbers 4 ​ m 2, 4 ​ n 2, 4 ​ p 2 4m^{2},4n^{2},4p^{2}, and 4 ​ q 2 4q^{2}, violating the primitivity of α ​ ε \alpha\varepsilon. Thus, E ⁡ ( α ​ ε) = E ⁡ ( α) ​ E ​ ( ε) E(\alpha\varepsilon)=E(\alpha)E(\varepsilon) is indeed a primitive integer matrix.

We now show the last statement of the theorem. If α \alpha belongs to type ( 1) (1), then, as we saw above, the entries in the main diagonal are odd, while the other entries are clearly even. Quaternions of class ( 2) (2) are handled by Lemma 3.7, and these correspond to the interchange of two columns by ( B) (B) of Proposition 3.1. The type ( 3) (3) case is handled by Lemma 3.6 and yields a cyclic fixed point free permutation of the columns, by ( A) (A) of Proposition 3.1. This completes the proof of Theorem 3.3. ∎

###### Corollary 3.9.

Consider a primitive icube as the columns of a matrix M M. Then there exists a Lipschitz integral quaternion α \alpha such that, by permuting the columns of E ⁡ ( α) E(\alpha) and changing the sign of the last column if necessary, we get M M.

###### Proof.

Change the sign of the last column if and only if M M is orientation-reversing. The new M M can be written as M = E ⁡ ( α) M=E(\alpha), for some quaternion α \alpha (with real coefficients) by Theorem 1.1. This α \alpha belongs to one of the three types listed in Theorem 3.3. Modify α \alpha using Proposition 3.1 so that the odd entries move to the main diagonal. Then we get a Lipschitz integral quaternion by the last statement of Theorem 3.3. If this transformation changes the sign of a column other than what was initially the third, then use Proposition 3.1 to change the sign of two columns to what they were originally. ∎

## 4. A representation of pure integral quaternions

In this section we decompose single pure quaternions. Geometrically, this means that we find a large cubic lattice that contains the corresponding vector. Algebraically, a cubic lattice is the subgroup of all quaternions δ = α ​ β ​ α ¯ \delta=\alpha\beta\,\overline{\alpha}, where α \alpha is a fixed Hurwitz integral quaternion and β \beta runs over all pure integral quaternions. The generating icube is given by α ​ i ​ α ¯ \alpha i\,\overline{\alpha}, α ​ j ​ α ¯ \alpha j\,\overline{\alpha}, α ​ k ​ α ¯ \alpha k\,\overline{\alpha}.

The primitive case is easier, and is handled by Theorem 4.2. This already implies Theorem 1.4, and the existence statement of Theorem 1.5. Theorem 4.6 explains how a vector in a cubic lattice can be divisible by a prime “unexpectedly”. This will be used in the characterization of twin-complete numbers, and is also sufficient to obtain a classical result about counting all vectors of a given length (Theorem 4.8, Corollary 4.9).

The results in this section are closely related to those in [Pal40], but that paper deals primarily with Lipschitz integral quaternions.

###### Lemma 4.1.

Let δ ∈ 𝔼 \delta\in\BE be a pure quaternion and p ∈ ℤ p\in\BZ a prime such that p 2 | N ⁡ ( δ) p^{2}\mid\Norm(\delta) but p p does not divide δ \delta. Then there exists an element π ∈ 𝔼 \pi\in\BE whose norm is p p such that δ = π ​ δ 1 ​ π ¯ \delta=\pi\delta_{1}\overline{\pi}, for some δ 1 ∈ 𝔼 \delta_{1}\in\BE.

###### Proof.

By Lemma 2.5, we get that δ = π ​ δ 2 \delta=\pi\delta_{2}, for some π, δ 2 ∈ 𝔼 \pi,\delta_{2}\in\BE such that N ⁡ ( π) = p \Norm(\pi)=p. Then N ⁡ ( δ) = p ​ N ⁡ ( δ 2) \Norm(\delta)=p\Norm(\delta_{2}). Hence, p p divides N ⁡ ( δ 2) \Norm(\delta_{2}) but p p clearly does not divide δ 2 \delta_{2}. By the dual of Lemma 2.5, we obtain an element π 1 ∈ 𝔼 \pi_{1}\in\BE with norm p p such that δ 2 = δ 3 ​ π 1 \delta_{2}=\delta_{3}\pi_{1}. Hence, δ = π ​ δ 3 ​ π 1 \delta=\pi\delta_{3}\pi_{1}. Taking conjugates, we get δ ¯ = π 1 ¯ ​ δ 3 ¯ ​ π ¯ \overline{\delta}=\overline{\pi_{1}}\overline{\delta_{3}}\overline{\pi}; however, δ \delta is a pure quaternion, hence δ ¯ = − δ \overline{\delta}=-\delta. Therefore, δ \delta is divisible by π \pi and by π 1 ¯ \overline{\pi_{1}} on the left. By the uniqueness statement of Lemma 2.5, we get that π \pi and π 1 ¯ \overline{\pi_{1}} are right associates. Thus, δ = π ​ δ 3 ​ π 1 \delta=\pi\delta_{3}\pi_{1} can indeed be written as π ​ δ 1 ​ π ¯ \pi\delta_{1}\overline{\pi}. ∎

###### Theorem 4.2.

Let δ ∈ 𝔼 \delta\in\BE be a pure quaternion with N ⁡ ( δ) = n ​ m 2 \Norm(\delta)=nm^{2}. Suppose that no integer prime divisor of m m divides δ \delta. Then δ \delta can be written as α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha}, for some α, β ∈ 𝔼 \alpha,\beta\in\BE such that N ⁡ ( α) = m \Norm(\alpha)=m and N ⁡ ( β) = n \Norm(\beta)=n. Here α \alpha is uniquely determined, that is, any two such elements α \alpha are right associates of each other and the corresponding elements β \beta are group-conjugates of each other via a unit of 𝔼 \BE. If n = 1 n=1, then β \beta can be chosen freely to be any element of { ± i, ± j, ± k } \{\pm i,\pm j,\pm k\}.

###### Proof.

The existence of α \alpha and β \beta is easily proven by induction on m m: apply Lemma 4.1 successively for each of the prime divisors of m m.

For the uniqueness assume that δ = α 1 ​ β 1 ​ α 1 ¯ = α 2 ​ β 2 ​ α 2 ¯ \delta=\alpha_{1}\beta_{1}\overline{\alpha_{1}}=\alpha_{2}\beta_{2}\overline{\alpha_{2}}. We use induction on m m again. If m = 1 m=1, then α 1 \alpha_{1} and α 2 \alpha_{2} are units, so they are right associates, and the unit ε = α 2 − 1 ​ α 1 \varepsilon=\alpha_{2}^{-1}\alpha_{1} satisfies ε ​ β 1 ​ ε − 1 = β 2 \varepsilon\beta_{1}\varepsilon^{-1}=\beta_{2}. If m > 1 m>1, then let p ∈ ℤ p\in\BZ be a prime divisor of m m. Apply Lemma 2.5 to get π 1, π 2 ∈ 𝔼 \pi_{1},\pi_{2}\in\BE, with π 1 | α 1 \pi_{1}\mid\alpha_{1} and π 2 | α 2 \pi_{2}\mid\alpha_{2}. Then π 1 \pi_{1} and π 2 \pi_{2} divide δ \delta on the left, and the uniqueness statement of Lemma 2.5 implies that π 1 \pi_{1} and π 2 \pi_{2} are right associates. Thus, if π 2 = π 1 ​ ε \pi_{2}=\pi_{1}\varepsilon, α 1 = π 1 ​ α 3 \alpha_{1}=\pi_{1}\alpha_{3} and α 2 = π 2 ​ α 4 \alpha_{2}=\pi_{2}\alpha_{4}, then δ ′ = α 3 ​ β 1 ​ α 3 ¯ = ( ε ​ α 4) ​ β 2 ​ ε ​ α 4 ¯ \delta^{\prime}=\alpha_{3}\beta_{1}\,\overline{\alpha_{3}}=(\varepsilon\alpha_{4})\beta_{2}\,\overline{\varepsilon\alpha_{4}}. By the induction hypothesis, α 3 \alpha_{3} and ε ​ α 4 \varepsilon\alpha_{4} are right associates. Similarly, we see that α 1 = π 1 ​ α 3 \alpha_{1}=\pi_{1}\alpha_{3} and α 2 = π 1 ​ ε ​ α 4 \alpha_{2}=\pi_{1}\varepsilon\alpha_{4} are also right associates.

If n = 1 n=1, then β \beta is a unit in 𝔼 \BE. Since β \beta is a pure quaternion, it is contained in { ± i, ± j, ± k } \{\pm i,\pm j,\pm k\}. These six elements are group-conjugates of each other via a unit by Proposition 3.2. Therefore, by taking a right associate of α \alpha, we may choose any of them to be β \beta. ∎

###### Remark 4.3.

Theorem 4.2 implies Theorem 1.4, and the existence statement of Theorem 1.5. (The uniqueness part of Theorem 1.5 clearly follows from Theorem 4.2 and Corollary 3.9, but we give a “pure number-theoretic” proof in Section 5.)

###### Proof.

Let u u be a primitive vector and denote by δ \delta the corresponding pure quaternion. Decompose δ \delta using Theorem 4.2 as δ = α ​ β ​ α ¯ \delta=\alpha\beta\,\overline{\alpha} with N ⁡ ( α) = m \Norm(\alpha)=m. Then the cubic lattice corresponding to α \alpha has edge length m m and contains u u. This yields the existence statement of Theorem 1.5.

If the length if u u is an integer, then n = 1 n=1 and we may assume that β = i \beta=i. Then α ​ j ​ α ¯ \alpha j\,\overline{\alpha} and α ​ k ​ α ¯ \alpha k\,\overline{\alpha} extend u u to an icube, proving Theorem 1.4 in the primitive case. The general case obviously follows from this. ∎

###### Lemma 4.4.

Let β, β 1 ∈ 𝔼 \beta,\beta_{1}\in\BE be pure quaternions, each of norm n n. If β + β 1 ≠ 0 \beta+\beta_{1}\neq 0, then we have ( β + β 1) ​ β ​ ( β + β 1) − 1 = β 1 (\beta+\beta_{1})\beta(\beta+\beta_{1})^{-1}=\beta_{1}.

###### Proof.

The proof is a straightforward calculation using β 2 = β 1 2 = − n \beta^{2}=\beta_{1}^{2}=-n. Instead of presenting it, we explain this formula geometrically. Since γ = β + β 1 \gamma=\beta+\beta_{1} is a nonzero pure quaternion, conjugation by γ \gamma acts on ℝ 3 \BR^{3} as half turn about the line through γ \gamma, which clearly takes β \beta to β 1 \beta_{1}. ∎

###### Lemma 4.5.

Let π, β ∈ 𝔼 \pi,\beta\in\BE such that β \beta is a pure quaternion and p = N ⁡ ( π) > 2 p=\Norm(\pi)>2 is a prime in ℤ \BZ. Then π ​ β ​ π − 1 ∈ 𝔼 \pi\beta\pi^{-1}\in\BE if and only if there exists an integer h ∈ ℤ h\in\BZ such that π ¯ | h + β \overline{\pi}\mid h+\beta.

###### Proof.

Suppose that π ¯ | h + β \overline{\pi}\mid h+\beta, that is, π ¯ ​ τ = h + β \overline{\pi}\tau=h+\beta, for some τ ∈ 𝔼 \tau\in\BE. Then

 | p ​ τ ​ π ¯ = π ​ π ¯ ​ τ ​ π ¯ = π ​ h ​ π ¯ + π ​ β ​ π ¯ = p ​ h + π ​ β ​ π ¯. p\tau\overline{\pi}=\pi\overline{\pi}\tau\overline{\pi}=\pi h\overline{\pi}+\pi\beta\,\overline{\pi}=ph+\pi\beta\,\overline{\pi}\,. |  |

Hence, p | π ​ β ​ π ¯ p\mid\pi\beta\,\overline{\pi}, which shows that π ​ β ​ π − 1 = ( π ​ β ​ π ¯) / p \pi\beta\pi^{-1}=(\pi\beta\,\overline{\pi})/p is indeed an integral quaternion.

To prove the converse, set β 1 = π ​ β ​ π − 1 \beta_{1}=\pi\beta\pi^{-1} and τ = β + β 1 \tau=\beta+\beta_{1}. We can assume that π \pi does not divide τ \tau on the left, as we now show. Let

 | β 2 = ( i ​ π) ​ β ​ ( i ​ π) − 1 = i ​ β 1 ​ i − 1, \beta_{2}=(i\pi)\beta(i\pi)^{-1}=i\beta_{1}i^{-1}\,, |  |

which is still an integral quaternion. It is clearly sufficient to prove that i ​ π ¯ | h + β \overline{i\pi}\mid h+\beta, so we can work with i ​ π i\pi instead of π \pi in the argument below. If, however, both π \pi and i ​ π i\pi are “bad”, that is, π | τ = β + β 1 \pi\mid\tau=\beta+\beta_{1} and i ​ π | β + β 2 i\pi\mid\beta+\beta_{2}, then π | i − 1 ​ β ​ i + β 1 \pi\mid i^{-1}\beta i+\beta_{1}, which implies π | β − i − 1 ​ β ​ i \pi\mid\beta-i^{-1}\beta i. Put β = a ​ i + b ​ j + c ​ k \beta=ai+bj+ck. Then β − i − 1 ​ β ​ i = 2 ​ ( b ​ j + c ​ k) \beta-i^{-1}\beta i=2(bj+ck). If j ​ π j\pi and k ​ π k\pi are also “bad”, then π \pi divides 2 ​ ( a ​ i + c ​ k) 2(ai+ck) and 2 ​ ( a ​ i + b ​ j) 2(ai+bj) as well. Taking norms, we get, using N ⁡ ( π) = p > 2 \Norm(\pi)=p>2, that p p divides a 2 + b 2 a^{2}+b^{2}, a 2 + c 2 a^{2}+c^{2}, and b 2 + c 2 b^{2}+c^{2}. Thus, p p divides a a, b b, c c, and, finally, p p divides β \beta. Therefore, π ¯ | h + β \overline{\pi}\mid h+\beta, for h = 0 h=0, and we are done in this case. We can then indeed assume that π \pi does not divide τ \tau on the left.

Lemma 4.4 implies that τ ​ β ​ τ − 1 = β 1 = π ​ β ​ π − 1 \tau\beta\tau^{-1}=\beta_{1}=\pi\beta\pi^{-1}, so τ − 1 ​ π \tau^{-1}\pi centralizes β \beta. Let d = N ⁡ ( τ) d=\Norm(\tau). Then d ​ τ − 1 ​ π = τ ¯ ​ π d\tau^{-1}\pi=\overline{\tau}\pi centralizes β \beta as well. The centralizer of β \beta consists of elements r + s ​ β r+s\beta, where r, s ∈ ℝ r,s\in\BR. This set is closed under conjugation, since β \beta is a pure quaternion, and therefore, contains τ ¯ ​ π ¯ = π ¯ ​ τ \overline{\overline{\tau}\pi}=\overline{\pi}\tau. If we write π ¯ ​ τ = u + v ​ β \overline{\pi}\tau=u+v\beta, where u u and v v are real, and β = d ​ β ′ \beta=d\beta^{\prime}, where d ∈ ℤ d\in\BZ and β ′ \beta^{\prime} is primitive, then 2 ​ u 2u and 2 ​ v ​ d 2vd are integers. (We need the factor 2 2, because the integral quaternion π ¯ ​ τ \overline{\pi}\tau need not have integer coefficients).

We now show that p p does not divide 2 ​ v ​ d 2vd. Suppose it does. Taking norms, we get that N ⁡ ( π ¯) = p | 4 ​ N ⁡ ( u + v ​ β) = ( 2 ​ u) 2 + ( 2 ​ v ​ d) 2 ​ N ⁡ ( β ′) \Norm(\overline{\pi})=p\mid 4\Norm(u+v\beta)=(2u)^{2}+(2vd)^{2}\Norm(\beta^{\prime}), so p | 2 ​ u p\mid 2u. Thus, either u + v ​ β u+v\beta has integer coefficients, which are divisible by p p, or 2 ​ u + 2 ​ v ​ β 2u+2v\beta has odd integer coefficients that are divisible by p p. Since p ≠ 2 p\neq 2, we have u ′ + v ′ ​ β = ( u + v ​ β) / p ∈ 𝔼 u^{\prime}+v^{\prime}\beta=(u+v\beta)/p\in\BE in either case. Then π ¯ ​ τ = u + v ​ β = p ⁡ ( u ′ + v ′ ​ β) = π ¯ ​ π ​ ( u ′ + v ′ ​ β) \overline{\pi}\tau=u+v\beta=p(u^{\prime}+v^{\prime}\beta)=\overline{\pi}\pi(u^{\prime}+v^{\prime}\beta), and τ = π ⁡ ( u ′ + v ′ ​ β) \tau=\pi(u^{\prime}+v^{\prime}\beta), contradicting our assumption that π \pi does not divide τ \tau on the left. Therefore, we have that p p does not divide 2 ​ v ​ d 2vd.

Let x, y x,y be integers such that ( 2 ​ v ​ d) ​ x + y ​ p = 1 (2vd)x+yp=1. Then

 | π ¯ | 2 ​ x ​ ( u + v ​ d ​ β ′) = x ⁡ ( 2 ​ u) + ( 1 − y ​ p) ​ β ′. \overline{\pi}\mid 2x(u+vd\beta^{\prime})=x(2u)+(1-yp)\beta^{\prime}\,. |  |

Since π ¯ | p \overline{\pi}\mid p, we get that π ¯ | x ⁡ ( 2 ​ u) + β ′ \overline{\pi}\mid x(2u)+\beta^{\prime} and take h = x ⁡ ( 2 ​ u) ​ d h=x(2u)d. ∎

###### Theorem 4.6.

Suppose that α, β ∈ 𝔼 \alpha,\beta\in\BE such that β \beta is a pure quaternion and p ∈ ℤ p\in\BZ is a prime. Then p | α ​ β ​ α ¯ p\mid\alpha\beta\,\overline{\alpha} if and only if one of the following cases holds.

1. ( 1) (1)

p p divides α \alpha or β \beta.

2. ( 2) (2)

p = 2 p=2 and does not divide α, β \alpha,\beta, but divides N ⁡ ( α) \Norm(\alpha).

3. ( 3) (3)

p > 2 p>2 and does not divide α, β \alpha,\beta, but divides N ⁡ ( α) \Norm(\alpha), and there exists a right divisor π \pi of α \alpha with norm p p and an integer h ∈ ℤ h\in\BZ such that π ¯ | h + β \overline{\pi}\mid h+\beta.

In particular, every prime divisor of α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} divides either β \beta or N ⁡ ( α) \Norm(\alpha).

###### Proof.

If ( 1) (1) holds, then clearly p | α ​ β ​ α ¯ p\mid\alpha\beta\,\overline{\alpha}. If ( 2) (2) holds, then the dual of Lemma 2.5 shows that α \alpha is right divisible by 1 + i 1+i (since this is the only element in 𝔼 \BE of norm 2 2 up to left association), and Proposition 3.2 yields that ( 1 + i) ​ β ​ 1 + i ¯ (1+i)\beta\,\overline{1+i} is divisible by 2 2. Finally, if ( 3) (3) holds, then p | π ​ β ​ π ¯ p\mid\pi\beta\,\overline{\pi} by Lemma 4.5. This proves one direction of the theorem.

Now assume that p | α ​ β ​ α ¯ p\mid\alpha\beta\,\overline{\alpha} but α \alpha and β \beta are not divisible by p p. If p p does not divide N ⁡ ( α) \Norm(\alpha), then we have p | α ¯ ​ ( α ​ β ​ α ¯) ​ α = N ⁡ ( α) 2 ​ β p\mid\overline{\alpha}(\alpha\beta\,\overline{\alpha})\alpha=\Norm(\alpha)^{2}\beta. Hence, p | β p\mid\beta, which is a contradiction. Therefore, we may assume that we are in case ( 3) (3), that is, p > 2 p>2 and p | N ⁡ ( α) p\mid\Norm(\alpha). We proceed by induction on N ⁡ ( α) \Norm(\alpha). By the dual of Lemma 2.5, α = α 1 ​ π \alpha=\alpha_{1}\pi for some α 1, π ∈ 𝔼 \alpha_{1},\pi\in\BE, with N ⁡ ( π) = p \Norm(\pi)=p. We show that β 1 = π ​ β ​ π ¯ \beta_{1}=\pi\beta\,\overline{\pi} is divisible by p p. Then we are clearly done by Lemma 4.5.

Suppose β 1 \beta_{1} is not divisible by p p. Apply the induction hypothesis to α 1 ​ β 1 ​ α 1 ¯ \alpha_{1}\beta_{1}\,\overline{\alpha_{1}} (which is equal to α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha}). We must be in case ( 3) (3), since p > 2 p>2 and p p does not divide both α 1 \alpha_{1} and β 1 \beta_{1}. Therefore, there exists a right divisor π 1 \pi_{1} of α 1 \alpha_{1} of norm p p and an integer h 1 h_{1} such that π 1 ¯ | h 1 + β 1 \overline{\pi_{1}}\mid h_{1}+\beta_{1}. Taking norms, we see that p = N ⁡ ( π 1 ¯) | N ⁡ ( h 1 + β) = h 1 2 + N ⁡ ( β 1) p=\Norm(\overline{\pi_{1}})\mid\Norm(h_{1}+\beta)=h_{1}^{2}+\Norm(\beta_{1}); however, N ⁡ ( β 1) = p 2 ​ N ⁡ ( β) \Norm(\beta_{1})=p^{2}\Norm(\beta) is divisible by p p, so p | h 1 p\mid h_{1}, and therefore, π 1 ¯ | β 1 \overline{\pi_{1}}\mid\beta_{1}. Since β 1 \beta_{1} is not divisible by p p, the uniqueness part of Lemma 2.5 shows that π 1 ¯ \overline{\pi_{1}} and π \pi are right associates. This implies α \alpha is divisible on the right by π 1 ​ π 1 ¯ = p \pi_{1}\overline{\pi_{1}}=p, contradicting our assumptions. ∎

###### Proposition 4.7.

Suppose that β ∈ 𝔼 \beta\in\BE is a pure quaternion and p p is a prime not dividing β \beta. Denote by e e the number of different quaternions of the form ε ​ β ​ ε − 1 \varepsilon\beta\varepsilon^{-1}, where ε \varepsilon runs over the units of 𝔼 \BE. Consider all quaternions α \alpha whose norm is p ℓ p^{\ell}, with some fixed ℓ > 0 \ell>0. If p > 2 p>2, then the number of quaternions of the form α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} that are not divisible by p p is

1. ( 1) (1)

e ​ p ℓ ep^{\ell}, if p | N ⁡ ( β) p\mid\Norm(\beta);

2. ( 2) (2)

e ⁡ ( p ℓ − p ℓ − 1) e(p^{\ell}-p^{\ell-1}), if − N ⁡ ( β) -\Norm(\beta) is a quadratic residue mod p p;

3. ( 3) (3)

e ⁡ ( p ℓ + p ℓ − 1) e(p^{\ell}+p^{\ell-1}) otherwise.

If p = 2 p=2, then this number is 0 0.

###### Proof.

If p = 2 p=2 (and ℓ > 0 \ell>0), then Theorem 4.6 shows that α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is divisible by p p, so suppose that p p is odd. We call a pair ( α 1, β 1) (\alpha_{1},\beta_{1}) “good”, if α 1 ∈ 𝔼 \alpha_{1}\in\BE with N ⁡ ( α 1) = p ℓ \Norm(\alpha_{1})=p^{\ell} and there is a unit ε ∈ 𝔼 \varepsilon\in\BE such that β 1 = ε − 1 ​ β ​ ε \beta_{1}=\varepsilon^{-1}\beta\varepsilon, and p p does not divide α 1 ​ β 1 ​ α 1 ¯ \alpha_{1}\beta_{1}\,\overline{\alpha_{1}}. By the uniqueness part of Theorem 4.2, every element α 1 ​ β 1 ​ α 1 ¯ \alpha_{1}\beta_{1}\,\overline{\alpha_{1}} is given by exactly 24 24 pairs. Therefore, it is sufficient to count the good pairs for any given β 1 \beta_{1}.

Let ( α 1, β 1) (\alpha_{1},\beta_{1}) be a good pair. Then clearly α 1 \alpha_{1} is not divisible by p p, so we can write α 1 = α 2 ​ π 2 \alpha_{1}=\alpha_{2}\pi_{2} by Lemma 2.5, where π 2 \pi_{2} of norm p p is uniquely determined up to left association. Theorem 4.6 shows that α 1 ​ β 1 ​ α 1 ¯ \alpha_{1}\beta_{1}\overline{\alpha_{1}} is divisible by p p if and only if π 2 ¯ \overline{\pi_{2}} divides h + β 1 h+\beta_{1}, for some integer h h (assuming that α 1 \alpha_{1} is not divisible by p p). We now count the number of such quaternions π 2 \pi_{2}.

Clearly, π 2 ¯ | h + β 1 \overline{\pi_{2}}\mid h+\beta_{1} implies N ⁡ ( π 2) = p | N ⁡ ( h + β 1) = h 2 + N ⁡ ( β 1) \Norm(\pi_{2})=p\mid\Norm(h+\beta_{1})=h^{2}+\Norm(\beta_{1}). This means that either p | N ⁡ ( β 1) p\mid\Norm(\beta_{1}) or − N ⁡ ( β 1) -\Norm(\beta_{1}) is a quadratic residue mod p p. Hence, in case ( 3) (3) above there is no such π 2 \pi_{2}. Since p p does not divide β 1 \beta_{1}, it does not divide h + β 1 h+\beta_{1}. Thus, by the uniqueness statement of Lemma 2.5, there is exactly one left divisor π 2 ¯ \overline{\pi_{2}} up to right association with norm p p of any given h + β 1 h+\beta_{1} for which p | h 2 + N ⁡ ( β 1) p\mid h^{2}+N(\beta_{1}), and π 2 \pi_{2} is unique up to left association. Clearly, the numbers h 1 h_{1} and h 2 h_{2} yield the same π 2 ¯ \overline{\pi_{2}} if and only if h 1 ≡ h 2 ​ ( p) h_{1}\equiv h_{2}~(p). If p | N ⁡ ( β 1) p\mid\Norm(\beta_{1}), then h = 0 h=0 is the only possibility. This yields one “bad” value for π 2 \pi_{2} up to left association. Otherwise, there are exactly two values 1 ≤ h ≤ p − 1 1\leq h\leq p-1 such that p | h 2 + N ⁡ ( β 1) p\mid h^{2}+\Norm(\beta_{1}) (since p p is an odd prime, assuming, of course, that − N ⁡ ( β 1) -\Norm(\beta_{1}) is a quadratic residue mod p p). So, in this case there are two “bad” values for π 2 \pi_{2} up to left association.

By Theorem 2.7, the number of possible choices for π 2 \pi_{2} is p + 1 p+1 up to left association. Thus, for every given β 1 \beta_{1}, the number of good values for π 2 \pi_{2} is p p, p − 1 p-1 and p + 1 p+1, respectively, corresponding to cases ( 1) (1), ( 2) (2) and ( 3) (3) in the claim. If π 2 \pi_{2} is fixed, then the number of choices for α 2 \alpha_{2} so that α 1 \alpha_{1} is not divisible by p p is, by Lemma 2.9, 24 ​ p ℓ − 1 24p^{\ell-1}. Since the number of possible β 1 \beta_{1} is e e, we get the result. ∎

In the theorem below, ( − n / p) (-n/p) denotes the Legendre symbol (which is defined to be 0 0 if p | n p\mid n).

###### Theorem 4.8.

Suppose that m, n ≥ 1 m,n\geq 1 are integers and n n is square-free. If m m is odd, then the number p ⁡ ( n ​ m 2) p(nm^{2}) of primitive vectors ( x, y, z) (x,y,z) whose norm is n ​ m 2 nm^{2} is

 | p ( n m 2) = p ( n) ∏ ( p ℓ − ( − n / p) p ℓ − 1), p(nm^{2})=p(n)\prod\Big(p^{\ell}-(-n/p)p^{\ell-1}\Big)\,, |  |

where p ℓ p^{\ell} runs over the prime powers in the canonical form of m m. If m m is even, then p ⁡ ( n ​ m 2) = 0 p(nm^{2})=0.

###### Proof.

We proceed by induction on the number of prime divisors of m m. Suppose that m = p ℓ ​ m 1 m=p^{\ell}m_{1}, where p p does not divide m 1 m_{1}. Theorem 4.2 implies that the pure quaternion δ = x ​ i + y ​ j + z ​ k \delta=xi+yj+zk corresponding to ( x, y, z) (x,y,z) can be represented as α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha}, where N ⁡ ( α) = p ℓ \Norm(\alpha)=p^{\ell}.

Theorem 4.6 shows that if β \beta is primitive, then the only possible prime divisor of α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is p p, and if p = 2 p=2 and ℓ > 0 \ell>0, then α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is not primitive, because it is divisible by 2 2. Thus, if p > 2 p>2, then α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is primitive if and only if β \beta is primitive and α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is not divisible by p p. The formula for p ⁡ ( n ​ m 2) p(nm^{2}) then follows clearly from Proposition 4.7. ∎

The following is a well-known formula (see (29) in [Pal40]), and follows with some effort from Theorem 4.8.

###### Corollary 4.9.

Suppose that m, n ≥ 1 m,n\geq 1 are integers and n n is square-free. The number s ⁡ ( n ​ m 2) s(nm^{2}) of all vectors of norm n ​ m 2 nm^{2} is

 | s ( n m 2) = s ( n) ∏ ( σ ( p ℓ) − ( − n / p) σ ( p ℓ − 1)), s(nm^{2})=s(n)\prod\Big(\sigma(p^{\ell})-(-n/p)\sigma(p^{\ell-1})\Big)\,, |  |

where p ℓ p^{\ell} runs over the odd prime powers in the canonical form of m m and σ ⁡ ( s) \sigma(s) denotes the sum of positive divisors of any integer s s.

## 5. A parameterization of twin pairs

Theorem 5.4 is our main characterization of twins. In Theorem 5.10, we count twin pairs with a given norm. Finally, we deal with the problem of extension. In Corollary 5.11, we show that each pair of twins whose length is an integer extends to an icube. Then, at the end of the section, we prove Theorem 1.5 and Corollary 1.6.

Recall that every vector v = ( v 1, v 2, v 3) ∈ ℝ 3 v=(v_{1},v_{2},v_{3})\in\BR^{3} is identified with the pure quaternion V ⁡ ( v) = v 1 ​ i + v 2 ​ j + v 3 ​ k V(v)=v_{1}i+v_{2}j+v_{3}k.

###### Proposition 5.1.

Two vectors v v and w w in ℤ 3 \BZ^{3} are twins if and only if θ = V ⁡ ( v) \theta=V(v) and η = V ⁡ ( w) \eta=V(w) satisfy the following conditions.

1. ( 1) (1)

θ \theta and η \eta are nonzero pure quaternions;

2. ( 2) (2)

N ⁡ ( θ) = N ⁡ ( η) \Norm(\theta)=\Norm(\eta);

3. ( 3) (3)

θ ​ η \theta\eta is also a pure quaternion;

4. ( 4) (4)

θ \theta and η \eta have integer coefficients.

We call a pair of such quaternions ( θ, η) (\theta,\eta) a *twin pair*.

###### Proof.

It is easy to verify that the real part of V ⁡ ( v) ​ V ​ ( w) V(v)V(w) equals the negative of the dot product of v v and w w, and the pure quaternion part of V ⁡ ( v) ​ V ​ ( w) V(v)V(w) corresponds to the cross product of v v and w w. ∎

We now translate the construction of twin pairs given in the Introduction. Denote by ( u, v, w) (u,v,w) the columns of an Euler matrix given by α ∈ 𝔼 \alpha\in\BE. By Proposition 2.2, N ⁡ ( α) \Norm(\alpha) and the components of ( u, v, w) (u,v,w) are integers. Let z = a + b ​ i ∈ 𝔾 z=a+bi\in\BG (the ring of Gaussian integers). Then E ⁡ ( α) E(\alpha) maps i i to V ⁡ ( u) V(u), j j to V ⁡ ( v) V(v), and k k to V ⁡ ( w) V(w). It maps the twin quaternions z ​ j = a ​ j + b ​ k zj=aj+bk and z ​ k = a ​ k − b ​ j zk=ak-bj to α ​ z ​ j ​ α ¯ \alpha zj\,\overline{\alpha} and α ​ z ​ k ​ α ¯ \alpha zk\,\overline{\alpha}, respectively, which correspond to the twin pair ( a ​ v + b ​ w, − b ​ v + a ​ w) (av+bw,-bv+aw).

###### Definition 5.2.

We say that ( θ, η) (\theta,\eta) is *parameterized*by the pair ( α, z) ∈ ℍ × ℂ (\alpha,z)\in\BH\times\BC if θ = α ​ z ​ j ​ α ¯ \theta=\alpha zj\,\overline{\alpha} and η = α ​ z ​ k ​ α ¯ \eta=\alpha zk\,\overline{\alpha}. Two pairs in ( α 1, z 1) ∈ ℍ × ℂ (\alpha_{1},z_{1})\in\BH\times\BC and ( α 2, z 2) ∈ ℍ × ℂ (\alpha_{2},z_{2})\in\BH\times\BC are *equivalent*if they parameterize the same ( θ, η) (\theta,\eta), that is, if α 1 ​ z 1 ​ j ​ α 1 ¯ = α 2 ​ z 2 ​ j ​ α 2 ¯ \alpha_{1}z_{1}j\,\overline{\alpha_{1}}=\alpha_{2}z_{2}j\,\overline{\alpha_{2}} and α 1 ​ z 1 ​ k ​ α 1 ¯ = α 2 ​ z 2 ​ k ​ α 2 ¯ \alpha_{1}z_{1}k\,\overline{\alpha_{1}}=\alpha_{2}z_{2}k\,\overline{\alpha_{2}}.

###### Proposition 5.3.

Suppose that ( θ, η) (\theta,\eta) is parameterized by a pair ( α, z) ∈ ℍ × ℂ (\alpha,z)\in\BH\times\BC. Then θ ​ η = N ⁡ ( α) ​ N ⁡ ( z) ​ α ​ i ​ α ¯ \theta\eta=\Norm(\alpha)\Norm(z)\alpha i\,\overline{\alpha}, so θ \theta and η \eta satisfy ( 1) (1) – ( 3) (3) of Proposition 5.1. If α ∈ 𝔼 \alpha\in\BE and z ∈ 𝔾 z\in\BG, then θ \theta and η \eta have integer coefficients and are twins.

###### Proof.

Note that α − 1 = α ¯ / N ⁡ ( α) \alpha^{-1}=\overline{\alpha}/\Norm(\alpha) and x ↦ α ​ x ​ α − 1 x\mapsto\alpha x\alpha^{-1} is an automorphism of the division ring ℍ \BH. Therefore, θ ​ η = N ⁡ ( α) ​ α ​ z ​ j ​ z ​ k ​ α ¯ \theta\eta=\Norm(\alpha)\alpha zjzk\,\overline{\alpha}; however, z ​ j ​ z ​ k = z ​ j ​ z ​ j − 1 ​ j ​ k = z ​ z ¯ ​ i zjzk=zjzj^{-1}jk=z\overline{z}i, so the quaternion θ ​ η = N ⁡ ( α) ​ N ⁡ ( z) ​ α ​ i ​ α ¯ \theta\eta=\Norm(\alpha)\Norm(z)\alpha i\,\overline{\alpha} is pure. ∎

###### Theorem 5.4.

The characterization of twin quaternions is given by the following.

1. ( 1) (1)

The quaternions θ \theta and η \eta are twins if and only if ( θ, η) (\theta,\eta) is parameterized by a pair in 𝔼 × 𝔾 \BE\times\BG (whose components are nonzero).

2. ( 2) (2)

Every pair in 𝔼 × 𝔾 \BE\times\BG is equivalent to a pair, where the second component is *square-free*in 𝔾 \BG.

3. ( 3) (3)

Let ( α 1, z 1), ( α 2, z 2) ∈ 𝔼 × 𝔾 (\alpha_{1},z_{1}),(\alpha_{2},z_{2})\in\BE\times\BG be such that both z 1 z_{1} and z 2 z_{2} are square-free. Then these pairs are equivalent if and only if there exists a unit ρ ∈ 𝔾 \rho\in\BG (that is, an element of { ± 1, ± i } \{\pm 1,\pm i\}) such that α 2 = α 1 ​ ρ \alpha_{2}=\alpha_{1}\rho and z 2 = ρ 2 ​ z 1 z_{2}=\rho^{2}z_{1}.

4. ( 4) (4)

The length of the twins θ \theta and η \eta is an integer if and only if in the parameterization ( α, z) (\alpha,z) of ( θ, η) (\theta,\eta), where z z is square-free, z ∈ 𝔾 z\in\BG is either real or pure imaginary.

The condition that z z is square-free expresses the fact that the cubic lattice given by α \alpha is as large as possible. We prove this theorem through a series of assertions.

###### Lemma 5.5.

Suppose that θ, η ∈ 𝔼 \theta,\eta\in\BE is such that θ \theta, η \eta and θ ​ η \theta\eta are pure quaternions. Let p ∈ ℤ p\in\BZ be a prime such that p p divides N ⁡ ( θ) \Norm(\theta) and N ⁡ ( η) \Norm(\eta). Then p | θ ​ η p\mid\theta\eta.

###### Proof.

Suppose that p p does not divide θ ​ η \theta\eta. By Lemma 2.5 and Lemma 4.1, we have θ = π 1 ​ θ 1 \theta=\pi_{1}\theta_{1}, η = η 1 ​ π 2 \eta=\eta_{1}\pi_{2}, and θ ​ η = π ​ δ 1 ​ π ¯ \theta\eta=\pi\delta_{1}\overline{\pi}, where π, π 1, π 2 \pi,\pi_{1},\pi_{2} have norm p p. By the uniqueness part of Lemma 2.5, π \pi, π 1 \pi_{1}, and π 2 ¯ \overline{\pi_{2}} are right associates; however, θ \theta, η \eta, and θ ​ η \theta\eta are pure quaternions, so θ ​ η = − θ ​ η ¯ = − η ¯ ​ θ ¯ = − η ​ θ = − η 1 ​ π 2 ​ π 1 ​ θ 1 \theta\eta=-\overline{\theta\eta}=-\overline{\eta}\,\overline{\theta}=-\eta\theta=-\eta_{1}\pi_{2}\pi_{1}\theta_{1} is divisible by p p, a contradiction. ∎

###### Lemma 5.6.

Suppose θ, η ∈ 𝔼 \theta,\eta\in\BE is such that θ \theta, η \eta, and θ ​ η \theta\eta are pure quaternions. Let p ∈ ℤ p\in\BZ be a prime such that p 2 p^{2} divides both N ⁡ ( θ) \Norm(\theta) and N ⁡ ( η) \Norm(\eta), but p p does not divide both θ \theta and η \eta. Then there exist elements π, θ 1, η 1 ∈ 𝔼 \pi,\theta_{1},\eta_{1}\in\BE such that N ⁡ ( π) = p \Norm(\pi)=p, θ = π ​ θ 1 ​ π ¯ \theta=\pi\theta_{1}\overline{\pi}, and η = π ​ η 1 ​ π ¯ \eta=\pi\eta_{1}\overline{\pi}.

###### Proof.

By Lemma 5.5, p | δ = θ ​ η p\mid\delta=\theta\eta. Using Lemma 4.1, we can write θ = π ​ θ 1 ​ π ¯ \theta=\pi\theta_{1}\overline{\pi} and η = π 1 ​ η 1 ​ π 1 ¯ \eta=\pi_{1}\eta_{1}\overline{\pi_{1}}, where N ⁡ ( π) = N ⁡ ( π 1) = p \Norm(\pi)=\Norm(\pi_{1})=p. Since θ \theta is pure, δ = θ ​ η = − θ ¯ ​ η \delta=\theta\eta=-\overline{\theta}\eta, and Lemma 2.6 shows that π | η \pi\mid\eta. Applying the uniqueness part of Lemma 2.5 to η \eta, we obtain that π \pi and π 1 \pi_{1} are right associates. ∎

###### Lemma 5.7.

Suppose θ, η ∈ 𝔼 \theta,\eta\in\BE is such that θ \theta, η \eta, and θ ​ η \theta\eta are pure quaternions. Let p ∈ ℤ p\in\BZ be a prime such that p 2 p^{2} divides N ⁡ ( θ) \Norm(\theta) but p p does not divide θ \theta. Then there exist elements π, θ 1, η 1 ∈ 𝔼 \pi,\theta_{1},\eta_{1}\in\BE such that N ⁡ ( π) = p \Norm(\pi)=p, θ = π ​ θ 1 ​ π ¯ \theta=\pi\theta_{1}\overline{\pi}, and p ​ η = π ​ η 1 ​ π ¯ p\eta=\pi\eta_{1}\overline{\pi}.

###### Proof.

Again, write θ = π ​ θ 1 ​ π ¯ \theta=\pi\theta_{1}\overline{\pi}. Suppose first that π | η \pi\mid\eta, that is, η = π ​ η 2 \eta=\pi\eta_{2}, for some η 2 ∈ 𝔼 \eta_{2}\in\BE. Then p ​ η = π ⁡ ( η 2 ​ π) ​ π ¯ p\eta=\pi(\eta_{2}\pi)\overline{\pi}, and we are done in this case. So, we can assume that π \pi does not divide η \eta. Since θ \theta is pure, δ = θ ​ η = − θ ¯ ​ η \delta=\theta\eta=-\overline{\theta}\eta, and Lemma 2.6 shows that p p does not divide δ \delta. By Lemma 4.1 and the uniqueness part of Lemma 2.5, we have δ = π ​ δ 1 ​ π ¯ \delta=\pi\delta_{1}\overline{\pi}. Then π ​ θ 1 ​ π ¯ ​ η = δ = π ​ δ 1 ​ π ¯ \pi\theta_{1}\overline{\pi}\eta=\delta=\pi\delta_{1}\overline{\pi} implies that θ 1 ​ π ¯ ​ η ​ π = δ 1 ​ π ¯ ​ π = p ​ δ 1 \theta_{1}\overline{\pi}\eta\pi=\delta_{1}\overline{\pi}\pi=p\delta_{1}. Hence, p | π ¯ ​ η ​ π ¯ ​ θ 1 p\mid\overline{\overline{\pi}\eta\pi}\,\theta_{1}. Lemma 2.6 shows that either π ¯ | θ 1 \overline{\pi}\mid\theta_{1} or p | π ¯ ​ η ​ π p\mid\overline{\pi}\eta\pi. The first case is impossible because then θ \theta would be divisible by p p. If we let π ¯ ​ η ​ π = p ​ η 1 \overline{\pi}\eta\pi=p\eta_{1}, then p ​ η = π ​ η 1 ​ π ¯ p\eta=\pi\eta_{1}\overline{\pi}. ∎

###### Proposition 5.8.

Every pair ( θ, η) (\theta,\eta) of twins is parameterized by a pair ( α, z) ∈ 𝔼 × 𝔾 (\alpha,z)\in\BE\times\BG.

###### Proof.

Let M = N ⁡ ( θ) = N ⁡ ( η) M=\Norm(\theta)=\Norm(\eta). Consider all representations of the form θ = α ​ θ 1 ​ α ¯ \theta=\alpha\theta_{1}\overline{\alpha} and η = α ​ η 1 ​ α ¯ \eta=\alpha\eta_{1}\overline{\alpha}, where α, θ 1, η 1 ∈ 𝔼 \alpha,\theta_{1},\eta_{1}\in\BE. Clearly, θ 1 \theta_{1} and η 1 \eta_{1} are twins as well. There exists such a representation (with α = 1 \alpha=1), and so there is one with N ⁡ ( α) \Norm(\alpha) as large as possible. We present reductions to increase N ⁡ ( α) \Norm(\alpha).

If p p is a prime such that p 2 p^{2} divides both N ⁡ ( θ 1) \Norm(\theta_{1}) and N ⁡ ( η 1) \Norm(\eta_{1}), but p p divides neither θ 1 \theta_{1} nor η 1 \eta_{1}, then Lemma 5.6 allows us to replace α \alpha with α ​ π \alpha\pi. If this p p does not divide θ 1 \theta_{1} but divides η 1 \eta_{1}, then we write η 1 = p ℓ ​ η ′ \eta_{1}=p^{\ell}\eta^{\prime} such that η ′ \eta^{\prime} is not divisible by p p, and apply Lemma 5.7 to θ 1 \theta_{1} and η ′ \eta^{\prime}. We again obtain a suitable π \pi by using up a factor of p p out of p ℓ p^{\ell}.

If none of these reductions can be performed further, then θ 1 = d ​ θ 2 \theta_{1}=d\theta_{2} and η 1 = d ​ η 2 \eta_{1}=d\eta_{2}, for some d ∈ ℤ d\in\BZ such that N ⁡ ( θ 2) = N ⁡ ( η 2) \Norm(\theta_{2})=\Norm(\eta_{2}) is square-free. By Lemma 5.5, every integer prime divisor of N ⁡ ( η 2) \Norm(\eta_{2}) divides θ 2 ​ η 2 \theta_{2}\eta_{2}. Hence, the square-free integer N ⁡ ( η 2) \Norm(\eta_{2}) divides θ 2 ​ η 2 \theta_{2}\eta_{2}, whose norm is N ⁡ ( η 2) 2 \Norm(\eta_{2})^{2}. Therefore, θ 2 ​ η 2 = N ⁡ ( η 2) ​ ε \theta_{2}\eta_{2}=\Norm(\eta_{2})\varepsilon, where ε \varepsilon is a unit of 𝔼 \BE. We may assume ε = i \varepsilon=i, by the argument in the last paragraph of the proof of Theorem 4.2. Thus, η 2 = θ 2 ​ i \eta_{2}=\theta_{2}i, and as θ 2 \theta_{2} and η 2 \eta_{2} are pure quaternions, θ 2 = z 1 ​ j \theta_{2}=z_{1}j, for some z 1 ∈ 𝔾 z_{1}\in\BG. Then θ = α ⁡ ( d ​ z 1) ​ j ​ α ¯ \theta=\alpha(dz_{1})j\,\overline{\alpha} and η = α ⁡ ( d ​ z 1) ​ k ​ α ¯ \eta=\alpha(dz_{1})k\,\overline{\alpha}, proving the claim. ∎

###### Lemma 5.9.

Let ( α, z) ∈ ℍ × ℂ (\alpha,z)\in\BH\times\BC and suppose that z = s 2 ​ t z=s^{2}t, for some s, t ∈ ℂ s,t\in\BC. Then the pairs ( α, z) (\alpha,z) and ( α ​ s, t) (\alpha s,t) are equivalent.

###### Proof.

Since j ​ s ​ j − 1 = s ¯ jsj^{-1}=\overline{s} for every s ∈ ℂ s\in\BC, we have that z ​ j = s ​ t ​ j ​ s ¯ zj=stj\,\overline{s} and similarly, z ​ k = s ​ t ​ k ​ s ¯ zk=stk\,\overline{s}. Therefore, α ​ z ​ j ​ α ¯ = ( α ​ s) ​ t ​ j ​ ( α ​ s ¯) \alpha zj\,\overline{\alpha}=(\alpha s)tj(\overline{\alpha s}) and α ​ z ​ k ​ α ¯ = ( α ​ s) ​ t ​ k ​ ( α ​ s ¯) \alpha zk\,\overline{\alpha}=(\alpha s)tk(\overline{\alpha s}). ∎

This lemma immediately implies ( 2) (2) of Theorem 5.4 ( ( 1) (1) has been proven in Proposition 5.8). We now proceed to prove ( 3) (3). If a suitable ρ \rho in ( 3) (3) exists, then ( α 1, z 1) (\alpha_{1},z_{1}) is equivalent to ( α 1 ​ ρ, z 2) = ( α 2, z 2) (\alpha_{1}\rho,z_{2})=(\alpha_{2},z_{2}), by Lemma 5.9. We now only have to prove that if ( α 1, z 1) (\alpha_{1},z_{1}) and ( α 2, z 2) (\alpha_{2},z_{2}) are equivalent pairs in 𝔼 × 𝔾 \BE\times\BG, then a suitable ρ \rho exists.

Choose elements s r ∈ ℂ s_{r}\in\BC satisfying s r 2 = z r s_{r}^{2}=z_{r}. Lemma 5.9 shows that ( α r, z r) (\alpha_{r},z_{r}) is equivalent to ( α r ​ s r, 1) (\alpha_{r}s_{r},1). From ( α 1 ​ s 1) ​ j ​ ( α 1 ​ s 1 ¯) = ( α 2 ​ s 2) ​ j ​ ( α 2 ​ s 2 ¯) (\alpha_{1}s_{1})j(\overline{\alpha_{1}s_{1}})=(\alpha_{2}s_{2})j(\overline{\alpha_{2}s_{2}}), we get that ( α 2 ​ s 2) − 1 ​ ( α 1 ​ s 1) (\alpha_{2}s_{2})^{-1}(\alpha_{1}s_{1}) centralizes j j (as well as k k, by the same calculation). Since the elements of ℍ \BH centralizing both j j and k k are exactly the real numbers, we get that t = ( α 2 ​ s 2) − 1 ​ ( α 1 ​ s 1) t=(\alpha_{2}s_{2})^{-1}(\alpha_{1}s_{1}) is contained in ℝ \BR. This can be written as t ​ α 1 − 1 ​ α 2 = s 1 ​ s 2 − 1 t\alpha_{1}^{-1}\alpha_{2}=s_{1}s_{2}^{-1}. From ( α 1 ​ s 1) ​ j ​ ( α 1 ​ s 1 ¯) = ( α 2 ​ s 2) ​ j ​ ( α 2 ​ s 2 ¯) (\alpha_{1}s_{1})j(\overline{\alpha_{1}s_{1}})=(\alpha_{2}s_{2})j(\overline{\alpha_{2}s_{2}}), we get that N ⁡ ( α 1) 2 ​ N ​ ( s 1) 2 = N ⁡ ( α 2) 2 ​ N ​ ( s 2) 2 \Norm(\alpha_{1})^{2}\Norm(s_{1})^{2}=\Norm(\alpha_{2})^{2}\Norm(s_{2})^{2}. Hence N ⁡ ( t) = 1 \Norm(t)=1, and t = ± 1 t=\pm 1.

This implies that α 1 − 1 ​ α 2 = ρ \alpha_{1}^{-1}\alpha_{2}=\rho is a complex number with rational components, and ρ 2 = ( s 1 ​ s 2 − 1) 2 = z 1 ​ z 2 − 1 \rho^{2}=(s_{1}s_{2}^{-1})^{2}=z_{1}z_{2}^{-1}. Therefore, z 1 ​ z 2 = ( ρ ​ z 2) 2 z_{1}z_{2}=(\rho z_{2})^{2}. The ring of Gaussian integers is integrally closed in the field of Gaussian numbers, so ρ ​ z 2 ∈ 𝔾 \rho z_{2}\in\BG. Since z 1 z_{1} and z 2 z_{2} are square-free, each Gaussian prime divisor of z 1 z_{1} has multiplicity 1 1 in both z 1 z_{1} and z 2 z_{2}, with the same holding for z 2 z_{2}. We see that z 1 z_{1} and z 2 z_{2} are associates, and ρ 2 \rho^{2} is a unit in 𝔾 \BG. Thus, ρ \rho is a unit in 𝔾 \BG, establishing ( 3) (3) of Theorem 5.4.

Finally, we prove ( 4) (4). Suppose that ( α, z) (\alpha,z) parameterizes the twin pair ( θ, η) (\theta,\eta). Then N ⁡ ( θ) = N ⁡ ( α) 2 ​ N ⁡ ( z) \Norm(\theta)=\Norm(\alpha)^{2}\Norm(z) is a square if and only if N ⁡ ( z) \Norm(z) is a square. Clearly, if z ∈ ℤ z\in\BZ or i ​ z ∈ ℤ iz\in\BZ, then N ⁡ ( z) \Norm(z) is a square.

Suppose that N ⁡ ( z) \Norm(z) is a square and consider a Gaussian prime divisor π \pi of z z. As z z is square-free in 𝔾 \BG, the number π 2 \pi^{2} does not divide z z. We show that π = 1 + i \pi=1+i is impossible. Indeed, all other Gaussian primes have odd norm, so N ⁡ ( z) \Norm(z) would have to be of the form 4 ​ k + 2 4k+2, which cannot be the square of an integer. Similarly, if p = N ⁡ ( π) p=\Norm(\pi) is an odd prime (of the from 4 ​ k + 1 4k+1), then p | N ⁡ ( z) p\mid\Norm(z), and so the conjugate of π \pi must also be a factor of z z. Therefore, z z is indeed either real or pure imaginary, and the proof of Theorem 5.4 is complete.∎

###### Theorem 5.10.

For a positive integer M M, denote by T ⁡ ( M) \Twin(M) the number of twin pairs ( θ, η) (\theta,\eta) such that N ⁡ ( θ) = N ⁡ ( η) = M \Norm(\theta)=\Norm(\eta)=M, and let σ ⁡ ( s) \sigma(s) be the sum of positive integer divisors of any integer s s. Suppose that

 | M = 2 κ ​ p 1 λ 1 ​ … ​ p m λ m ​ q 1 μ 1 ​ … ​ q ℓ μ ℓ, M=2^{\kappa}p_{1}^{\lambda_{1}}\ldots p_{m}^{\lambda_{m}}q_{1}^{\mu_{1}}\ldots q_{\ell}^{\mu_{\ell}}\,, |  |

where p 1, …, p m p_{1},\ldots,p_{m} are primes ≡ 1 ​ ( 4) \equiv 1~(4) and q 1, …, q ℓ q_{1},\ldots,q_{\ell} are primes ≡ − 1 ​ ( 4) \equiv-1~(4). We assume that all λ r \lambda_{r} and μ s \mu_{s} are positive. Then

 | T ⁡ ( M) = 24 ​ ∏ r = 1 m g ⁡ ( p r λ r) ​ ∏ s = 1 ℓ h ⁡ ( q s μ s), \Twin(M)=24\prod_{r=1}^{m}g(p_{r}^{\lambda_{r}})\prod_{s=1}^{\ell}h(q_{s}^{\mu_{s}})\,, |  |

where

 | g ⁡ ( p 2 ​ λ) = σ ⁡ ( p λ) + σ ⁡ ( p λ − 1), g ⁡ ( p 2 ​ λ + 1) = 2 ​ σ ​ ( p λ), g(p^{2\lambda})=\sigma(p^{\lambda})+\sigma(p^{\lambda-1})\,,\qquad g(p^{2\lambda+1})=2\sigma(p^{\lambda})\,, |  |

and

 | h ⁡ ( q 2 ​ μ) = σ ⁡ ( q μ) + σ ⁡ ( q μ − 1), h ⁡ ( q 2 ​ μ + 1) = 0. h(q^{2\mu})=\sigma(q^{\mu})+\sigma(q^{\mu-1})\,,\qquad h(q^{2\mu+1})=0\,. |  |

In particular, T ⁡ ( M) / 24 \Twin(M)/24 is a multiplicative function. If there exists a twin pair with norm M M, then M M is the sum of two squares.

###### Proof.

By Theorem 5.4, we have to count the number of pairs ( α, z) ∈ 𝔼 × 𝔾 (\alpha,z)\in\BE\times\BG, where M = N ⁡ ( α) 2 ​ N ⁡ ( z) M=\Norm(\alpha)^{2}\Norm(z) and z z is square-free in 𝔾 \BG, and divide the number of solutions by 4 4 due to ( 3) (3).

Writing z z as a product of Gaussian primes, we see that in the canonical form of N ⁡ ( z) \Norm(z) every prime of the form 4 ​ k + 3 4k+3 has exponent 2 2, every prime of the form 4 ​ k + 1 4k+1 has exponent 2 2 or 1 1, and the prime 2 2 has exponent 1 1 (or 0 0). If such a number t = N ⁡ ( z) t=\Norm(z) is given, then the only freedom in determining z z occurs at the primes p p of the form 4 ​ k + 1 4k+1. Indeed, p = π 1 ​ π 1 ¯ p=\pi_{1}\overline{\pi_{1}} is a product of two Gaussian primes, and if the exponent of p p in N ⁡ ( z) \Norm(z) is 1 1, then we can decide whether to put π \pi or π ¯ \overline{\pi} into z z. We have to multiply the resulting z z with the four Gaussian units. Thus, if 4 ​ f ​ ( t) 4f(t) denotes the number of solutions for z z with norm t t, then f f is a multiplicative function, which is 1 1 or 0 0 for every prime power, except that f ⁡ ( p 1) = 2 f(p^{1})=2 when p ≡ 1 ​ ( 4) p\equiv 1~(4).

Corollary 2.8 allows us to count the number of integral quaternions α \alpha with given norm N ⁡ ( α) \Norm(\alpha). The result is 24 24 times a multiplicative function (the sum of odd divisors of N ⁡ ( α) \Norm(\alpha)). We now go through all primes in the decomposition of M M to see how we can split M M into N ⁡ ( α) 2 ​ N ⁡ ( z) \Norm(\alpha)^{2}\Norm(z).

If the prime is 2 2, then we must put 2 κ 2^{\kappa} into N ⁡ ( α) 2 \Norm(\alpha)^{2} when κ \kappa is even, and must put 2 κ − 1 2^{\kappa-1} into N ⁡ ( α) 2 \Norm(\alpha)^{2} when κ \kappa is odd. By Corollary 2.8, we see that T ⁡ ( 2 κ) = 24 \Twin(2^{\kappa})=24, and T ⁡ ( M) \Twin(M) does not depend on κ \kappa.

Next, we consider a prime q r ≡ − 1 ​ ( 4) q_{r}\equiv-1~(4). In this case, μ r \mu_{r} must be even for a solution to exist, and we can either put the entire q r μ r q_{r}^{\mu_{r}} into N ⁡ ( α) 2 \Norm(\alpha)^{2} or put q r μ r − 2 q_{r}^{\mu_{r}-2} into N ⁡ ( α) 2 \Norm(\alpha)^{2} and q r q_{r} into z z. This proves the formula in the theorem for h h.

Finally, for p r ≡ 1 ​ ( 4) p_{r}\equiv 1~(4) there are two cases to consider. If λ r \lambda_{r} is even, then we can put 0 0 or 2 2 copies of p r p_{r} into N ⁡ ( z) \Norm(z). If λ r \lambda_{r} is odd, then we must put 1 1 copy of p r p_{r} into N ⁡ ( z) \Norm(z) (and the corresponding Gaussian primes in z z can be chosen in 2 2 ways). This proves the formula for g g.

Since we can put together the solutions for M M from the solutions for the prime divisors of M M independently, we get the formula in the theorem. ∎

###### Corollary 5.11.

Let ( v, w) (v,w) be a pair of twins in ℤ 3 \BZ^{3} whose length is an integer. Then there exists an α ∈ 𝔼 \alpha\in\BE and an integer d d such that the last two columns of d ​ E ​ ( α) dE(\alpha) are either ( v, w) (v,w) or ( − w, v) (-w,v). Therefore, ( v, w) (v,w) can be extended to an icube.

###### Proof.

Let ( V ⁡ ( v), V ⁡ ( w)) = ( θ, η) \big(V(v),V(w)\big)=(\theta,\eta) be parameterized by ( α, z) (\alpha,z), where z z is square-free. By ( 4) (4) of Theorem 5.4, z z is either real or pure imaginary, so z = d z=d or z = d ​ i z=di for some integer d d. In the first case, θ = d ​ α ​ j ​ α ¯ \theta=d\alpha j\,\overline{\alpha} and η = d ​ α ​ k ​ α ¯ \eta=d\alpha k\,\overline{\alpha}, so the last two columns of d ​ E ​ ( α) dE(\alpha) are v v and w w. In the second case, θ = d ​ α ​ k ​ α ¯ \theta=d\alpha k\,\overline{\alpha} and η = − d ​ α ​ j ​ α ¯ \eta=-d\alpha j\,\overline{\alpha}, so the last two columns of d ​ E ​ ( α) dE(\alpha) are − w -w and v v. ∎

###### Corollary 5.12.

If ( u, v, w) (u,v,w) is an icube, then there is an α ∈ 𝔼 \alpha\in\BE and d ∈ ℤ d\in\BZ such that ( u, v, w) (u,v,w) and d ​ E ​ ( α) dE(\alpha) can be obtained from each other by permuting and changing the signs of certain columns.

###### Proof.

By Proposition 1.3, the edge length is an integer. Let α \alpha and d d be given by Corollary 5.11. Then the columns of d ​ E ​ ( α) dE(\alpha) and ( ± u, ± v, ± w) (\pm u,\pm v,\pm w) share two orthogonal vectors, and so they share the third column of E ⁡ ( α) E(\alpha) as well. ∎

###### Lemma 5.13.

Suppose that α ∈ 𝔼 \alpha\in\BE, z z is a square-free Gaussian integer and θ = α ​ z ​ j ​ α ¯ \theta=\alpha zj\,\overline{\alpha} is primitive. Then N ⁡ ( z) \Norm(z) is the square-free part of N ⁡ ( θ) \Norm(\theta).

###### Proof.

As N ⁡ ( θ) = N ⁡ ( α) 2 ​ N ⁡ ( z) \Norm(\theta)=\Norm(\alpha)^{2}\Norm(z), it is sufficient to prove that N ⁡ ( z) \Norm(z) is square-free. Suppose that p 2 | N ⁡ ( z) p^{2}\mid\Norm(z), for a prime 0 < p ∈ ℤ 0<p\in\BZ. If p ≡ 3 ​ ( 4) p\equiv 3~(4), then p p is a Gaussian prime, so p | z p\mid z, contradicting the fact that θ \theta is primitive. If p = 2 p=2, then 2 | z 2\mid z, a contradiction. Finally, if p = π ​ π ¯ p=\pi\overline{\pi}, for some Gaussian prime π \pi, then π \pi and π ¯ \overline{\pi} cannot both divide z z, because then p p would divide the primitive θ \theta. On the other hand, the exponent of π \pi and π ¯ \overline{\pi} is at most 1 1 in z z, since z z is square-free. Therefore, N ⁡ ( z) \Norm(z) cannot be divisible by p 2 p^{2}, a contradiction. ∎

###### Proof of Theorem 1.5.

We have proved the existence statement in Remark 4.3. Suppose that x x is primitive. If ( u, v, w) (u,v,w) is an icube with edge length m m such that x = a ​ u + b ​ v + c ​ w x=au+bv+cw, then ( u, v, w) (u,v,w) is also primitive. Therefore, by Corollary 5.12 (or by Corollary 3.9), we may assume that ( u, v, w) = E ⁡ ( α) (u,v,w)=E(\alpha), for some α ∈ 𝔼 \alpha\in\BE. Thus, it is sufficient to deal with “Eulerian” cubic lattices.

Suppose that x x is contained in two such sublattices: V ⁡ ( x) = α 1 ​ β 1 ​ α 1 ¯ = α 2 ​ β 2 ​ α 2 ¯ V(x)=\alpha_{1}\beta_{1}\,\overline{\alpha_{1}}=\alpha_{2}\beta_{2}\,\overline{\alpha_{2}}. By the uniqueness part of Theorem 4.2, there exists a unit ε ∈ 𝔼 \varepsilon\in\BE such that α 2 = α 1 ​ ε − 1 \alpha_{2}=\alpha_{1}\varepsilon^{-1}, and β 2 \beta_{2}, β 1 \beta_{1} are group-conjugates via ε \varepsilon. Propositions 3.1 and 3.2 show that the matrices E ⁡ ( α 1) E(\alpha_{1}) and E ⁡ ( α 2) E(\alpha_{2}) may differ only by permutations and sign changes of columns. Therefore, the two cubic lattices are actually the same, proving the uniqueness part of the theorem. ∎

###### Proof of Corollary 1.6.

Using the notation of the previous proof, let L L denote the unique sublattice obtained there. Proposition 3.2 shows that β 1 \beta_{1} and β 2 \beta_{2} have the same number of zero components. Therefore, when considering the three cases of Corollary 1.6 (which are distinguished by the number of zero components of x x relative to L L), it does not matter which generating α \alpha we choose for L L.

We now show that every twin of x x is contained in L L. Let η 1 \eta_{1} be a twin of θ = V ⁡ ( x) \theta=V(x), and let ( α 1, z 1) (\alpha_{1},z_{1}) parameterize the pair ( θ, η 1) (\theta,\eta_{1}), with z 1 z_{1} square-free. By Lemma 5.13, N ⁡ ( z 1) = n \Norm(z_{1})=n, and so N ⁡ ( α 1) = m \Norm(\alpha_{1})=m. Thus, the sublattice generated by α 1 \alpha_{1} is L L. Since z 1 ​ j z_{1}j has a zero component, by case ( 1) (1) of Corollary 1.6, the vector x x cannot have a twin.

If the norm of x x is a square, then 1 = n = N ⁡ ( z 1) 1=n=\Norm(z_{1}), and z 1 ∈ { ± 1, ± i } z_{1}\in\{\pm 1,\pm i\}. Thus, x x and each of its twins has exactly one nonzero component relative to L L. Therefore, x x has exactly 4 4 twins. Conversely, if x x has only one nonzero component relative to L L, then its length is obviously an integer, since the same holds for the generating vectors of L L. Hence, ( 3) (3) is proved.

Finally, suppose that none of the components of z 1 z_{1} is zero (so x x has exactly one zero component). Let η 2 \eta_{2} be another twin of θ \theta, parameterized by ( α 2, z 2) (\alpha_{2},z_{2}). Again, α 2 = α 1 ​ ε − 1 \alpha_{2}=\alpha_{1}\varepsilon^{-1} and ε ​ z 1 ​ j ​ ε − 1 = z 2 ​ j \varepsilon z_{1}j\varepsilon^{-1}=z_{2}j, for some unit ε \varepsilon; however, not every unit ε \varepsilon yields a twin of θ \theta. Indeed, if ε ∉ Q = { ± 1, ± i, ± j, ± k } \varepsilon\notin Q=\{\pm 1,\pm i,\pm j,\pm k\}, then Proposition 3.2 shows that group-conjugation by ε \varepsilon induces a fixed point free permutation on the components of the vectors (while possibly changing some signs). We know that the first component of z 1 ​ j z_{1}j and of z 2 ​ j z_{2}j is zero. Therefore, ε ∉ Q \varepsilon\notin Q can happen only if z 1 ​ j z_{1}j and z 2 ​ j z_{2}j have two nonzero components, which we have excluded. Thus, ε ∈ Q \varepsilon\in Q. The two twins of θ \theta in question are η 1 = α 1 ​ z 1 ​ k ​ α 1 ¯ \eta_{1}=\alpha_{1}z_{1}k\,\overline{\alpha_{1}} and

 | η 2 = α 2 ​ z 2 ​ k ​ α 2 ¯ = − α 1 ​ z 1 ​ ( j ​ ε − 1 ​ i ​ ε) ​ α 1 ¯. \eta_{2}=\alpha_{2}z_{2}k\,\overline{\alpha_{2}}=-\alpha_{1}z_{1}(j\varepsilon^{-1}i\varepsilon)\overline{\alpha_{1}}\,. |  |

Let us calculate this now.

If ε ∈ { ± 1, ± i } \varepsilon\in\{\pm 1,\pm i\}, then η 2 = η 1 \eta_{2}=\eta_{1}. (This has been noted in ( 3) (3) of Theorem 5.4.)

If ε ∈ { ± j, ± k } \varepsilon\in\{\pm j,\pm k\}, then η 2 = − η 1 \eta_{2}=-\eta_{1} (This is always obviously another twin of θ \theta.)

Thus, if x x has two nonzero components relative to L L, then it has no more than two twins, completing the proof of Corollary 1.6. ∎

## 6. Twin-complete numbers

In this section we first prove the characterization of twin-complete numbers given in Theorem 1.8 and then discuss Conjecture 1.9.

###### Lemma 6.1.

If 4 ​ n 4n is twin-complete, then so is n n.

###### Proof.

Every pure quaternion whose norm is divisible by 4 4 is divisible by 2 2. This follows by looking at the coefficients mod 4 4 (or from Theorem 4.6). Thus, if N ⁡ ( θ) = n \Norm(\theta)=n, then 2 ​ θ 2\theta has a twin η \eta, and so η / 2 \eta/2 is a twin of θ \theta. ∎

###### Lemma 6.2.

Let β ∈ 𝔼 \beta\in\BE be a primitive pure quaternion and m > 0 m>0 an odd positive integer. Then there exists an α ∈ 𝔼 \alpha\in\BE with norm m m such that α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is primitive.

###### Proof.

It is sufficient to prove this when m m is a prime, since we can go through the prime divisors of m m one by one. Clearly (or by Theorem 4.6), α ​ β ​ α ¯ \alpha\beta\,\overline{\alpha} is primitive if and only if it is not divisible by p = m p=m. By Proposition 4.7, there is such an α \alpha (we have actually counted them). ∎

###### Proof of Theorem 1.8.

Let n, m > 0 n,m>0 be integers, with n n square-free. Suppose that n n is twin-complete. It is sufficient to prove that every primitive vector δ \delta with norm n ​ m 2 nm^{2} has a twin (since we can do induction on m m). By Theorem 4.2, δ = α ​ β ​ α ¯ \delta=\alpha\beta\,\overline{\alpha}, for some α, β ∈ 𝔼 \alpha,\beta\in\BE such that N ⁡ ( α) = m \Norm(\alpha)=m and N ⁡ ( β) = n \Norm(\beta)=n. Since n n is twin-complete, β \beta has a twin γ \gamma. We show that α ​ γ ​ α ¯ \alpha\gamma\,\overline{\alpha} is a twin of δ \delta, using Proposition 5.1. Indeed,

 | δ ​ α ​ γ ​ α ¯ = α ​ β ​ ( α ¯ ​ α) ​ γ ​ α ¯ = m ​ α ​ β ​ γ ​ α ¯. \delta\alpha\gamma\,\overline{\alpha}=\alpha\beta(\overline{\alpha}\alpha)\gamma\,\overline{\alpha}=m\alpha\beta\gamma\overline{\alpha}\,. |  |

This is a pure quaternion, since β ​ γ \beta\gamma is a pure quaternion. This proves one direction of the theorem.

For the converse, suppose that n > 0 n>0 is square-free and n ​ m 2 nm^{2} is twin-complete. Then every vector β \beta with norm n n is primitive. By Lemma 6.1, we may assume that m m is odd. For any given β \beta, Lemma 6.2 yields an α \alpha with norm m m such that θ = α ​ β ​ α ¯ \theta=\alpha\beta\,\overline{\alpha} is primitive. Since n ​ m 2 nm^{2} is twin-complete, θ \theta has a twin. By Theorem 5.4, this pair of twins can be parameterized by some ( α 1, z) ∈ 𝔼 × 𝔾 (\alpha_{1},z)\in\BE\times\BG such that z z is square-free. Thus, θ = α 1 ​ z ​ j ​ α 1 ¯ \theta=\alpha_{1}zj\,\overline{\alpha_{1}}, and by Lemma 5.13, N ⁡ ( z) \Norm(z) is the square-free part of N ⁡ ( θ) \Norm(\theta), that is, N ⁡ ( z) = n \Norm(z)=n and N ⁡ ( α 1) = m \Norm(\alpha_{1})=m. By the uniqueness statement of Theorem 4.2, we get that β = ε ​ z ​ j ​ ε − 1 \beta=\varepsilon zj\varepsilon^{-1}, for some unit ε ∈ 𝔼 \varepsilon\in\BE, but then ε ​ z ​ k ​ ε − 1 \varepsilon zk\varepsilon^{-1} is a twin of β \beta. Hence, n n is twin-complete.

To prove the last statement of the theorem, let n n be square-free. Clearly, ( a, b, 0) (a,b,0) and ( − b, a, 0) (-b,a,0) are twins, so if n n is not the sum of three positive squares, but is the sum of two squares, then it is twin-complete. Conversely, suppose that n n is twin-complete. Let β \beta be a pure quaternion of norm n n, we have to show that at least one of the three coordinates of the corresponding vector is zero. As n n is twin-complete, β \beta has a twin, so Theorem 5.4 implies that β = α ​ z ​ j ​ α ¯ \beta=\alpha zj\,\overline{\alpha}, for some ( α, z) ∈ 𝔼 × 𝔾 (\alpha,z)\in\BE\times\BG. Here n = N ⁡ ( β) = N ⁡ ( α) 2 ​ N ⁡ ( z) n=\Norm(\beta)=\Norm(\alpha)^{2}\Norm(z), so N ⁡ ( α) = 1 \Norm(\alpha)=1 and α \alpha is a unit. From Proposition 3.2, we get that at least one component of β \beta is zero (since this is the case with z ​ j zj). ∎

Now we discuss Conjecture 1.9. Let

 | S ⊇ { 1, 2, 5, 10, 13, 37, 58, 85, 130 } S\supseteq\{1,2,5,10,13,37,58,85,130\} |  |

denote the list of those square-free numbers that can be written as a sum of two squares, but not as a sum of three positive squares. It has been known since [GCC59] that this list is finite, and if the conjecture fails, there is at most one number in S S not listed above ( [Wei73], [Gro85]).

In [Mor60], it is shown that for an integer n ∈ S n\in S, the only nonnegative solutions of

 | x ​ y + y ​ z + z ​ x = n xy+yz+zx=n |  |

when n ≡ 2 ​ ( 4) n\equiv 2~(4) are given by x ​ y ​ z = 0 xyz=0, and when n ≡ 1 ​ ( 4) n\equiv 1~(4) are given by either x ​ y ​ z = 0 xyz=0 or x = d x=d, y = d y=d, z = ( n − d 2) / 2 ​ d z=(n-d^{2})/2d, where d d is any divisor of n n with d 2 < n d^{2}<n. Either way, for such numbers n n the above equation has no solution with three distinct positive integers x, y, z x,\,y,\,z.

This characterization of the numbers in S S allows us to see the relationship they bear with Euler’s *numeri idonei*. Euler defined a *numerus idoneus*to be an integer N N such that, for any positive integer m m, if

 | m = x 2 ± N y 2, ( x 2, N y 2) = 1, x, y ≥ 0 m=x^{2}\pm Ny^{2},\quad(x^{2},Ny^{2})=1,\quad x,y\geq 0 |  |

has a unique solution, then m m is of the form 2 a ​ p k 2^{a}p^{k}, a ∈ { 0, 1 } a\in\{0,1\}, k ≥ 1 k\geq 1, p p is a prime.

Euler was aware of 65 numeri idonei, and it is widely believed and conjectured that this list is complete ( [Rib00]). S. Chowla proved in [Cho34] that there are only finitely many numeri idonei, and P. J. Weinberger improved this result by showing that there can be at most one more square-free idoneal number, and, if it exists, it must be greater than 2 ⋅ 10 11 2\cdot 10^{11} ( [Wei73]). If there is indeed another square-free idoneal number N N, and it is even, then 4 ​ N 4N is also idoneal. On the other hand, if N > 1848 N>1848 is idoneal and not square-free, then N / 4 N/4 is both square-free and idoneal ( [Kan09]). Thus, there are at most 67 idoneal numbers.

Using Theorem 3.22 of [Cox89] it can be shown that an integer N N is a *numerus idoneus*if and only if it cannot be expressed as x ​ y + y ​ z + z ​ x xy+yz+zx with 0 < x < y < z 0<x<y<z. Combining this with the characterization by [Mor60] described above, we see that every integer in S S is also one of Euler’s *numeri idonei*. Checking Euler’s list of the 65 65*numeri idonei*(the greatest of which is only 1848 1848) against the properties listed in Conjecture 1.9, one sees that, indeed, Conjecture 1.9 is true if Euler’s list is complete.

If we only consider those integers n n for which there is no representation of the form x ​ y + y ​ z + z ​ x xy+yz+zx with 1 ≤ x ≤ y ≤ z 1\leq x\leq y\leq z, i.e., the even, square-free, twin-complete numbers, then we have from [BC00] that such an n n can only be absent from the list of Conjecture 1.9 if the Generalized Riemann Hypothesis fails.

## References

- [BC00] J. Borwein, K. K. S. Choi, *On the representations of x ​ y + y ​ z + z ​ x xy+yz+zx*, Exp. Math. 9 (2000), 153–158.
- [Car15] R. D. Carmichael, *Diophantine analysis*, John Wiley & Sons, 1915.
- [Cho34] S. Chowla, *An extension of Heilbronn’s class number theorem*, Quart. J. Math. Oxford 5 (1934), 304–307.
- [CS03] J. H. Conway, D. A. Smith, *On Quaternions and Octonions: Their Geometry, Arithmetic and Symmetry*, A K Peters, 2003.
- [Cox89] D. A. Cox, *Primes of the form x 2 + n ​ y 2 x^{2}+ny^{2}*, New York: John Wiley & Sons, 1989.
- [GCC59] E. Grosswald, A. Calloway, J. Calloway, *The representation of integers by three positive squares*, Proc. Amer. Math. Soc. 10 (1959), 451–455.
- [Gro85] E. Grosswald, *Representations of integers as sums of squares*, New York: Springer-Verlag, 1985.
- [HW79] G. H. Hardy, E. M. Wright, *An introduction to the theory of numbers, 5th Ed.*, Oxford: Clarendon Press, 1979.
- [H19] A. Hurwitz, *Vorlesungen über die Zahlentheorie der Quaternionen*, Berlin, 1919.
- [Kan09] E. Kani, *Idoneal numbers and some generalizations*, preprint (2009), available at http://www.mast.queensu.ca/ ∼ \mathtt{\sim} kani/papers/idoneal.pdf
- [Mor60] L. J. Mordell, *The representation of integers by three positive squares*, Mich. Math. J. 7 (1960), 289–290.
- [Pal40] G. Pall, *On the arithmetic of quaternions*, Tran. Amer. Math. Soc. 47 (1940), 487–500.
- [Rib00] P. Ribenboim, *My numbers, my friends.*Popular Lectures on Number Theory. Springer-Verlag, Berlin-Heidelberg, 2000.
- [Sar61] A. Sárközy, *On lattice-cubes in the three-space*(in Hungarian), Matematikai Lapok, 1961.
- [Wei73] P. J. Weinberger, *Exponents of the class groups of complex quadratic fields*, Acta Arith. 22 (1973), 117–124.

[◄][5][image: ar5iv homepage] [6]
[Feeling lucky?][7] [8]
[Conversion report][9]
[Report an issue][10]
[View original on arXiv][11] [►][12]


## Links

[1]: mailto:goswick@amadeus.math.uab.edu
[2]: mailto:ewkiss@math.elte.hu
[3]: mailto:mg@math.elte.hu
[4]: mailto:simanyi@math.uab.edu
[5]: /html/0806.3942
[6]: /
[7]: /feeling_lucky
[8]: /land_of_honey_and_milk
[9]: /log/0806.3943
[10]: https://github.com/dginev/ar5iv/issues/new?template=improve-article--arxiv-id-.md&title=Improve+article+0806.3943
[11]: https://arxiv.org/abs/0806.3943
[12]: /html/0806.3944
