"""Deeper structural probe on PE591 n=1e13 data.

A) Chain closure of the m^2-scaling law: within a square-class chain
   {d0, 4 d0, 9 d0, ...} verify that when m1*m2*d0 is in range,
   b_{m1 m2 d0} == (b_{d0}) / (m1 m2) whenever |a| stays equal all the way,
   i.e. the scaling is transitive.

B) Equal-|a| groups: list all groups of d sharing the same |a|, and for each
   check the explanation (scaling chain vs coincidence).  Find the "base" d0
   (smallest) of each group and the multipliers.

C) For each equal-|a| group, check b_d * sqrt(d) is approximately constant
   (that's what yields equal |a|), and check whether the base d0 is squarefree.
"""
import math
from collections import defaultdict

rows = {}
with open("results_full_bothsides.txt") as f:
    for line in f:
        p = line.split()
        if len(p) == 4 and p[0].isdigit():
            rows[int(p[0])] = (int(p[1]), int(p[2]), int(p[3]))
nonsq = [d for d in range(2,100) if int(math.isqrt(d))**2 != d]

# ---- B) equal-|a| groups ----
groups = defaultdict(list)
for d in nonsq:
    groups[rows[d][2]].append(d)
multi = {aa: ds for aa, ds in groups.items() if len(ds) > 1}
print("== Equal-|a| groups (size>=2):", len(multi), "groups,", sum(len(v) for v in multi.values()), "d's ==")
for aa in sorted(multi):
    ds = sorted(multi[aa])
    # find base = smallest nonsquare member with squarefree kernel giving all
    print(f"  |a|={aa}: {ds}")

# ---- A) chain check: for each chain generated by squarefree base ----
def squarefree_kernel(d):
    k = 1
    for p in range(2, int(math.isqrt(d))+1):
        if p*p > d: break
        while d % (p*p) == 0:
            d //= p*p
    return d

print("\n== Chains (squarefree base -> its square multiples in range) ==")
seen = set()
for d in nonsq:
    base = squarefree_kernel(d)
    if base in seen: continue
    chain = [x for x in nonsq if squarefree_kernel(x) == base]
    seen.add(base)
    if len(chain) > 1:
        chain.sort()
        b0 = abs(rows[chain[0]][0]); a0 = rows[chain[0]][2]
        line = f"  base d0={chain[0]} (sqfree kernel {base}) chain={chain}"
        # check |a| equality and b = b0/m
        eqs = all(rows[x][2] == a0 for x in chain)
        detail = []
        for x in chain[1:]:
            m = int(math.isqrt(x // chain[0]))
            # must be perfect square ratio
            exp = abs(rows[x][0]) == b0 // m if b0 % m == 0 else False
            detail.append(f"{x}(m={m},b_ok={exp})")
        print(line, "| all |a| equal:", eqs, " |", " ".join(detail))
