"""Analyze the 56 minimality exceptions of the subgroup criterion.

For each exception: e' < e with -n*x_{e'} in the subgroup generated by primes
of n*x_{e'} mod d' (=4e'+3), yet no split at x_{e'} exists (brute force says
so).  Print the residues/generators to see whether the obstruction is the
u <= nx cutoff.
"""
import json
from sympy import factorint
from fractions import Fraction
from sympy import divisors

rows = json.load(open('code/out/extended_minimal_x.json'))['rows']
QNR7 = {3,5,6}

def two_term(n, x):
    d = 4 * x - n
    if d <= 0:
        return None
    nx = n * x
    M = nx * nx
    for u in divisors(M):
        if u > nx:
            continue
        if (nx + u) % d != 0:
            continue
        v = M // u
        if (nx + v) % d != 0:
            continue
        y, z = (nx + u) // d, (nx + v) // d
        if y >= 1 and z >= 1 and Fraction(1, x) + Fraction(1, y) + Fraction(1, z) == Fraction(4, n):
            return (y, z)
    return None

def gen(n, e):
    """-n*x_e residues reachable as divisor classes mod d (subgroup members) with u<=nx info."""
    d = 4*e + 3
    x = (n + 4*e + 3)//4
    nx = n*x
    M = nx*nx
    # enumerate all divisors u, collect their classes modulo d and whether u <= nx,
    # and whether the complementary v = M/u is <= nx
    from collections import defaultdict
    classes = defaultdict(list)
    for u in divisors(M):
        if u <= nx:
            classes[u % d].append(('u<=nx', u))
            # also the class of v=M/u, since a split uses either u or v as the small one
            classes[(M//u) % d].append(('v', M//u))
    return classes

def subgroup(n, e):
    d = 4*e+3
    x = (n+4*e+3)//4
    nx = n*x
    target = (-nx) % d
    gens = {q % d for q in factorint(nx)}
    sub = {1}; frontier = {1}
    while frontier:
        nxt = set()
        for a in frontier:
            for g in gens:
                b = (a*g) % d
                if b not in sub:
                    sub.add(b); nxt.add(b)
        frontier = nxt
    return target in sub, target, d, sorted(gens)

# re-derive exceptions
exceptions = []
for row in rows:
    n, e = row['n'], row['excess']
    for ep in range(e):
        if gen is None:
            continue
        in_sub, target, d, gens = subgroup(n, ep)
        if in_sub and two_term(n, (n + 4*ep + 3)//4) is None:
            exceptions.append((row['k'], row['r'], n, e, ep, d, target, gens))
print(f"total exceptions: {len(exceptions)}")
print("k  r      n       e  e' d  target gens")
for ex in exceptions[:40]:
    k, r, n, e, ep, d, target, gens = ex
    # is target reachable with u <= nx?
    cls = gen(n, ep)
    reach_small = target in cls and any(t[0]=='u<=nx' for t in cls[target])
    print(f"{k:<3} {r:<4} {n:<7} {e}  {ep}  {d:<2} {target:<2} gens={gens} reachable_u<=nx={reach_small}")

# how many exceptions per class
from collections import Counter
print(Counter(ex[1] for ex in exceptions))
print(Counter(ex[3] for ex in exceptions))