"""Exact validation of the subgroup-membership characterization of minimal excess.

For n = 4m+1 (all six open classes) and a candidate x_e = (n + 4e + 3)/4,
d = 4e + 3 = 4x_e - n.  A split d/(n x_e) = 1/y + 1/z exists iff there is a
divisor u of (n x_e)^2 with
    u == -n*x_e (mod d),  u <= n*x_e
(y = (nx+u)/d, z = (nx + (nx)^2/u)/d are then positive integers).

Claim (subgroup characterization).  For squarefree d with gcd(n*x_e, d) = 1,
such a u exists iff
    -n*x_e (mod d)  is in  < p (mod d) : p | n*x_e >
(the subgroup of (Z/d)^* generated by the prime factors of n*x_e).
Equivalently: -n*x_e lies in the subgroup of (Z/d)^* generated by n*x_e.

   Proof sketch: every divisor of (n x_e)^2 is a product of powers of primes
   dividing n*x_e, so its residue mod d lies in the generated subgroup.
   Conversely, if -nx is in the subgroup, write it as a product of prime
   powers; multiplying by a suitable power of (nx) itself (whose square is 1
   mod d... actually (nx)^2 = M = u*v, and v = M/u compensates) gives a
   divisor <= nx in the right class (pairing u, M/u, one of them is <= nx,
   and M/u == -nx mod d when gcd = 1, by u*v == (nx)^2 and u == -nx).

This program checks, over every row of the extended sweep (k <= 450, all six
classes, 2705 solutions):
  * for the minimal excess e: -n*x_e mod d is in the subgroup; and
  * for every e' < e (so d' = 4e'+3): -n*x_{e'} mod d' is NOT in the subgroup
    (this is exactly what minimality of x demands, independently of the
    u <= nx subtlety, which is also checked by brute force).

The subgroup computation is exact: factor n*x_e, reduce each prime mod d,
generate the subgroup multiplicatively, and test membership by checking every
element (|(Z/d)^*| is tiny here, d <= 4*14+3 = 59).

Also re-checks the d=7 criterion with the residue bug fixed:
   e <= 1 (d=7 works)  <=>  some prime q | n or q | (n+7)/4 has q % 7 in
   {3,5,6} (quadratic non-residues mod 7).
"""
import json, time
from sympy import factorint, isprime
from fractions import Fraction

rows = json.load(open('code/out/extended_minimal_x.json'))['rows']
QNR7 = {3, 5, 6}

def two_term(n, x):
    d = 4 * x - n
    if d <= 0:
        return None
    nx = n * x
    M = nx * nx
    cnt = 0
    from sympy import divisors
    for u in divisors(M):
        if u > nx:
            continue
        if (nx + u) % d != 0:
            continue
        v = M // u
        if (nx + v) % d != 0:
            continue
        y, z = (nx + u) // d, (nx + v) // d
        if y >= 1 and z >= 1 and Fraction(1, x) + Fraction(1, y) + Fraction(1, z) == Fraction(4, n):
            return (y, z)
    return None

def subgroup_membership(n, e):
    """Return (in_subgroup, subgroup_size, d) for candidate excess e, or None if gcd != 1."""
    d = 4 * e + 3
    x = (n + 4 * e + 3) // 4
    if 4 * x - n != d:
        return None
    nx = n * x
    from math import gcd
    if gcd(nx, d) != 1:
        return None            # the caveat case: need prime-power refinement
    target = (-nx) % d
    gens = set()
    for q in factorint(nx):
        gens.add(q % d)
    # generate subgroup
    sub = {1}
    frontier = {1}
    while frontier:
        nxt = set()
        for a in frontier:
            for g in gens:
                b = (a * g) % d
                if b not in sub:
                    sub.add(b); nxt.add(b)
        frontier = nxt
        if len(sub) == d - 1:
            break
    return (target in sub), len(sub), d, sorted(gens)

def main():
    t0 = time.time()
    bad_sub = []      # minimal e should be IN subgroup
    bad_min = []      # e' < e should NOT be in subgroup
    bad_two = []      # subgroup says yes but brute-force split says no
    n_apply = 0
    for row in rows:
        n, e = row['n'], row['excess']
        x = row['x']
        # brute-force ground truth at the minimal x: split must exist
        assert two_term(n, x) is not None

        m = subgroup_membership(n, e)
        if m is None:
            continue
        n_apply += 1
        in_sub, sz, d, gens = m
        if not in_sub:
            bad_sub.append((row['k'], row['r'], n, e, d, gens))
        else:
            # the subgroup answer says d works; brute force must agree
            xd = (n + d) // 4
            if two_term(n, xd) is None:
                bad_two.append((row['k'], row['r'], n, e, d))
        for ep in range(e):
            mp = subgroup_membership(n, ep)
            if mp is not None and mp[0]:
                bad_min.append((row['k'], row['r'], n, e, ep))

    print(f"rows with gcd(n*x_e, 4e+3)==1 (criterion applies): {n_apply}/{len(rows)}")
    print(f"minimal e in subgroup: {n_apply - len(bad_sub)}/{n_apply}  (violations {bad_sub[:5]})")
    print(f"all e'<e outside subgroup: {n_apply - len(bad_min)}/{n_apply}  (violations {bad_min[:5]})")
    print(f"subgroup-yes but brute-force-no splits: {len(bad_two)} {bad_two[:5]}")

    # --- d=7 criterion, residue bug fixed: e<=1 <=> QNR-7 prime divides n*(n+7)/4 ---
    bad7 = 0; total7 = 0
    for row in rows:
        n = row['n']
        works = two_term(n, (n + 7) // 4) is not None
        cond = any((p % 7) in QNR7 for p in factorint(n)) or \
               any((p % 7) in QNR7 for p in factorint((n + 7) // 4))
        total7 += 1
        if works != cond:
            bad7 += 1
            if bad7 <= 8:
                print(f"  d=7 mismatch: k={row['k']} r={row['r']} n={n} works={works} cond={cond}")
    print(f"d=7 criterion (q%7 in {{3,5,6}} divides n or (n+7)/4): {total7-bad7}/{total7} rows agree")

    # --- d=3 criterion, restate: e=0 <=> some q%3==2 divides n or (n+3)/4 ---
    bad3 = 0
    for row in rows:
        e0 = (row['excess'] == 0)
        cond = any(p % 3 == 2 for p in factorint(row['n'])) or \
               any(p % 3 == 2 for p in factorint((row['n'] + 3) // 4))
        if e0 != cond:
            bad3 += 1
    print(f"d=3 criterion (q%3==2 divides n or (n+3)/4): {len(rows)-bad3}/{len(rows)} rows agree")

    print(f"done in {time.time()-t0:.1f}s")

if __name__ == '__main__':
    main()