

# This file was *autogenerated* from the file code/stick_index.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0); _sage_const_5 = Integer(5); _sage_const_7 = Integer(7); _sage_const_11 = Integer(11)# Clean exact computation of [Z[G]^- : s^-] for p=5,7,11 via Z-lattice index.
# Convention: theta = (1/p) sum_{a=1}^{p-1} a sigma_{a^{-1}} (Washington IX.2).
# s = Z[G] cap theta^{-1} Z[G].  e^-=(1/2)(1-sigma_{-1}).
from fractions import Fraction

def minus_index(p):
    n = p - _sage_const_1 
    idx = list(range(_sage_const_1 , p))
    pos = {a: i for i, a in enumerate(idx)}
    inv = {a: pow(a, p - _sage_const_2 , p) for a in idx}
    m = (p - _sage_const_1 ) // _sage_const_2 
    # theta = (1/p) sum_a a sigma_{a^{-1}};  its multiplication by sigma_a:
    # (sigma_a * theta) = sum_c (c^{-1} a / p) sigma_c   (c = a u, u^{-1}/p)
    # so the matrix M (row c, col a) giving coeff of sigma_c in sigma_a*theta:
    M = matrix(QQ, n, n)
    for ai, a in enumerate(idx):
        ai_inv = inv[a]
        for ci, c in enumerate(idx):
            u = (ai_inv * c) % p
            M[ci, ai] = Fraction(int(pow(int(u), p - _sage_const_2 , p)), int(p))
    # s = { x in Z^n : M x in Z^n }.  M = N/p with N integral.
    # N x = p z, x,z in Z^n  =>  (N | -p I)(x;z) = 0 over Z.
    N = matrix(ZZ, n, n)
    for i in range(n):
        for j in range(n):
            N[i, j] = M[i, j] * p
    Blk = block_matrix(ZZ, [[N, -p * identity_matrix(ZZ, n)]])
    Ker = Blk.right_kernel()
    sxs = [list(g[:n]) for g in Ker.basis()]
    s_lat = matrix(ZZ, sxs).echelon_form()
    s_rows = [list(r) for r in s_lat.rows()]
    # Z-basis of e^-Z[G]: v_a = e_a - e_{-a}, a=1..m  (rank m, each in minus part)
    basis = []
    for a in range(_sage_const_1 , m + _sage_const_1 ):
        v = [_sage_const_0 ] * n; v[pos[a]] = _sage_const_1 
        w = [_sage_const_0 ] * n; w[pos[(p - a) % p]] = _sage_const_1 
        basis.append([x - y for x, y in zip(v, w)])
    B = matrix(QQ, basis)  # m x n
    def coords_in_minus_basis(w):
        return B.solve_left(vector(QQ, w))
    def e_minus(v):
        rv = [v[pos[(p - a) % p]] for a in idx]
        return [(vv - rvv) / _sage_const_2  for vv, rvv in zip(v, rv)]
    coords = []
    for xrow in s_rows:
        pm = e_minus(xrow)
        coords.append(list(coords_in_minus_basis(pm)))
    # integer lattice generated by coords in Z^m; index = |Z^m / (D L)| / D^m
    # = (product of invariant factors of Smith form) / D^m
    from sage.all import lcm
    dens = [c.denominator() for row in coords for c in row]
    D = lcm(dens)
    if D == _sage_const_0 :
        D = _sage_const_1 
    Cint = matrix(ZZ, [[(Fraction(c) * int(D)).numerator() for c in row] for row in coords])
    S, U, V = Cint.smith_form()
    d = prod(int(S[i, i]) for i in range(S.nrows()))
    idx = Fraction(d, D ** m)
    return idx, (len(s_rows), S.dimensions())

for p in [_sage_const_5 , _sage_const_7 , _sage_const_11 ]:
    idx, dim = minus_index(p)
    print("p=%d  [Z[G]^-:s^-] = %s   dims=%s   (h^- from our exact table: 1)" % (p, idx, dim))

