"""Exact computation of the Stickelberger-minus index  [Z[G]^- : s^-]  for Q(zeta_p).

Setup (Washington IX.2, Thm 6.10):
  G = (Z/p)^*,  theta = (1/p) * sum_{a=1}^{p-1} a sigma_{a^{-1}}  in Q[G],
  s = Z[G]theta cap Z[G],   e^- = (1/2)(1 - sigma_{-1}).
  The theorem is  [Z[G]^- : s^-] = h^-(Q(zeta_p)).

The condition defining s:  x in s  <=>  x = theta * u for some u in Z[G]
  <=>  x * theta^{-1} in Z[G]  <=>  M^{-1} x in Z^n,
  where M is the multiplication-by-theta matrix (x as coefficient vector),
  i.e.  s = M Z^n cap Z^n  =  (N/p) Z^n cap Z^n  with M = N/p, N integer.

  x = (1/p) N y in Z^n  for y in Z^n  <=>  N y ≡ 0 (mod p).
  So   s = (1/p) * N * Y,   Y = { y in Z^n : N y ≡ 0 (mod p) },
  a rank-n lattice.  We build a Z-basis of Y (p·identity plus lifts of the
  mod-p kernel of N), then project by e^- and take the lattice index against
  e^- Z[G].  Everything is exact integer/rational arithmetic.
"""
from fractions import Fraction
from sympy import Matrix, GF


def mod_p_kernel_lifts(N, p):
    """Return list of integer column vectors (representatives mod p) that
    form a basis of ker(N mod p) over GF(p), each reduced to [0,p)."""
    n = N.rows
    Np = N.applyfunc(lambda v: v % p)   # matrix over ZZ reduced
    # row/col reduce over GF(p) to find a kernel basis: solve Np x = 0 mod p
    from sympy import Matrix as M
    A = M(Np).applyfunc(lambda v: int(v) % p)
    # nullspace over GF(p)
    F = GF(p)
    Af = A.applyfunc(lambda v: F(int(v) % p))
    ns = Af.nullspace()
    lifts = [list(map(int, v.T)) for v in ns]   # each column vector length n
    return lifts


def minus_index(p):
    n = p - 1
    idx = list(range(1, p))
    pos = {a: i for i, a in enumerate(idx)}
    inv = {a: pow(a, p - 2, p) for a in idx}
    # M[c,a] = (a * c^{-1})/p   (coefficient of sigma_c in sigma_a * theta)
    M = Matrix.zeros(n, n)
    for ai, a in enumerate(idx):
        for ci, c in enumerate(idx):
            M[ci, ai] = Fraction((a * inv[c]) % p, p)
    N = Matrix(n, n, lambda i, j: int(M[i, j] * p))
    # --- basis of Y = { y in Z^n : N y ≡ 0 mod p } ---
    # p * e_i  (all of them) plus lifts of mod-p kernel
    Ycols = []
    for i in range(n):
        v = [0]*n; v[i] = p
        Ycols.append(v)
    for v in mod_p_kernel_lifts(N, p):
        Ycols.append(v)
    # s = (1/p) N Y :  apply (1/p)N to each Y generator, reduce to Q-coords of Z[G]
    s_gens = []   # rational vectors in Q^n
    for y in Ycols:
        Ny = list(N * Matrix(y))            # integer column
        s_gens.append([Fraction(int(v), p) for v in Ny])
    # --- minus part ---
    m = (p - 1) // 2
    # Z-basis of e^- Z[G]:  v_a = e_a - e_{-a}, a = 1 .. m,  (a rank-m lattice)
    basis = []
    for a in range(1, m + 1):
        v = [0]*n; v[pos[a]] = 1
        w = [0]*n; w[pos[(p - a) % p]] = 1
        basis.append([x - y for x, y in zip(v, w)])
    B = Matrix(basis)                     # m x n
    def e_minus(v):
        return [(Fraction(vv) - Fraction(v[pos[(p - a) % p]])) / 2
                for a, vv in zip(idx, v)]
    def coords(w):
        # w (length n) as a combination of the m basis rows:  w = c B  <=> B^T c = w^T
        return B.transpose().solve(Matrix(w)).T.tolist()[0]
    # s^- generators in the B-coordinate lattice
    coords_s = [coords(e_minus(g)) for g in s_gens]
    # index = |det of integer lattice generated by coords_s in Z^m|
    from math import lcm, gcd
    import math as _m
    dens = set()
    for row in coords_s:
        for c in row:
            dens.add(Fraction(c).denominator)
    D = _m.lcm(*list(dens)) if dens else 1
    if not isinstance(D, int):
        D = _m.lcm(*list(dens))
    # scale by D to integers, then take Smith/determinant
    Cint = Matrix([[Fraction(c)*D for c in row] for row in coords_s])
    # reduce to m x m full-rank by dropping dependent rows via integer row reduction
    # compute index = |det(Cint)| / D^m  (coords give full-rank lattice in Z^m)
    # full-rank determinant: use Smith normal form of Cint
    from sympy.matrices.normalforms import smith_normal_form
    from sympy import ZZ
    # Cint may be n-generators x m ; we want the sublattice index in Z^m.
    # The quotient Z^m / L  has order = product of invariant factors of Smith(Cint).
    S = smith_normal_form(Cint, domain=ZZ)
    diag = [int(S[i, i]) for i in range(min(S.rows, S.cols))]
    order = 1
    for d in diag:
        order *= d
    index = Fraction(order, D ** m)
    return index


if __name__ == "__main__":
    for p in [5, 7, 11]:
        idx = minus_index(p)
        print("p=%d  [Z[G]^- : s^-] = %s   (Bernoulli h^- = 1)" % (p, idx))
