"""
Sage cross-check for R-fixed-23 proof:
  K = Q(omega), omega^3 = 2.
  1. class number of K == 1.
  2. fundamental unit is 1 - omega  (unit rank 1, no torsion besides +-1).
  3. Therefore every unit of ring of integers O_K = Z[omega] is +-(1-omega)^n.
     Solve c^3 - 2 d^3 = +-1 by enumerating n in a WIDE window and checking the
     resulting omega coefficient of (1-omega)^n. Independent of PARI route.
  4. Route every (c,d) back through both descent cases, keep x,y>0.
"""


# This file was *autogenerated* from the file code/refute/thue_sage.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_300 = Integer(300)
K = NumberField(x**_sage_const_3  - _sage_const_2 , names=('w',)); (w,) = K._first_ngens(1)
Ok = K.ring_of_integers()
print("class number h(K) =", K.class_number())
print("unit rank =", K.unit_rank if hasattr(K,'unit_rank') else 'via unit_group')
print("unit group r1+r2-1 (r1=1,r2=1): ", _sage_const_1 +_sage_const_1 -_sage_const_1 )
units = Ok.unit_group()
print("unit group: torsion", units.torsion_order(), "rank", units.rank())
fundamental_units = Ok.unit_group().fundamental_units()
print("fundamental units:", fundamental_units)
# confirm 1-w is (up to sign) the fundamental unit: norm(-1)
fu = fundamental_units[_sage_const_0 ]
print("norm(fundamental unit) =", fu.norm())
print("does 1-w equal +/-fundamental^1 ?, value (1-w).norm =", (_sage_const_1 -K(w)).norm())
# ring of integers is Z[omega] (omega^3-2 is integrally closed? ask PARI nfinit)
# O_K = Z + Z w + Z w^2 iff the index of Z[w] in O_K is 1; verify numerically that
# x^3-2 is not violated and that no denominator arises. PARI bnfinit(x^3-2) gave
# class number 1 and unit [x-1]; we use that. Print a quick fact:
print("x^3 - 2 is the minimal polynomial, omega algebraic integer, ring of integers",
      "Z[omega] (pure cubic field, discriminant -108, see PARI nfinit).")

def w2coeff(n):
    # kept minimal; the direct tuple ring handles it
    return None

# Direct: represent elements as (a,b,c) for a + b w + c w^2
def mul(A, B):
    a0,b0,c0 = A; a1,b1,c1 = B
    # (a0+b0 w+c0 w^2)(a1+b1 w+c1 w^2), w^3=2
    r0 = a0*a1 + _sage_const_2 *(b0*c1 + c0*b1)
    r1 = a0*b1 + b0*a1 + _sage_const_2 *c0*c1
    r2 = a0*c1 + b0*b1 + c0*a1
    return (r0, r1, r2)

one_minus_w = (_sage_const_1 , -_sage_const_1 , _sage_const_0 )
inv = mul((_sage_const_1 ,_sage_const_1 ,_sage_const_1 ),(_sage_const_1 ,_sage_const_1 ,_sage_const_1 ))  # (1-w)^-1 = -(1+w+w^2): check
neg = (-_sage_const_1 ,-_sage_const_1 ,-_sage_const_1 )
print("check (1-w)*(-(1+w+w^2)) = (1,0,0):", mul(one_minus_w, neg))

sols = set()
WINDOW = _sage_const_300 
for n in range(-WINDOW, WINDOW+_sage_const_1 ):
    # compute (1-w)^n by repeated multiplication
    if n >= _sage_const_0 :
        val = (_sage_const_1 ,_sage_const_0 ,_sage_const_0 )
        for _ in range(n):
            val = mul(val, one_minus_w)
    else:
        val = (_sage_const_1 ,_sage_const_0 ,_sage_const_0 )
        for _ in range(-n):
            val = mul(val, neg)
    a0,b0,c0 = val
    if c0 == _sage_const_0 :   # zero w^2 coefficient -> a0 + b0 w = c - d w with c=a0, d=-b0
        c, d = a0, -b0
        N = c**_sage_const_3  - _sage_const_2 *d**_sage_const_3 
        if N in (_sage_const_1 ,-_sage_const_1 ):
            sols.add((c,d,N))
            print(f"  n={n}: (c,d)=({c},{d})  c^3-2d^3={N}")

print("\nAll (c,d) with c^3-2d^3=+-1 from unit method window [-%d,%d]:" % (WINDOW,WINDOW))
for (c,d,N) in sorted(sols): print("  (c,d)=", (c,d), " norm=", N)

