#!/usr/bin/env python3
"""Exploratory scratch: nail down the A2 index-7 quotient and the separation
graph F before building code/lib/torus_margin.py.  Exact arithmetic only."""
import itertools
import sympy as sp

sqrt3 = sp.sqrt(3)
L = sp.Rational(2, 5)  # example L in the window 1/(sqrt21-2)~0.6057? no, that's wrong, check below

# ---- window derivation ----
sqrt21 = sp.sqrt(21)
window_lo = 1 / (sqrt21 - 2)
print("window_lo ~", sp.N(window_lo, 12))
print("window_hi = 1/2 =", sp.N(sp.Rational(1, 2)))
print("margin at L=1/2:", sp.simplify((sqrt21 - 2) * sp.Rational(1, 2)), "~",
      sp.N((sqrt21 - 2) * sp.Rational(1, 2), 12))

# ---- A2 lattice point (u,v) -> physical (x,y) with centre spacing s = sqrt3*L
def centre(u, v, Lv):
    x = sqrt3 * Lv * (u - v / 2)
    y = sqrt3 * Lv * (sqrt3 / 2 * v)      # = 3/2 L v
    return sp.simplify(x), sp.simplify(y)

# sanity: nearest neighbours at spacing sqrt3*L
p0 = centre(0, 0, L); p1 = centre(1, 0, L)
dist_10 = sp.simplify((p1[0]-p0[0])**2 + (p1[1]-p0[1])**2)
print("|(1,0)-(0,0)|^2 =", sp.simplify(dist_10), "= (sqrt3 L)^2 =",
      sp.simplify((sqrt3*L)**2))

# ---- norm-7 sublattice (2-omega), generated by (2,-1) and (1,3) in (u,v)
# representatives of Z^2 / <(2,-1),(1,3)>
g1 = (2, -1); g2 = (1, 3)

def coset(u, v):
    # reduce (u,v) into a canonical representative
    # solve (u,v) = (2a+b, -a+3b) + r, r in a fixed 7-set.
    # walk: subtract g1,g2 greedily then pick nearest to origin
    return (u, v)

# brute: enumerate a window, find 7 distinct cosets closest to origin
def reduce_point(u, v):
    # try subtracting integer combinations to get into fundamental cell,
    # then return the coset label as (a,b) reduction: find (a,b) with
    # (u,v) = a*g1 + b*g2 + r, r in smallest set. We'll find canonical reps
    # by grouping.
    return None

# Group all points in a box by coset, then within each coset pick nearest to origin.
box = range(-10, 11)
points = [(u, v) for u in box for v in box]

def coset_key(u, v):
    # canonical reduction: repeatedly subtract g1,g2 while it helps; use a
    # simple canonical via solving over reals-free integer reduction.
    # Do a finite search: the rep is the closest point to origin in the coset.
    return None

# Simpler: compute the coset equivalence by checking (u,v)-(u0,v0) in lattice
def in_lattice(dx, dy):
    # (dx,dy) = a*(2,-1)+b*(1,3) = (2a+b, -a+3b); solve for integers
    # 2a+b = dx, -a+3b = dy -> b = dx-2a; -a+3(dx-2a)=dy => -7a+3dx=dy => 7a=3dx-dy
    num = 3*dx - dy
    if num % 7 != 0:
        return False
    a = num // 7
    b = dx - 2*a
    return True

# find canonical rep of each coset = point minimizing distance to origin
from collections import defaultdict
cosets = defaultdict(list)
for (u, v) in points:
    # put into coset keyed by reducing: we only need representative
    pass

# Instead: choose reps = the 7 points in a fundamental region closest to origin.
# Distance from origin in lattice units: u^2 - u*v + v^2 (inner product metric).
def latnorm(u, v):
    return u*u - u*v + v*v

reps = []
used = set()
# iterate points sorted by lattice norm
for (u, v) in sorted(points, key=lambda p: (latnorm(*p), abs(p[0])+abs(p[1]))):
    # check not equivalent to any chosen rep
    equiv = False
    for (ru, rv) in reps:
        if in_lattice(u - ru, v - rv):
            equiv = True
            break
    if not equiv:
        reps.append((u, v))
        if len(reps) == 7:
            break
print("7 representatives of index-7 sublattice:", reps)
print("their lattice norms:", [latnorm(*r) for r in reps])

# ---- build F: physical distance threshold T = 1 + 2L, edge iff |u-v| <= T
T = 1 + 2*L
T2 = sp.expand(T**2)
print("T = 1+2L =", T, "~", sp.N(T, 10), " T^2 ~", sp.N(T2, 10))

edges = []
for k,(u1,v1) in enumerate(reps):
    for j in range(k+1, len(reps)):
        u2, v2 = reps[j]
        c1 = centre(u1, v1, L); c2 = centre(u2, v2, L)
        d2 = sp.expand((c1[0]-c2[0])**2 + (c1[1]-c2[1])**2)
        # exact comparison d2 <= T2
        diff = sp.simplify(d2 - T2)
        le = sp.simplify(diff <= 0)   # sympy compare exact
        print(f"  pair {reps[k]},{reps[j]} d2~{sp.N(d2,8)} T2~{sp.N(T2,8)} d2-T2 sign: {le} (diff~{sp.N(diff,6)})")
        if le is True:
            edges.append((k, j))
print("edges among 7 reps (complete graph would be", 7*6//2, "):", edges)
print("if len(edges) == 21 -> K7 -> chi=7")
