#!/usr/bin/env python3
"""Check the load-bearing combinatorial claims of the three proposed candidates.

Candidate 1 (mobius-meet-factorization):
  Claim: for j = d & d', each piece M_d \\ M_j is a disjoint union of "subcubes"
  indexed by the set bits of d \\ j, in the sense that the run/product structure
  of M_d △ M_{d'} factorizes per set-bit of d △ d'.  We test the literal claim:
  for each pair (d,d'), with j = d&d', does M_d △ M_{d'} decompose as a disjoint
  union over the set bits b of (d ^ d') of sub-blocks each lying within a single
  reflected subcube?  We test the run structure: is every run of M_d △ M_{d'}
  contained in a single reflected subcube generated by one set bit (i.e. does the
  symmetric difference not "interleave" two set bits within one run)?

Candidate 2 (endpoint-product-dirichlet):
  The contraction chi(ab)=chi(a)chi(b) is assumed; the combinatorial question is
  whether the endpoint products P_{d,d'} = prod_R q_{a_R} q_{b_R} form a set with
  any "Dirichlet-series structure".  We at least verify the run-decomposition and
  endpoint multiset (separation = powers of two etc.) that the route claims.

Candidate 3 (excess-degree-spectrum-dichotomy):
  Claim: |M_d| = 2^{pc(d)} (even for d>=2), so every monomial of S(n) has even
  degree, S(n) is orthogonal to degree-1 (switch density): <S(n), u_j> = 0.
  Also that degree-2/4 spectra of S(n)^2 are carried by separations.
  We verify: (i) |M_d| = 2^{pc(d)}; (ii) no monomial of degree 1 exists;
  (iii) the distance-2/symmetric-difference-2 stratum products u_a u_b are at
  NON-adjacent positions (no separation-1 switch sign in the 4th-order stratum).
"""
import itertools

def submasks(x):
    s = x
    while True:
        yield s
        if s == 0:
            break
        s = (s - 1) & x

def M(n, d):
    return sorted({n - 1 - d + o for o in submasks(d) if 0 <= n - 1 - d + o <= n - 1})

def runs_of(S):
    runs = []
    for x in S:
        if runs and x == runs[-1][1] + 1:
            runs[-1][1] = x
        else:
            runs.append([x, x])
    return runs

def pc(x):
    return bin(x).count("1")

def test_candidate3(nmax):
    """evenness: |M_d| = 2^{pc(d)} even, no degree-1 monomial, distance-2 = 2 non-adjacent singletons."""
    ok_even = True
    ok_nosingle = True
    ok_a2 = True
    a2_seps = set()
    for n in range(3, nmax):
        for d in range(2, n):
            md = M(n, d)
            if len(md) != 2**pc(d):
                ok_even = False
                print("  evenness FAIL n,d:", n, d, len(md), 2**pc(d))
            # degree-1 monomial: |M_d| == 1
            if len(md) == 1:
                ok_nosingle = False
                print("  degree-1 monomial n,d:", n, d)
        # distance-2 pairs
        for d, dp in itertools.combinations(range(2, n), 2):
            S = sorted(set(M(n,d)) ^ set(M(n,dp)))
            if len(S) == 2:
                R = runs_of(S)
                if len(R) != 2 or R[1][0] - R[0][1] == 1:
                    ok_a2 = False
                    print("  A2 not two non-adjacent singletons:", n, d, dp, R)
                else:
                    a2_seps.add(R[1][0] - R[0][0])
    print(f"[C3] evenness |M_d|=2^pc(d): {ok_even}; no degree-1 monomial: {ok_nosingle};")
    print(f"[C3] A2 stratum = 2 non-adjacent singletons: {ok_a2}")
    print(f"[C3] A2 separations seen (must have none = 1): {sorted(a2_seps)[:20]}")
    return ok_even and ok_nosingle

def test_candidate1(nmax):
    """Does M_d △ M_{d'} decompose per set-bit?  We test whether every maximal run
    of the symmetric difference lies within a single reflected subcube, i.e. whether
    no run 'interleaves' two set bits of d ^ d'."""
    # A run [a,b] interleaves bits if subsets contiguity property fails.  The cleanest
    # test: M_d is {n-1-d+o : o submask of d}.  Reflect to index 0: L_d = {o : o submask of d}.
    # Then L_d △ L_{d'} = (downsets).  A run in reflected coordinates corresponds to
    # consecutive o-values.  The claim 'union of subcubes per set bit of d\\j' means the
    # symmetric difference's reflected set is a disjoint union, across set bits b of d^d',
    # of sets that are translation-invariant in bit b (full within the subcube).
    interleaves = []
    perbit_fail = []
    for n in range(3, nmax):
        for d, dp in itertools.combinations(range(2, n), 2):
            R_n = set(M(n,d)) ^ set(M(n,dp))
            # reflect: r = n-1 - position
            Rrev = sorted(n - 1 - x for x in R_n)
            runs = runs_of(Rrev)
            diff = d ^ dp
            for a, b in runs:
                # does this run lie entirely within one subcube generated by a single
                # set bit?  A subcube for bit b (all o with bit b free, others of d\\j fixed)
                # is a set {fixed + t*2^b : t in {0,1}}.  A run [a,b] fits one such iff
                # the run length is 2 and the two elements differ by a single power of 2,
                # OR length 1.
                L = b - a + 1
                if L >= 2:
                    # check: is {a..b} equal to a contiguous sub-block parameterized by ONE bit?
                    # contiguous interval [a,b] of length 2^k is a subcube for bit k iff
                    # a mod 2^(k) and the interval [a,b] = {c, c+1} for length-2 subcube.
                    if L == 2 and (b - a) == 1:
                        # two adjacent positions; is this a subcube for a single set bit?
                        # only if b and a agree on all bits except one single bit.
                        xr = a ^ b
                        if pc(xr) == 1:
                            pass  # fits a length-2 subcube
                        else:
                            interleaves.append((n, d, dp, (a, b)))
                    else:
                        interleaves.append((n, d, dp, (a, b)))
    print(f"[C1] runs of M_d△M_{'d\''} that are NOT single-bit subcubes (length>2 or not 2-bit):")
    if not interleaves:
        print("  NONE (all runs are single-bit subcubes) for n<", nmax)
    else:
        from collections import Counter
        c = Counter((L := (b-a+1)) for _,_,_,(a,b) in interleaves)
        print("  count:", len(interleaves), " length spectrum:", dict(c))
        for ex in interleaves[:5]:
            print("   e.g.", ex)
    return len(interleaves) == 0

def test_candidate2(nmax):
    """Endpoint multiset / separations of runs of M_d △ M_{d'}.  Report the
    separation distribution (run lengths) and confirm no separation-1 single run."""
    lengths = Counter()
    nosingle = True
    for n in range(3, nmax):
        for d, dp in itertools.combinations(range(2, n), 2):
            S = sorted(set(M(n,d)) ^ set(M(n,dp)))
            for a,b in runs_of(S):
                L = b - a + 1
                lengths[L] += 1
                if L == 1:
                    nosingle = False
    print(f"[C2] run lengths of M_d△M_{'d\''} distribution (n<{nmax}): {dict(sorted(lengths.items()))}")
    print(f"[C2] any length-1 run (separation-1 single run): {not nosingle}")
    return nosingle

from collections import Counter
test_candidate3(40)
print()
ok1 = test_candidate1(40)
print()
test_candidate2(40)
