"""Independent no-4-cycle filter, exact integer arithmetic.

A simple graph contains a 4-cycle iff some pair of distinct vertices has at
least two common neighbours (those two neighbours plus the pair form the C4).
So: G is C4-free  <=>  every pair of vertices has at most one common neighbour.

This is a structurally different check from geng's -f filter: for each graph
generated by geng WITHOUT -f, decide C4-freeness by this pairwise-common-
neighbour rule, and count.  Used to cross-check NO4(n) = # connected graphs on
n vertices with min degree >= 3 and no 4-cycle, which the run computes via
`nauty-geng -f -d3 -c -u n`.

Usage:
    nauty-geng -d3 -c n | python3 c4free_check.py n
reads graph6 lines on stdin, prints the exact count of C4-free graphs and the
wall time.
"""
import sys
import time


def parse_graph6(s):
    """Decode graph6 string to adjacency list. Exact integers."""
    s = s.strip()
    n = ord(s[0]) - 63
    bits = []
    for ch in s[1:]:
        v = ord(ch) - 63
        for k in range(6):
            bits.append((v >> (5 - k)) & 1)
    adj = [[] for _ in range(n)]
    idx = 0
    for j in range(1, n):
        for i in range(j):
            if bits[idx]:
                adj[i].append(j)
                adj[j].append(i)
            idx += 1
    return adj


def min_degree(adj):
    return min((len(nb) for nb in adj), default=0)


def has_c4(adj):
    """True iff some pair of vertices shares >= 2 common neighbours."""
    n = len(adj)
    adjset = [set(nb) for nb in adj]
    for a in range(n):
        for b in range(a + 1, n):
            if len(adjset[a] & adjset[b]) >= 2:
                return True
    return False


def main():
    n_target = int(sys.argv[1]) if len(sys.argv) > 1 else None
    t0 = time.time()
    total = 0
    c4free = 0
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        adj = parse_graph6(line)
        if n_target is not None and len(adj) != n_target:
            continue
        total += 1
        if min_degree(adj) >= 3 and not has_c4(adj):
            c4free += 1
    print(f"read {total} graphs in {time.time() - t0:.1f}s; "
          f"connected min-deg>=3 C4-free: {c4free}")


if __name__ == "__main__":
    main()