import Mathlib.Data.ZMod.Basic
import Mathlib.NumberTheory.ZMod
import Mathlib.Data.Int.GCD

#check ZMod.intCast_zmod_eq_zero_iff_dvd
#check Int.cast_zmod_eq_zero_iff_dvd
#check ZMod.natCast_zmod_eq_zero_iff_dvd
#check ZMod.pow_card
#check ZMod.pow_card_one
#check ZMod.cast_natCast
#check ZMod.exists_zmod_eq_val
#check Int.cast_pow
#check map_pow
#check Int.gcd
#check Int.gcd_eq_gcd
#check Int.gcd_dvd_left
#check Int.gcd_dvd_right
#check Int.dvd_gcd
#check Int.gcd_pos_of_ne_zero
#check Int.gcd_eq_natAbs
#check Int.dvd_sub_iff_left
#check Int.dvd_sub_iff_right
#check Int.emod_eq_of_lt
#check dvd_gcd
#check Nat.dvd_gcd
#check Nat.gcd_eq_left
#check Int.gcd_eq_left
#check Int.gcd_eq_right
