import Mathlib

#check Int.one_le_pow
#check one_le_pow₀
#check Finset.sum_le_sum
#check Finset.sum_const
#check mul_le_mul
#check Nat.cast_sub
#check Nat.pow_le_pow_left
#check Nat.Prime.two_le
#check Nat.Prime.pos
#check odd_iff_not_even
#check Nat.even_iff
#check Nat.Coprime.gcd_eq_one
#check Nat.gcd_dvd_left
#check Nat.gcd_dvd_right
#check Nat.dvd_antisymm
#check Nat.dvd_sub
#check Nat.dvd_sub'
#check Nat.one_dvd
#check Nat.dvd_prime
#check Nat.Prime.dvd_of_dvd_pow
#check Nat.dvd_of_mul_dvd_mul_left
#check Nat.dvd_mul_right
#check Nat.dvd_refl
#check Nat.gcd_eq_right
#check Nat.gcd_comm
#check Nat.even_iff_two_dvd
#check Nat.even_sub_one
#check Nat.two_dvd_ne_zero
#check Nat.dvd_of_mod_eq_zero
#check Int.ofNat_sub
#check Int.natCast_sub
#check even_iff_two_dvd
#check Odd
#check Even
#check Nat.odd_iff
#check Nat.not_even_iff_odd
#check even_iff
#check Nat.even_or_odd
