import Mathlib

namespace Cited

/-- Theorem 4.1 from Bruyère, Hansel, Michaux, Villemaire (1994):
For every integer p ≥ 2 and every sequence s : ℕ → A over a finite alphabet A,
s is generated by a p-substitution if and only if s is p-recognizable,
if and only if s is p-definable.

This statement cannot be faithfully formalised because Mathlib does not
define "p-substitution", "p-recognizable", or "p-definable" (concepts from the
theory of automatic sequences). Without these definitions, any formalisation
would be a placeholder asserting `True`, which is not a valid theorem. -/
axiom p_automaticity_equivalence {A : Type} [Finite A] (p : ℕ) (hp : 2 ≤ p) (s : ℕ → A) :
    True

end Cited
