#!/usr/bin/env python3
"""Generating stretches behind the 12 genuine giant (2,4)-events.

Event rows k in {34,56,64,68,94,96,110,112,126,130,134,146} (1-based row of
the prime Gilbreath triangle; row 0 = the primes). Block lengths b_k, b_{k+1}
from code/out/blocks_depth1000.json: b[i] stores the block length of row i+1,
so b_k = b[k-1], b_{k+1} = b[k]. All twelve events have a positive jump
j = b_{k+1} - b_k in [1314, 360698] (the genuine giants of claim
bigjump-cap-characterization-1000; row 161 is the capped 13th giant, kept for
the cross-check only).

Mechanism verified: the landing row's fresh {0,2} run of length j at
positions b_k+1..b_{k+1} is generated by the event row's halved stretch
h_k(i) = A_k(i)/2 for i in [b_k, b_{k+1}+1] being a 1-Lipschitz chain
(|h(i+1)-h(i)| <= 1): each landing entry A_{k+1}(i) = |A_k(i) - A_k(i+1)|
= 2|h(i) - h(i+1)| is in {0,2} iff the chain step is in {-1,0,1}. Every
entry past column 0 of every row >= 1 is even, so halving is exact.

Method: sieve primes once (2e7 -> 1,270,607 primes), stream rows 1..147 one
at a time via lib.gilbreath.rows_generator, never holding more than the
current row plus the 12 kept windows. Exact integers everywhere.
Time O(W) x 148 rows ~ 1.9e8 element ops (~2 min). Space O(W): current row
1.27e6 ints + kept generating windows (3.35e6 ints total) + landing bits
stored as bytearrays (3.35e6 bytes). One worker.

Built-in checks (any failure exits non-zero):
  * worked-example oracle: rows A_1..A_5 of problem.md reproduced exactly;
  * block_profile(row r) == b[r-1] for every event row (13: the 12 genuine
    + capped giant row 161) and every genuine landing row (12);
  * step law: (edge, intruder) == (2,4) at each event row;
  * the generating stretch is a genuine 1-Lipschitz chain (diffs in
    {-1,0,1});
  * landing bits over [b_k, b_{k+1}] are all in {0,1} and
    A_{k+1}(b_{k+1}+1) not in {0,2} (block maximality);
  * the maximal 1-Lipschitz container of the generating stretch is exactly
    [1, b_{k+1}+1]: it starts at position 1 (block's first column) and ends
    at the unique chain break. Derived: landing positions 1..b_{k+1} of row
    k+1 are all in {0,2} so |h(i+1)-h(i)| <= 1 for i = 1..b_{k+1}; and the
    landing block ends at b_{k+1} means position b_{k+1}+1 !in {0,2}, i.e.
    |h(b_{k+1}+1) - h(b_{k+1}+2)| >= 2.
"""
import json
import time
import sys
from collections import Counter

from lib.gilbreath import primes_up_to, rows_generator, block_profile, EXPECTED

W_LIMIT = 20_000_000
GENUINE = [34, 56, 64, 68, 94, 96, 110, 112, 126, 130, 134, 146]
CAPPED = 161
ALL13 = GENUINE + [CAPPED]
DEPTH = 147          # maximum needed row (landing row of event 146)
MINLEN = 100         # control threshold: "other stretches" of >= MINLEN positions


def rle(seq):
    """Run-length encode seq -> list of (value, count)."""
    runs = []
    cur, cnt = seq[0], 1
    for v in seq[1:]:
        if v == cur:
            cnt += 1
        else:
            runs.append((cur, cnt))
            cur, cnt = v, 1
    runs.append((cur, cnt))
    return runs


def fmt_runs(runs, limit=25):
    toks = [f"{v}^{c}" for v, c in runs]
    if len(toks) <= limit:
        return " ".join(toks)
    return " ".join(toks[:limit - 10]) + "  ...(%d runs total)...  " % len(toks) + " ".join(toks[-10:])


def main():
    t0 = time.time()
    data = json.load(open('code/out/blocks_depth1000.json'))
    assert data['num_primes'] == 1_270_607 and data['sieve_limit'] == W_LIMIT
    b = data['b']

    def bk(r):
        return b[r - 1]

    events = {k: (bk(k), bk(k + 1)) for k in ALL13}
    for k, (x, y) in events.items():
        assert y > x, (k, x, y)

    out = []
    P = out.append

    P("# Giant generating stretches — 12 genuine (2,4)-events\n")
    P(f"Depth {DEPTH}, W = 1,270,607 primes (sieve 2e7), exact integers, one worker.\n")

    # ---------------- oracle ----------------
    primes = primes_up_to(W_LIMIT)
    assert len(primes) == 1_270_607
    gen5 = rows_generator(primes_up_to(60), 5)
    got = [next(gen5) for _ in range(6)]
    assert all(got[k][:12] == EXPECTED[k] for k in range(1, 6))
    P("Oracle: rows A_1..A_5 reproduce problem.md exactly. "
      f"Sieve: {len(primes)} primes up to 2e7.\n")

    gen = rows_generator(primes, DEPTH)
    assert next(gen) == primes

    gen_windows = {}    # k -> halved values of row k over [b_k, b_{k+1}+1]
    landing_bits = {}   # k -> bytes (0/1) of row k+1 halved over [b_k, b_{k+1}]
    control = {}        # k -> dict with container, stretches, rank stats

    for r in range(1, DEPTH + 1):
        row = next(gen)
        L = len(row)
        # --- (a) block-profile cross-checks: event rows (13) + landing rows (12)
        if r in ALL13 or (r - 1) in GENUINE:
            p = block_profile(row)
            assert p == bk(r), (r, p, bk(r))
        # --- event rows
        if r in GENUINE:
            bcur, bnxt = events[r]
            assert row[bcur] == 2 and row[bcur + 1] == 4, (r, row[bcur], row[bcur + 1])
            vals = [row[i] >> 1 for i in range(bcur, bnxt + 2)]
            diffs = [vals[i + 1] - vals[i] for i in range(len(vals) - 1)]
            assert all(d in (-1, 0, 1) for d in diffs), r
            gen_windows[r] = vals
            # --- (d) CONTROL: maximal 1-Lipschitz stretches of the whole row,
            # over halved positions 1..L-1 (position 0 is odd).
            # |h(i+1)-h(i)| <= 1  <=>  |row[i]-row[i+1]| <= 2  (values even).
            stretches = []
            s = 1
            for i in range(1, L - 1):
                if abs(row[i] - row[i + 1]) > 2:
                    if i - s + 1 >= MINLEN:
                        stretches.append((s, i))
                    s = i + 1
            if L - 1 - s + 1 >= MINLEN:
                stretches.append((s, L - 1))
            container = None
            for (a, e_) in stretches:
                if a <= bcur <= e_:
                    container = (a, e_)
                    break
            assert container is not None, r
            assert container == (1, bnxt + 1), (r, container, bnxt)
            lengths = [e_ - a + 1 for (a, e_) in stretches]
            clen = bnxt + 1
            rank = 1 + sum(1 for ln in lengths if ln > clen)
            ties = sum(1 for ln in lengths if ln == clen) - 1
            others = [(a, e_, e_ - a + 1) for (a, e_) in stretches if not (a <= bcur <= e_)]
            runner = max(others, key=lambda t: t[2], default=None)
            control[r] = dict(container=container, stretches=stretches, rank=rank,
                              ties=ties, runner=runner)
        # --- landing rows of genuine events
        if r - 1 in GENUINE:
            k = r - 1
            bcur, bnxt = events[k]
            bits = bytearray(row[i] >> 1 for i in range(bcur, bnxt + 1))
            assert all(v <= 1 for v in bits), k
            assert row[bnxt + 1] not in (0, 2), k   # block maximality
            landing_bits[k] = bytes(bits)

    assert set(gen_windows) == set(GENUINE) and set(landing_bits) == set(GENUINE)
    P(f"Cross-checks (a): block_profile == stored b for all 13 giant event rows "
      f"(12 genuine + capped 161) and all 12 genuine landing rows; "
      f"step law (2,4), chain 1-Lipschitz, landing bits in {{0,1}}, "
      f"block maximality, and container == [1, b_{{k+1}}+1] verified for all 12.\n")

    # ---------------- per-event report ----------------
    details = []
    for k in GENUINE:
        bcur, bnxt = events[k]
        j = bnxt - bcur
        vals = gen_windows[k]
        bits = landing_bits[k]
        ctrl = control[k]
        (cs, ce), rank, ties, runner = (ctrl['container'], ctrl['rank'],
                                        ctrl['ties'], ctrl['runner'])
        assert len(vals) == j + 2 and len(bits) == j + 1
        diffs = [vals[i + 1] - vals[i] for i in range(len(vals) - 1)]
        lvl = diffs.count(0)
        up = diffs.count(1)
        dn = diffs.count(-1)
        drift = sum(diffs)
        vmin, vmax = min(vals), max(vals)
        vc = Counter(vals)
        dom, domc = vc.most_common(1)[0]
        v_runs = rle(vals)
        bits_runs = rle(list(bits))
        zc = sum(1 for v in bits if v == 0)
        oc = len(bits) - zc
        longest0 = max((c for v, c in bits_runs if v == 0), default=0)
        longest1 = max((c for v, c in bits_runs if v == 1), default=0)
        head_bits = ''.join(str(v) for v in bits[:24])
        stretches = ctrl['stretches']
        lengths = sorted((e_ - a + 1 for (a, e_) in stretches), reverse=True)
        n_stretch = len(stretches)

        D = dict(k=k, bcur=bcur, bnxt=bnxt, j=j, vals=vals, v_runs=v_runs,
                 vmin=vmin, vmax=vmax, dom=dom, domc=domc, n=len(vals),
                 lvl=lvl, up=up, dn=dn, drift=drift,
                 bits_runs=bits_runs, zc=zc, oc=oc, longest0=longest0,
                 longest1=longest1, head_bits=head_bits,
                 cs=cs, ce=ce, clen=ce - cs + 1, rank=rank, ties=ties,
                 runner=runner, n_stretch=n_stretch, lengths=lengths,
                 distinct=len(vc))
        details.append(D)

        P(f"--- Event k={k}  b_k={bcur}  b_{{k+1}}={bnxt}  j={j} (landing row {k + 1}) ---")
        P(f"(b) generating stretch h_k over [{bcur}, {bnxt + 1}], len {len(vals)} = j+2")
        P(f"    rle values (value^count, in order): {fmt_runs(v_runs)}")
        P(f"    distinct={D['distinct']} min={vmin} max={vmax} "
          f"dominant={dom} (count {domc}, frac {domc / len(vals):.4f})")
        P(f"    steps: level {lvl} ({lvl / len(diffs):.4f}), up {up} "
          f"({up / len(diffs):.4f}), down {dn} ({dn / len(diffs):.4f}); "
          f"net drift {drift:+d}; level+up = {(lvl + up) / len(diffs):.4f}")
        P(f"(c) landing bits row {k + 1} over [{bcur}, {bnxt}], len {len(bits)} = j+1")
        P(f"    rle 0/1: {fmt_runs(bits_runs)}")
        P(f"    #0={zc} ({zc / len(bits):.4f})  #1={oc} ({oc / len(bits):.4f})  "
          f"longest 0-run {longest0}, longest 1-run {longest1}; head: {head_bits}")
        P(f"(d) CONTROL row {k}: {n_stretch} maximal 1-Lipschitz stretches "
          f"with >= {MINLEN} positions total")
        P(f"    top lengths: {lengths[:12]}{' ...' if len(lengths) > 12 else ''}")
        if runner is not None:
            P(f"    runner-up (longest stretch other than the container): "
              f"[{runner[0]}, {runner[1]}] len {runner[2]}")
        else:
            P(f"    no other stretch >= {MINLEN} positions")
        P(f"    container of generating stretch = [{cs}, {ce}] len {ce - cs + 1} = "
          f"b_{{k+1}}+1 = {bnxt + 1}; rank by length among the {n_stretch}: "
          f"{rank} (ties: {ties})")
        P("")

    # ---------------- summary ----------------
    P("## Summary across the 12 genuine giants\n")
    hdr = (f"{'k':>4} {'b_k':>8} {'j':>7} {'stretch':>7} {'dist':>4} {'min':>4} "
           f"{'max':>6} {'dom':>4} {'domfrac':>8} {'lvlf':>6} {'drift':>8} "
           f"{'contLen':>9} {'rank':>4} {'#>=100':>6} {'runner':>9}")
    P(hdr)
    for D in details:
        P(f"{D['k']:>4} {D['bcur']:>8} {D['j']:>7} {D['n']:>7} {D['distinct']:>4} "
          f"{D['vmin']:>4} {D['vmax']:>6} {D['dom']:>4} {D['domc'] / D['n']:>8.4f} "
          f"{D['lvl'] / (D['n'] - 1):>6.4f} {D['drift']:>+8d} {D['clen']:>9} "
          f"{D['rank']:>4} {D['n_stretch']:>6} {D['runner'][2] if D['runner'] else 0:>9}")
    P("")

    # structural pattern
    from statistics import median
    lvlfs = [D['lvl'] / (D['n'] - 1) for D in details]
    doms = [(D['dom'], D['domc'] / D['n']) for D in details]
    drifts = [D['drift'] for D in details]
    P(f"Level-step fraction (plateau weight): min {min(lvlfs):.4f}, "
      f"median {median(lvlfs):.4f}, max {max(lvlfs):.4f}.")
    P(f"Dominant (value, frac) per event: "
      f"{', '.join(f'{v}:{f:.3f}' for v, f in doms)}")
    P(f"Dominant-value multiset: {Counter(v for v, f in doms)}")
    P(f"Net drift of the chain (h(b_{{k+1}}+1) - h(b_k)): "
      f"{drifts}  (always nonnegative: {all(d >= 0 for d in drifts)})")
    tot_j = sum(D['j'] for D in details)
    tot_fresh1 = sum(D['oc'] for D in details)
    P(f"Total fresh {0,2} entries generated by the 12 giants: "
      f"{tot_j}; landing bits are 1 (chain climbing/falling) in "
      f"{tot_fresh1} = {tot_fresh1 / (tot_j + 12):.4f} of them, 0 (level step) "
      f"otherwise.")
    all_rank1 = all(D['rank'] == 1 for D in details)
    P(f"Container is the longest 1-Lipschitz stretch of its row in all 12: "
      f"{all_rank1}.")
    P(f"Container == [1, b_{{k+1}}+1] in all 12 (start at block's first column, "
      f"end at the chain break that defines the landing block end).")
    P(f"\nCost: one worker; time {time.time() - t0:.1f} s wall; "
      f"space O(W) ~ 220 MB peak (current row + 12 kept windows).")

    txt = "\n".join(out)
    with open('code/out/giant_stretches.captured.txt', 'w') as f:
        f.write(txt + "\n")
    with open('code/out/giant_stretches.md', 'w') as f:
        f.write(txt + "\n")
    print(txt)


if __name__ == "__main__":
    main()