import Mathlib.Data.Real.Basic
import Mathlib.Data.Set.Finite.Basic
import Mathlib.Data.Set.Card

/-!
FIX (this pass): the previous version took `rankFinitenessTheorem` as a
hypothesis typed as the theorem's own conclusion
(`({z | ...}).Finite`), so the "proof" received the answer as an assumption
and returned it; `analyticExpansion` and `finitelyGeneratedModule` were
`Prop` parameters whose proofs were named `_hAnalytic`/`_hModule` and never
used. The genuine content — that a finitely generated almost-regular module
plus the cited rank theorem gives finiteness of the displacement's zero set —
is the open analytic step, so it is now stated as a real (if abstract)
hypothesis on the module structure and left `sorry`, rather than assumed
directly as the conclusion.
-/
namespace H16Zeros

abbrev Parameter := ℝ × ℝ
abbrev Section := ℝ

/-- A sector transition map on the transversal, with parameters in `K`. -/
def Transition (_K : Set Parameter) : Type := Parameter → Section → Section

/-- A finite cyclic composition of sector transition maps. -/
def ComposeTransitions (K : Set Parameter) (maps : List (Transition K)) : Transition K :=
  fun p x => (maps.foldr (fun T r => fun q y => T q (r q y)) (fun _ y => y)) p x

/-- The displacement function obtained by composing the sector maps and subtracting
identity.  `D p x = 0` is the encoded zero condition. -/
def Displacement (K : Set Parameter) (maps : List (Transition K)) : Transition K :=
  fun p x => ComposeTransitions K maps p x - x

/-- An almost-regular module of finite rank generated by the transition maps'
analytic expansions — the actual structural input the cited rank theorem
needs, in place of a bare `Prop`. Deliberately carries only `rank` and
`generators`: the real membership condition (the displacement's analytic
expansion lying in the module these generators span, in the almost-regular
sense Zhu-Rousseau-style rank theorems use) is not yet held from the
literature, so it is not stated here rather than faked as a tautology. -/
structure AlmostRegularModule (K : Set Parameter) (maps : List (Transition K)) where
  rank : ℕ
  generators : Fin rank → Parameter → Section → ℝ

/--
The precise formal content of the G-zeros node: assuming the analytic transition
maps belong to a finitely generated almost-regular module, and that the cited
rank/finiteness theorem applies to the resulting displacement, its zero set on
`K × [0,∞)` is finite and hence has a natural-number bound.  The mathematical
inputs are explicit hypotheses rather than silently asserted facts.
-/
theorem displacement_zeros_finite
    (K : Set Parameter) (maps : List (Transition K))
    (analyticExpansion : Prop)
    (hAnalytic : analyticExpansion)
    (module : AlmostRegularModule K maps) :
    ∃ N : ℕ, ({z : Parameter × Section |
      z.1 ∈ K ∧ 0 ≤ z.2 ∧ Displacement K maps z.1 z.2 = 0}).Finite ∧
      ({z : Parameter × Section |
        z.1 ∈ K ∧ 0 ≤ z.2 ∧ Displacement K maps z.1 z.2 = 0}).ncard ≤ N := by
  sorry

#print axioms displacement_zeros_finite

/- gap
id: h16-2-g-zeros-rank-finiteness
lemma: ∀ (K, maps, analyticExpansion holding, module : AlmostRegularModule K
  maps), ∃ N, the zero set of `Displacement K maps` on `K × [0,∞)` is finite
  with ncard ≤ N
status: sorry
next: state the actual almost-regular/finite-rank normal form for the
  transition maps (the `AlmostRegularModule.spans` field here is a stand-in,
  not the real membership condition — see the note in that field), cite the
  rank-finiteness theorem this node is named for as a `Cited.*` axiom over
  that real structure, and specialise to `N := module.rank`. This is the step
  the previous `rankFinitenessTheorem : Z.Finite` hypothesis smuggled in
  instead of deriving.
-/

end H16Zeros
