from fractions import Fraction

# Verify the user's claim: r_n = f(n)/f(n-1) is generated by Calkin-Wilf.
# f = number of hyperbinary reps = paper's b(n), b(0)=1.
# recurrence: f(2n+1)=f(n), f(2n+2)=f(n)+f(n+1)
def f(n):
    if n == 0: return 1
    if n % 2 == 1:
        return f(n//2)
    else:
        k = n//2
        return f(k) + f(k-1)

# Check the user's three recurrences:
# f(2n)=f(n)+f(n-1), f(2n+1)=f(n), f(2n-1)=f(n-1)
ok = True
for n in range(1, 200):
    ok &= (f(2*n) == f(n) + f(n-1))
    ok &= (f(2*n+1) == f(n))
    ok &= (f(2*n-1) == f(n-1))
print("user's 3 recurrences hold:", ok)

# Now verify the Calkin-Wilf ratio claim.
# r_n = f(n)/f(n-1). Claim: root r_1 = 1/1.
# For each n, the ratio r_n should equal the fraction obtained by walking the
# Calkin-Wilf tree from 1/1 following the binary digits of n (after leading '1')
# with 0 -> r+1 and 1 -> r/(r+1). Let's test both bit-labelings.
def ratio_via_recurrence(n):
    return Fraction(f(n), f(n-1))

def ratio_via_tree(n, zero_map):
    # walk binary digits of n excluding leading 1
    bits = bin(n)[3:]
    r = Fraction(1,1)  # root 1/1
    for ch in bits:
        if ch == '0':
            r = zero_map(r)
        else:
            # one must be the '1' map; try both conventions
            pass
    return r

# Convention A: bit 0 -> r+1, bit 1 -> r/(r+1)
def ratio_treeA(n):
    r = Fraction(1,1)
    for ch in bin(n)[3:]:
        if ch == '0':
            r = r + 1
        else:
            r = r / (r + 1)
    return r

# Convention B: bit 0 -> r/(r+1), bit 1 -> r+1
def ratio_treeB(n):
    r = Fraction(1,1)
    for ch in bin(n)[3:]:
        if ch == '0':
            r = r / (r + 1)
        else:
            r = r + 1
    return r

for n in range(1, 100):
    r = ratio_via_recurrence(n)
    assert ratio_treeA(n) == r, (n, "A", r, ratio_treeA(n))
    # B is checked just to see which matches
print("Convention A (0->r+1, 1->r/(r+1)) matches r_n for n=1..99: True")

# But note: the user's mapping is tied to *trailing* bits of n, not leading.
# The bit we read corresponds to the *last* step. Everything is consistent since
# tree path is unique. Print a few.
for n in range(1, 9):
    print(n, bin(n), "ratio=", ratio_via_recurrence(n), "treeA=", ratio_treeA(n))
