#!/usr/bin/env python3
"""Robust rerun of the Bautin focal-value extension to degree 14.

Same recurrence as lyap_extend.py but with a corrected poly_terms that
handles rational coefficients. Reports for each even degree d:
  * whether the obstruction is a genuine polynomial in (A,C,D,E,F),
  * its monomial count and homogeneous degree,
  * membership of the higher obstructions in the ideal generated by the
    earlier ones (exact Groebner reduction over QQ).
Bounded degree 14 -> polynomial time in the (fixed) degree ring.
"""
import sympy as sp
import time

u, v = sp.symbols("u v")
A, C, D, E, F = sp.symbols("A C D E F")
params = [A, C, D, E, F]
Q1 = A * u**2 + C * u * v + D * v**2
Q2 = E * u * v + F * v**2


def rotation(poly):
    return sp.expand(-v * sp.diff(poly, u) + u * sp.diff(poly, v))


def poly_info(poly_expr):
    e = sp.expand(sp.together(poly_expr))
    num, den = sp.fraction(e)
    if den != 1:
        return None
    p = sp.Poly(num, *params)
    monoms = list(p.terms())  # [(exp_tuple, coeff)]
    degs = [sum(m) for m, _ in monoms]
    hdeg = degs[0] if all(d == degs[0] for d in degs) else None
    return len(monoms), hdeg


t0 = time.time()
V = {2: (u**2 + v**2) / 2}
obstruction = {}
for degree in range(3, 15):
    coeffs = sp.symbols(f"c{degree}_0:{degree + 1}")
    correction = sum(coeffs[j] * u ** (degree - j) * v**j
                     for j in range(degree + 1))
    unknowns = list(coeffs)
    equation = sp.expand(
        rotation(correction)
        + Q1 * sp.diff(V[degree - 1], u)
        + Q2 * sp.diff(V[degree - 1], v)
    )
    radial = None
    if degree % 2 == 0:
        radial = sp.symbols(f"L{degree}")
        unknowns.append(radial)
        equation -= radial * (u**2 + v**2) ** (degree // 2)
    polynomial = sp.Poly(equation, u, v)
    equations = [polynomial.coeff_monomial(u ** (degree - j) * v**j)
                 for j in range(degree + 1)]
    if degree % 2 == 0:
        equations.append(coeffs[0])
    solution = sp.solve(equations, unknowns, dict=True, simplify=False)[0]
    V[degree] = sp.expand(correction.subs(solution))
    if radial is not None:
        obstruction[degree] = sp.factor(solution[radial])

print(f"recurrence through degree 14: {time.time() - t0:.1f}s")
print("\nd  monomials  hdeg  is_polynomial")
for d in (4, 6, 8, 10, 12, 14):
    info = poly_info(obstruction[d])
    if info is None:
        print(f"{d}  NOT a polynomial (rational denominator)")
    else:
        print(f"{d}  {info[0]:9d}  {str(info[1]):5s}  yes")

print("\nmonomial-count sequence L_d (d = 4,6,8,10,12,14):",
      [poly_info(obstruction[d])[0] for d in (4, 6, 8, 10, 12, 14)])

# ---- ideal membership ----
b = time.time()
G = sp.groebner([obstruction[4], obstruction[6], obstruction[8], obstruction[10]],
                *params, order="lex")
for d in (12, 14):
    rem, _ = G.reduce(sp.expand(sp.together(obstruction[d])))
    print(f"L{d} in <L4,L6,L8,L10>: remainder == 0 ?", sp.simplify(rem) == 0)
print(f"groebner-reduction block: {time.time() - b:.1f}s")
