"""Hunt: is there a nonzero common zero of the n=5 traceless-slice ideal?

If a3^e is never in I_slice, V(I_slice) contains a point with a3 != 0,
which would be a counterexample to CA_5 (impossible -- CA_5 settled).
So either (a) my slice resultants are wrong, or (b) the grevlex GB/LM
read is misleading.  Cross-check via: (1) verify GB generates the ideal;
(2) verify the pure-power origin is a zero; (3) numeric/near search for a
nonzero zero; (4) verify the slice's zero set really is {0} by eliminating.
"""
from sympy import symbols, Poly, expand, resultant, groebner, QQ, binomial

x = symbols("x")
a1, a2, a3, a4, a5 = symbols("a_1 a_2 a_3 a_4 a_5")
a = [a1, a2, a3, a4, a5]


def hasse(f, i):
    p = Poly(expand(f), x)
    c = {j: p.coeff_monomial(x ** j) for j in range(p.degree() + 1)}
    return sum(binomial(j, i) * cc * x ** (j - i)
               for j, cc in c.items() if j >= i)


n = 5
f = x ** n + sum(a[i] * x ** (n - 1 - i) for i in range(n))
sl = [a2, a3, a4, a5]
R = [expand(resultant(f, hasse(f, i), x).subs(a1, 0)) for i in (1, 2, 3, 4)]

# sanity: origin is a common zero (pure power (x)^5 traceless)
zero_pt = {a2: 0, a3: 0, a4: 0, a5: 0}
print("all R_i vanish at origin:", all(r.subs(zero_pt) == 0 for r in R))

# ideal generated by R vs GB: check GB generators reduce to 0 mod R?
print("R_1..R_4 in grevlex  (should be 0):")
gb = groebner(R, *sl, order="grevlex")
for g in gb.polys:
    pass  # skip

# Are the R_i each reducible to 0 by the GB (=> GB generates same ideal)?
def reduce_by_gb(expr):
    return gb.reduce(Poly(expand(expr), *sl, domain=QQ))

ok = True
for i, r in enumerate(R):
    rr = gb.reduce(Poly(expand(r), *sl, domain=QQ))
    if isinstance(rr, tuple):
        rr = rr[0]
    if rr != 0:
        ok = False
        print(f"  R_{i} NOT reduced to 0 by GB -- GB may not generate ideal!")
print("GB generates the stated ideal:", ok)

# numeric search for a nonzero zero near origin
import numpy as np
from numpy.polynomial import polynomial as P
# build R_i as functions
Rf = [Poly(r, *sl, domain=QQ) for r in R]
def ev(pts):
    return np.array([
        [float(Rff.subs({sv: float(v) for sv, v in zip(sl, p)})) for Rff in Rf]
        for p in pts])
# random small sample
rng = np.random.default_rng(0)
pts = rng.uniform(-0.5, 0.5, size=(2000, 4))
vals = ev(pts)
norms = np.abs(vals).sum(axis=1)
j = np.argmin(norms)
print("closest sampled point to a zero (should be ~origin):",
      np.round(pts[j], 4), "|R|_1 =", norms[j])
