"""Correct nilpotency probe for the n=5 traceless-slice ideal.

CA_5 settled true => V(I_slice) = {0} (a1=0 forces r=0 forces f=x^5), so
I is 0-dim and EVERY a_j must have a pure power in I.  Verify membership
with the correct sympy API.  If a3 shows NO power, the grevlex GB from
sympy is incomplete/wrong, not the math.
"""
from sympy import symbols, Poly, expand, resultant, groebner, QQ, binomial
from sympy.polys.polytools import reduced

x = symbols("x")


def hasse(f, i):
    p = Poly(expand(f), x)
    c = {j: p.coeff_monomial(x ** j) for j in range(p.degree() + 1)}
    return sum(binomial(j, i) * cc * x ** (j - i)
               for j, cc in c.items() if j >= i)


def in_ideal(expr, gb_polys, sl):
    """True iff expr is in the ideal generated by gb_polys (exact reduction)."""
    r = reduced([Poly(expand(expr), *sl, domain=QQ)], gb_polys, sl)
    rem = r[1]  # list of remainders, one per input poly
    rr = rem[0] if isinstance(rem, (list, tuple)) else rem
    return rr == 0


for n in (4, 5):
    a = symbols(f"a_1:{n+1}")
    f = x ** n + sum(a[i] * x ** (n - 1 - i) for i in range(n))
    sl = list(a[1:])
    R = [expand(resultant(f, hasse(f, i), x).subs(a[0], 0)) for i in range(1, n)]
    gb = groebner(R, *sl, order="grevlex")
    gb_polys = [g.as_poly(*sl, domain=QQ) for g in gb.polys]
    print(f"=== n={n}: quotient QQ[{' '.join(map(str,sl))}]/I ===")
    for vv in sl:
        ks = [k for k in range(1, 26) if in_ideal(vv ** k, gb_polys, sl)]
        print(f"   {vv}: {vv}^k in I for k = {ks}")
