

# This file was *autogenerated* from the file code/bremner2_genus.sage
from sage.all_cmdline import *   # import sage library

_sage_const_4 = Integer(4); _sage_const_9409 = Integer(9409); _sage_const_1352 = Integer(1352); _sage_const_3 = Integer(3); _sage_const_1346 = Integer(1346); _sage_const_2 = Integer(2); _sage_const_5041 = Integer(5041); _sage_const_30252 = Integer(30252); _sage_const_27554 = Integer(27554)# Genus of Y^2 = Q(x,1) for each of Bremner II's three (13) quartics at lambda=13.
# Each Q is a homogeneous quartic in (p,q); set x=p/q and take the affine model Y^2=f(x).
from sage.all import *

quartics = {
 'Q1a': _sage_const_4 *(_sage_const_9409 *x**_sage_const_4  + _sage_const_1352 *x**_sage_const_3  + _sage_const_1346 *x**_sage_const_2  - _sage_const_1352 *x + _sage_const_9409 ),
 'Q1b': _sage_const_4 *(_sage_const_5041 *x**_sage_const_4  - _sage_const_30252 *x**_sage_const_3  + _sage_const_27554 *x**_sage_const_2  + _sage_const_30252 *x + _sage_const_5041 ),
 'Q1c': _sage_const_4 *(_sage_const_9409 *x**_sage_const_4  + _sage_const_30252 *x**_sage_const_3  + _sage_const_1346 *x**_sage_const_2  - _sage_const_30252 *x + _sage_const_9409 ),
}

x = var('x')
for name, f in quartics.items():
    fpoly = QQ['x'](f)
    # squarefree?
    print(name, "leading coeff", fpoly.leading_coefficient())
    # smooth projective curve X: v^2 = w^4 f(w?) ... put x=X/Z, y=Y/Z^2:
    # use Sage's genus on HyperellipticCurve with odd/even degree.
    R = PolynomialRing(QQ, 'x')
    ff = R(fpoly)
    # Curve y^2 = f(x), f degree 4: HyperellipticCurve handles even degree -> genus 2? 
    H = HyperellipticCurve(ff)
    print("   HyperellipticCurve genus:", H.genus())
    # Also check the squarefree-ness of f and of the "points at infinity" structure.
    print("   f squarefree:", ff.is_squarefree())
    # Distinct roots count over QQbar
    nroots = len(ff.roots(QQbar, multiplicities=False))
    print("   distinct roots over QQbar:", nroots)

