#!/usr/bin/env python3
"""Study the Mersenne per-residue constants c_r (normalized by /2) and find
the exact closed form for the whole structure.

For P = 2^k - 1, the entries c_r/2 form a self-similar array.  We test the
conjecture that c_r/2 satisfies a 2-adic / doubling recursion, and that
sum c_r = 3^k - 3 (already confirmed).  Goal: a closed form for c_r itself
and for the block density slope (3^k-3)/(2^k-1)^2.

Here we test whether the c_r/2 array is generated by a simple recursion:
starting from [1], the next level doubles in length by some rule.  Compare
level k and k+1 arrays.
"""
P7  = [1,3,2,2,1,2,1]
P15 = [1,7,4,4,2,4,2,2,1,4,2,2,1,2,1]
P31 = [1,15,8,8,4,8,4,4,2,8,4,4,2,4,2,2,1,8,4,4,2,4,2,2,1,4,2,2,1,2,1]

# Hypothesis: c_{r}/2 = 2^{v} where the value depends on r via a pattern.
# Observe P15 = P7 interleaved with something?  P15 has block of length 8:
#   [1,7,4,4,2,4,2,2] then [1,4,2,2,1,2,1]
# P7 = [1,3,2,2,1,2,1].  If we double-rescale: new array = [2x for x in P7 with 1 replaced...]
# Let's compute: P15[0::2] and P15[1::2]
print("P15 even:", P15[0::2])
print("P15 odd :", P15[1::2])
print("P31 even:", P31[0::2])
print("P31 odd :", P31[1::2])
# P15[0::2] should be P7? [1,4,2,1,2,1,2,...]  len 8
# Actually interleave structure: it looks like c_r/2 is a binary-ish self-similar object.
for k in [3,4,5]:
    P = 2**k-1
    arr = {3:P7,4:P15,5:P31}[k]
    # any pattern?  print positions where arr==1
    ones=[r for r in range(P) if arr[r]==1]
    print(f"k={k} P={P} positions with c_r/2==1:", ones)
    # also max
    print(f"   max c_r/2 = {max(arr)}, at {[r for r in range(P) if arr[r]==max(arr)]}")
