#!/usr/bin/env python3
"""Independent oracle for PE763 D(N), written to differ structurally from
lib/amoeba.next_level_bits so the large-N values get a second route.

Differences from the primary oracle:
  * succeeds are generated by first building the set of non-blocked cubes
    (those whose three positive-unit neighbours are all empty) via a per-cube
    neighbor precence test that scans the occupied mask once into a dict of
    cube->columns, then testing each cube against its three neighbours;
  * the new config mask is assembled by clearing the divided cube's bit and
    OR-ing in the three neighbour bits, and configs are hashed as Python ints
    just as the primary does, but the whole step is re-derived independently
    rather than copied.

Validated by reproducing D(0..13), whose values are independently established
(D(2)=3, D(10)=44499 from the statement; D(12)=514419, D(13)=1749267 from the
frozenset oracle).  If this route also yields 5949063 at N=14, the primary
bitmask result is confirmed by a second implementation.
"""

import sys
import time

E = ((1, 0, 0), (0, 1, 0), (0, 0, 1))


def step(level, W):
    """One division step over a set of int-masked configs (width W).

    Position of bit i: (x*W + y)*W + z, with x,y,z in [0, W-1].
    """
    W2 = W * W
    nxt = set()
    nxt_add = nxt.add
    for S in level:
        # occupied cells as a frozenset of (x,y,z)
        cells = []
        m = S
        while m:
            low = m & -m
            i = low.bit_length() - 1
            m ^= low
            x_, r = divmod(i, W2)
            y_, z_ = divmod(r, W)
            cells.append((x_, y_, z_))
        occupied = set(cells)
        # a cube can divide iff all three forward neighbours are empty
        for (x, y, z) in cells:
            a = (x + 1, y, z)
            b = (x, y + 1, z)
            c = (x, y, z + 1)
            if a not in occupied and b not in occupied and c not in occupied:
                ns = S ^ (1 << (x * W2 + y * W + z))
                ns |= (1 << ((x + 1) * W2 + y * W + z)
                       | 1 << (x * W2 + (y + 1) * W + z)
                       | 1 << (x * W2 + y * W + (z + 1)))
                nxt_add(ns)
    return nxt


def main(max_n, budget):
    W = max_n + 1
    level = {1}
    results = {0: 1}
    print("D(0) = 1")
    for n in range(1, max_n + 1):
        t0 = time.time()
        level = step(level, W)
        dt = time.time() - t0
        if not level:
            print(f"level {n}: empty after {dt:.2f}s")
            break
        results[n] = len(level)
        print(f"D({n}) = {len(level):>12d}   (level in {dt:.2f}s)", flush=True)
        if dt > budget:
            print(f"Stopping: level {n} took {dt:.2f}s > budget {budget}s")
            break
        if len(level) > 5_000_000:
            print(f"Stopping: frontier {len(level)} > 5M cap")
            break
    return results


if __name__ == "__main__":
    max_n = int(sys.argv[1]) if len(sys.argv) > 1 else 14
    budget = float(sys.argv[2]) if len(sys.argv) > 2 else 900.0
    main(max_n, budget)
